### ISSUE TITLE
提供一个使用Let's Encrypt免费SSL证书的教程（希望能被合并到wiki

### ISSUE THREAD

**Issue by lxdlam** [esdeathlove/ss-panel-v3-mod#116]
注：以下以CentOS6为例，请确保按照wiki教程正确配置ss-panel
1、新建一个文件夹来存放certbot
`cd /home && mkdir certbot && cd certbot`
2、下载并解压certbot
`wget https://dl.eff.org/certbot-auto`
`chmod a+x certbot-auto`
3、停止nginx进程
`service nginx stop`
4、获取一个证书
`./certbot-auto certonly -w <你的ss-panel文件夹> -d <你的域名>`
5、下面这个图d的提示中选择2
![qq 20160606165617](https://cloud.githubusercontent.com/assets/7735691/15816862/a3880acc-2c07-11e6-99f5-e6849c1c88e2.png)
6、编辑你的nginx配置文件
`nano /usr/local/nginx/conf/vhost/<域名>.conf`
在其中加入

```
server {
listen 443;
ssl_certificate /etc/letsencrypt/live/<你的域名>/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/<你的域名>/privkey.pem;
}
```

当然，你也可以直接改动原有的server段，直接使用https访问
7、开启nginx
`service nginx start`
8、使用`https://<你的域名>`访问即可
9、设置自动续期
由于Let's Encrypt的证书是180天有效，所以我们要设置自动续期
`crontab -e`
加入如下
`0 0 <你申请证书的日期，如6月24日就填24> */3 * service nginx stop && ./home/certbot/certbot-auto renew --quiet && service nginx start`
保存即可。

**Comment by glzjin** [comment]
先放在这，不关闭先，谢谢。

**Comment by ChromiumX** [comment]
真要SSL，弄个沃通的免费就行

**Comment by wudimenghuan** [comment]
沃通收购了startssl，你懂的

**Comment by 512557852** [comment]
听说沃通有问题，可能要被拉黑

**Comment by a86913179** [comment]
你这个太复杂。直接去certbot官网就有教程，按提示来就行。运行certbot-auto certonly然后图形界面选webroot，不用关闭nginx，填入域名，多个用空格隔开，填入路径，然后就会自动生成了，选standlone需要占用80和443端口，要把nginx停掉，而且cloudflare不支持standlone只支持webroot。

**Comment by cibyyang** [comment]
大神 第4步、获取一个证书
./certbot-auto certonly -w <你的ss-panel文件夹> -d <你的域名>
这个地方我非要用/sspanel/public 这个文件夹才能获取证书 但配置nginx后还是不能ssl访问?
这个要怎么处理?或者说你们根本不是用这个文件夹的?
