### ISSUE TITLE
如果您的用户等级过期不降级

### ISSUE THREAD

**Issue by WhoRUa** [esdeathlove/ss-panel-v3-mod#313]
30 22 \* \* \* php /home/wwwroot/ss.panel/xcat sendDiaryMail
*/1 \* \* \* \* php /home/wwwroot/ss.panel/xcat synclogin
*/1 \* \* \* \* php /home/wwwroot/ss.panel/xcat syncvpn
0 0 \* \* \* php -n /home/wwwroot/ss.panel/xcat dailyjob
*/1 \* \* \* \* php /home/wwwroot/ss.panel/xcat checkjob
*/1 \* \* \* \* php -n /home/wwwroot/ss.panel/xcat syncnas

请把其中的 php 命令改为绝对路径
例如（lj2007331的lnmp中）：
30 22 \* \* \* /usr/local/php/bin/php /home/wwwroot/ss.panel/xcat sendDiaryMail
*/1 \* \* \* \* /usr/local/php/bin/php /home/wwwroot/ss.panel/xcat synclogin
*/1 \* \* \* \* /usr/local/php/bin/php /home/wwwroot/ss.panel/xcat syncvpn
0 0 \* \* \* /usr/local/php/bin/php -n /home/wwwroot/ss.panel/xcat dailyjob
*/1 \* \* \* \* /usr/local/php/bin/php /home/wwwroot/ss.panel/xcat checkjob
*/1 \* \* \* \* /usr/local/php/bin/php -n /home/wwwroot/ss.panel/xcat syncnas

**Comment by Woophp** [comment]
查询php目录：

which php

**Comment by WhoRUa** [comment]
php /home/wwwroot/ss.panel/xcat checkjob 这行命令控制账户、等级到期后的动作等。如果用户现有流量和等级到期时要置要的流量相同的话，也是不自动降级的。栽过，提醒下

**Comment by bigbigname** [comment]
赵大大
使用您制作的面板有一段时间了，很赞。我后制作了主页，也加上了staff链接~~
这个执行定时任务的命令，在我这边有点问题，我写一下，如果有相同问题的，可以参考。
运行 日志保存在 /var/log/cron
这里提示Dec 25 03:31:01 npro crond[1707]: (/usr/local/php/bin/php) ERROR (getpwnam() failed)
应该是错误没有运行，后来我看了下/etc/crontab这个文件里的描述
要求是# *  *  *  *  * user-name command to be executed
这里有个user-name
所以我将您提供的命令，加上root这个用户名改成如下：（我的网站默认目录是deafult）
30 22 * * * /usr/local/php/bin/php /home/wwwroot/default/xcat sendDiaryMail
*/1 * * * * root /usr/local/php/bin/php /home/wwwroot/default/xcat synclogin
*/1 * * * * root /usr/local/php/bin/php /home/wwwroot/default/xcat syncvpn
0 0 * * * root /usr/local/php/bin/php -n /home/wwwroot/default/xcat dailyjob
*/1 * * * * root /usr/local/php/bin/php /home/wwwroot/default/xcat checkjob
*/1 * * * * root /usr/local/php/bin/php -n /home/wwwroot/default/xcat syncnas
运行一段时间后，日志文件显示
Dec 29 10:59:01 npro CROND[15330]: (root) CMD (/usr/local/php/bin/php -n /home/wwwroot/default/xcat syncnas)
这应该算是好了吧

**Comment by alstarking** [comment]
我来详细说下：CD到你sspanel目录。运行crontab -e
如果改不了，出错就在运行yum install -y vixie-cron

**Comment by alstarking** [comment]
@WhoRUa 如果用户现有流量和等级到期时要置要的流量相同的话，也是不自动降级的。
什么意思？没太看明白。。。。。

**Comment by alstarking** [comment]
@WhoRUa 

照做，依然不降级。。。。。
![1](https://cloud.githubusercontent.com/assets/24618335/21955189/99f28314-daa0-11e6-9b5a-dc8b3ef221d8.png)
![2](https://cloud.githubusercontent.com/assets/24618335/21955190/9e02c284-daa0-11e6-84f5-25b322018355.png)

**Comment by WhoRUa** [comment]
用户现有流量 == $System_Config['enable_class_expire_reset_traffic']='*'中的* 也不会自动降级

**Comment by esdeathlove** [comment]
@WhoRUa 并没有，新版已经修复了这个地方了。

**Comment by alstarking** [comment]
@WhoRUa   我的config里是这样的。

#等级到期时重置为的流量值，GB
$System_Config['enable_class_expire_reset_traffic']='6';


我已经按照上面说的全都加上了，但是到期还是不降级。

**Comment by WhoRUa** [comment]
@esdeathlove 好吧，我以为这是很重要的功能呢 ，谢谢  ！ /// @alstarking 一般是定时任务没有配置好，主要是这个
*/1 * * * * root /usr/local/php/bin/php /home/wwwroot/default/xcat checkjob
网站的自动功能大都写在了 checkjob.php 里面
细心检查，多多学习
