### ISSUE TITLE
通过IPV6连接SS服务端流量不计

### ISSUE THREAD

**Issue by shuangzhijinghua** [esdeathlove/ss-panel-v3-mod#454]
如题，只要是通过V6到客户端的流量都不计算，一点点都不算。

**Comment by Rhilip** [comment]
同样是IPv6的使用者，未发现有同样的问题。
你可以查看下“流量使用记录”面板，看下有没有实际使用流量的产生，以及是否因为你的倍率设置原因（比如设置为0）导致未能结算流量。

**Comment by shuangzhijinghua** [comment]
这个看过，我的服务器V6接入方式是isatap，不是原生V6。
