### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by esdeathlove** [esdeathlove/ss-panel-v3-mod#457]
此处已废弃。

**Comment by glzjin** [comment]
1.http://sexxg.com/
![photo_2016-11-24_22-35-26](https://cloud.githubusercontent.com/assets/7975407/20602039/8a5240de-b296-11e6-8ec3-cfc89189c7ba.jpg)

![photo_2016-11-24_22-37-53](https://cloud.githubusercontent.com/assets/7975407/20602100/c2ec4322-b296-11e6-8fed-a1694e8ec58d.jpg)
![photo_2016-11-24_22-37-55](https://cloud.githubusercontent.com/assets/7975407/20602098/c2c876d6-b296-11e6-8616-d973c5ae7439.jpg)
![photo_2016-11-24_22-37-57](https://cloud.githubusercontent.com/assets/7975407/20602096/c2c4ef84-b296-11e6-831f-8c8599592c03.jpg)
![photo_2016-11-24_22-37-59](https://cloud.githubusercontent.com/assets/7975407/20602094/c2c34b5c-b296-11e6-8ece-81c0ee4644d1.jpg)
![photo_2016-11-24_22-38-00](https://cloud.githubusercontent.com/assets/7975407/20602095/c2c45e16-b296-11e6-95dc-db937aa40820.jpg)
![photo_2016-11-24_22-38-02](https://cloud.githubusercontent.com/assets/7975407/20602097/c2c6b7e2-b296-11e6-8095-42a11202655b.jpg)
![photo_2016-11-24_22-38-03](https://cloud.githubusercontent.com/assets/7975407/20602099/c2ebed82-b296-11e6-95e3-8ae9eb3342f4.jpg)
![photo_2016-11-24_22-38-05](https://cloud.githubusercontent.com/assets/7975407/20602101/c2ed1518-b296-11e6-9daf-b55c305c4853.jpg)
![photo_2016-11-24_22-38-06](https://cloud.githubusercontent.com/assets/7975407/20602102/c2ee7fac-b296-11e6-905d-4018668f71e8.jpg)
![photo_2016-11-24_22-38-08](https://cloud.githubusercontent.com/assets/7975407/20602103/c2f10a10-b296-11e6-92bf-5f99737703fa.jpg)
![photo_2016-11-24_22-38-09](https://cloud.githubusercontent.com/assets/7975407/20602105/c3137f1e-b296-11e6-96f9-b00c04e75b8f.jpg)
![photo_2016-11-24_22-38-11](https://cloud.githubusercontent.com/assets/7975407/20602106/c317df50-b296-11e6-9a33-8f0a35ce0a54.jpg)
![photo_2016-11-24_22-38-12](https://cloud.githubusercontent.com/assets/7975407/20602107/c31b0b62-b296-11e6-9590-f757e1ebb31c.jpg)
![photo_2016-11-24_22-38-14](https://cloud.githubusercontent.com/assets/7975407/20602110/c362d4b0-b296-11e6-9f4a-3fad11ae3204.jpg)
![photo_2016-11-24_22-38-16](https://cloud.githubusercontent.com/assets/7975407/20602108/c344ee8c-b296-11e6-8ace-4681611519c4.jpg)
![photo_2016-11-24_22-38-18](https://cloud.githubusercontent.com/assets/7975407/20602111/c36d7280-b296-11e6-90e0-0ac1c51d8f69.jpg)
![photo_2016-11-24_22-38-19](https://cloud.githubusercontent.com/assets/7975407/20602112/c3759654-b296-11e6-9b7a-3d4b0c087391.jpg)
![photo_2016-11-24_22-38-21](https://cloud.githubusercontent.com/assets/7975407/20602113/c3982b38-b296-11e6-8bd5-f23bc7350f5d.jpg)

太傻逼了 我懒得骂下去了

所有节点IP
[Forwarded from Mashiro Shina]
222.186.151.193
61.160.215.135
61.160.215.160
139.162.81.42
112.74.168.142
202.168.155.152

[Forwarded from Tiny]
商丘工学院...百度贴吧

[Forwarded from Tiny]
我的电话15518630050 扣扣1130426694 谢谢大家！没错，还是这个

[Forwarded from akw kda]
uzmpo.cn 的whois信息
域名: uzmpo.cn
ROID: 20160713s10001s84453434-cn
域名状态: ok
注册者ID: en16713113575
注册者: 曹孝峰
注册者联系人邮件: caoxiaofeng1855@163.com
所属注册服务机构: 郑州世纪创联电子科技开发有限公司
域名服务器: ns1.cloudcdns.com
域名服务器: ns2.cloudcdns.com
注册时间: 2016-07-13 11:12:28
到期时间: 2017-07-13 11:12:28
DNSSEC: unsigned

高中：商丘第二高中
大学：商丘工学院


![photo_2016-11-24_22-40-31](https://cloud.githubusercontent.com/assets/7975407/20602365/ea09318a-b297-11e6-856d-30c654a962ad.jpg)
![photo_2016-11-24_22-40-33](https://cloud.githubusercontent.com/assets/7975407/20602364/ea093798-b297-11e6-8a34-3d96b6fb0370.jpg)
![photo_2016-11-24_22-40-35](https://cloud.githubusercontent.com/assets/7975407/20602367/ea2f2156-b297-11e6-9c8c-9120e49a7b81.jpg)
![photo_2016-11-24_22-40-36](https://cloud.githubusercontent.com/assets/7975407/20602366/ea09eb52-b297-11e6-974d-81f47b3ecf40.jpg)
![photo_2016-11-24_22-40-54](https://cloud.githubusercontent.com/assets/7975407/20602363/ea090836-b297-11e6-862d-45a14841686c.jpg)
![photo_2016-11-24_22-40-56](https://cloud.githubusercontent.com/assets/7975407/20602362/ea0883a2-b297-11e6-9d76-e984f6cc3edd.jpg)
![photo_2016-11-24_22-40-57](https://cloud.githubusercontent.com/assets/7975407/20602369/ea302ff6-b297-11e6-9e80-3837110f3f80.jpg)
![photo_2016-11-24_22-40-58](https://cloud.githubusercontent.com/assets/7975407/20602368/ea300abc-b297-11e6-8f66-548271976803.jpg)

**Comment by glzjin** [comment]
2.某个改了SSR Android客户端，改成免流客户端，还说是自己独立开发的

![img_20161124_230641](https://cloud.githubusercontent.com/assets/7975407/20603099/9555afbe-b225-11e6-9190-768c20319a87.jpg)

**Comment by glzjin** [comment]
3.https://sakura.ypaper.cn/

staff页面改成他自己站点的链接了

![2016-11-25 19-05-47](https://cloud.githubusercontent.com/assets/7975407/20623371/386f366c-b342-11e6-9137-c728c378559e.png)

**Comment by glzjin** [comment]
4.https://nowall.cc/tos

去掉了 staff 链接。


![qq 20161125192436](https://cloud.githubusercontent.com/assets/7975407/20623976/2cd8f2d6-b345-11e6-9bd6-98e73f563c8a.png)

**Comment by glzjin** [comment]
5.http://www.fuli6.cc/

去掉了 staff 链接。

![qq 20161126214310](https://cloud.githubusercontent.com/assets/7975407/20640720/5d442242-b421-11e6-90f9-992a6c1e2136.png)

**Comment by glzjin** [comment]
6.https://www.kansusu.com/code

我操你妈这玩意 staff 页面面目全非了。

![qq 20161126214436](https://cloud.githubusercontent.com/assets/7975407/20640725/9e498c3c-b421-11e6-8297-59d3cadaad82.png)

**Comment by glzjin** [comment]
7.https://ss.6doors.org/

去除了 staff 链接。

![qq 20161126214557](https://cloud.githubusercontent.com/assets/7975407/20640728/bbd4bfec-b421-11e6-9c99-1bc1330286ea.png)

**Comment by glzjin** [comment]
7.https://client.huixing.net/

此站点去掉了脚部 staff 链接。


![qq 20161215073353](https://cloud.githubusercontent.com/assets/7975407/21205821/454a24b2-c299-11e6-903b-ad76265e8be0.png)

**Comment by glzjin** [comment]
8.https://www.bpic.ml/staff

这个站点把 staff 页面改得不成样子了。

![qq 20161215074138](https://cloud.githubusercontent.com/assets/7975407/21205962/0a4bb3a2-c29a-11e6-83ee-07de14929100.png)

**Comment by glzjin** [comment]
9.http://www.bpic.ml/

去掉版权了还那么嚣张，既然你那么想被D那我们就成全他好不好？

![photo_2016-12-29_20-18-00](https://cloud.githubusercontent.com/assets/7975407/21543737/16f270d0-ce04-11e6-897d-565bd19ac0bc.jpg)

![qq 20161229201942](https://cloud.githubusercontent.com/assets/7975407/21543750/2ac82456-ce04-11e6-9e80-5abe0ad287ed.png)

![qq 20161229202013](https://cloud.githubusercontent.com/assets/7975407/21543758/3be2d6e6-ce04-11e6-9dd2-410dda89ec86.png)

IP : 45.76.202.201

**Comment by glzjin** [comment]
10.

![screenshot_20170102-165914](https://cloud.githubusercontent.com/assets/7975407/21586640/d4827a0a-d098-11e6-9932-1186b6ba4d3d.png)
![screenshot_20170102-165922](https://cloud.githubusercontent.com/assets/7975407/21586641/d5b2bb92-d098-11e6-9905-98bb7216dee5.png)

你倒是留个真实邮箱呀，我好看看你是哪个站点的站长看看你站点改得如何了。

你首先不尊重我还指望我尊重你？傻孩子，这世界没你想象的那么好。
