### ISSUE TITLE
我是今早从邮件里看到#耻辱柱的

### ISSUE THREAD

**Issue by SuperSuperSuperSuper5** [esdeathlove/ss-panel-v3-mod#458]
态度-是支持glzjin的
每个人都不可能独立一个人开发出一个很6的代码，都有借鉴别人代码的时候，这我是肯定的
如果你就抄了一行代码，那我觉得你挂不挂原作者也无所谓，但是起码的，你抄了人家60%甚至80%的代码
反正我会在开头@author 的时候@原作者的的邮箱也好，网站也好，然后在原作者下面加上另一个@Remix author再加上我的邮箱
还有就是看不起那些装B的，本人也是安全工程师，OD的图一眼就看出来了，不懂这能说明这个代码是它开发的？？？（黑人疑问脸？？？？？）
OD是用来逆向二进制可执行程序的，这GitHub上都是开源的代码，用的着你逆向？？？
然后还装B说自己是西电的，最后域名查出来是个学院的，这啪啪啪打脸？？？
然后就算你在360，这种水平还能在360，我早成阿里巴巴CTO了，360药王哦（反正我不用360），发现了别人抄袭自己代码，然后改成别人是原作者，尤其是自己费尽心思写出来的，我觉得glzjin生气也很正常

**Comment by HanC890** [comment]
从未见过有如此厚颜无耻之人~~
支持

**Comment by HolaJam** [comment]
我来自西安电子科技大学
我保证这是西电和西安被黑的最惨的一次

**Comment by SuperSuperSuperSuper5** [comment]
@HolaJam 我ex在西安我会乱说？哈哈哈，想念那场西安的大雪🤐

**Comment by shiyeshu** [comment]
作为河南人我为他们感到丢人（商丘属河南省）。当年他们学校还去我们高中宣传招生，幸亏填志愿的时候长了脑子，没报。真是一群厚颜无耻的人渣。

**Comment by python12450** [comment]
无耻之尤，建议往死里D

**Comment by Okabe-Kurisu** [comment]
真的很傻逼。。。。

**Comment by tataki** [comment]
国内开源环境真的就是被这种人搅烂的
