### ISSUE TITLE
php /home/wwwroot/ss.panel/xcat checkjob后报错

### ISSUE THREAD

**Issue by tsongneil** [esdeathlove/ss-panel-v3-mod#496]
运行后  提示You have new mail in /var/spool/mail/root

打开root文件后，报错如下

PHP Parse error:  syntax error, unexpected '$rbusers' (T_VARIABLE), expecting function (T_FUNCTION) in /home/wwwroot/ss.panel/app/Command/Job.php on line 806

**Comment by lithromantic** [comment]
php什么版本？

**Comment by A1exLiu** [comment]
> Parse error: A problem with the syntax of your program, such as leaving a semicolon off of the end of a statement or, like the case above, missing the . operator. The interpreter stops running your program when it encounters a parse error.

In simple words this is a syntax error, meaning that there is something in your code stopping it from being parsed correctly and therefore running.

What you should do is check carefully at the lines around where the error is for any simple mistakes.

That error message means that in line x of the file, the PHP interpreter was expecting to see an open parenthesis but instead, it encountered something called T_VARIABLE. That T_VARIABLE thing is called a token. It's the PHP interpreter's way of expressing different fundamental parts of programs. When the interpreter reads in a program, it translates what you've written into a list of tokens. Wherever you put a variable in your program, there is aT_VARIABLE token in the interpreter's list.
从stackoverflow上找到的有关内容，希望能帮上忙
Reference: [Parse error: syntax error, unexpected T_VARIABLE](http://stackoverflow.com/questions/12769982/reference-what-does-this-error-mean-in-php/15539535#15539535)
