### ISSUE TITLE
php -n xcat createAdmin 命令执行后出错，求助。

### ISSUE THREAD

**Issue by andy817** [esdeathlove/ss-panel-v3-mod#540]
![136](https://cloud.githubusercontent.com/assets/10892833/21686752/6496d702-d3a1-11e6-9f89-a73a875811d9.JPG)
![error](https://cloud.githubusercontent.com/assets/10892833/21686754/64b5740a-d3a1-11e6-8f82-20f9fd040a64.JPG)
![kaiguan](https://cloud.githubusercontent.com/assets/10892833/21686755/64c7fca6-d3a1-11e6-9f2a-001861785cf3.JPG)

提示136行语法错误，我并没有开启wecenter，为什么还有这个错误。。。
求指导

**Comment by esdeathlove** [comment]
@andy817 请问您可以发一下完整的配置文件截图吗？我觉得应该是可能是您配置文件多删了一个分号导致的。

**Comment by andy817** [comment]
[config文件截图打包.zip](https://github.com/esdeathlove/ss-panel-v3-mod/files/687678/config.zip)
配置文件截图打包在上，不知道什么问题，请指导

**Comment by andy817** [comment]
我仔细看了，是丢了一个分号，找到了，谢谢
