### ISSUE TITLE
为什么我公告管理不能在删除

### ISSUE THREAD

**Issue by zhangdailin** [esdeathlove/ss-panel-v3-mod#543]
不知道为什么不能修改用户信息，ubuntu 14.04 
php7

**Comment by Fribyter** [comment]
连场景都不描述一下让别人怎么帮你

**Comment by zhangdailin** [comment]
管理面板里面，公告管理里面可以新增一条公告，但是不可以删除或者修改，用户列表也是的，点修改以后会弹出一个空白的页面和知道了，但是并没有修改或者删除

**Comment by Fribyter** [comment]
应该是你mysql这几张表主键出了问题，自己导过数据？

**Comment by zhangdailin** [comment]
对 我导入的原版sspanel的数据 好像报错的

**Comment by Fribyter** [comment]
报错肯定不对，先回去把导数据库出错的问题解决了吧。数据库报出来的错网上很好查到

**Comment by zhangdailin** [comment]
我找到原因了 不是数据库的问题 用了cdn 把cdn给撤了就正常了 不知道为什么 百度云加速
