### ISSUE TITLE
能不能多个后端连接一个前端，可以的话怎么做？

### ISSUE THREAD

**Issue by CxiaoyuN** [esdeathlove/ss-panel-v3-mod#544]
是前端数据库打开远程打开远程连接吗？整个还是只是sspanel?

**Comment by Fribyter** [comment]
装了魔改后端把数据库指向你数据库服务器，mysql要开启允许远程连接，node id要对应

**Comment by CxiaoyuN** [comment]
怎么指向？就是1.MYSQL_HOST = ‘localhost’ //前端mysql域名/IP
2.MYSQL_PORT = 3306 //mysql端口
3.MYSQL_USER = ‘ss’ //mysql用户名
4.MYSQL_PASS = ‘ss’ //mysql密码
5.MYSQL_DB = ‘shadowsocks’ //数据库名，这个数据库是不动还是，改成sspanel的库？还是在前端数据库建一个shadowsocks？

**Comment by Fribyter** [comment]
localhost替换成mysql的那台服务器的IP地址

**Comment by CxiaoyuN** [comment]
其他的呢？
