### ISSUE TITLE
发送邮件的方式

### ISSUE THREAD

**Issue by hly9469** [esdeathlove/ss-panel-v3-mod#546]
smtp不可用了，mailgun倒是可用，但是不能用qq邮箱注册，会屏蔽来自mailgun服务器的邮件，而mailgun独立ip又太贵，会不会考虑加入sendcloud之类的？

**Comment by CxiaoyuN** [comment]
smtp可以用

**Comment by hly9469** [comment]
怎么配置的？我那几个选项搞不清楚

**Comment by CxiaoyuN** [comment]
$System_Config['smtp_host'] = 'smtp.qq.com';
$System_Config['smtp_username'] = '888888888@qq.com';
$System_Config['smtp_port'] = '465';
$System_Config['smtp_name'] = '88888888@qq.com';
$System_Config['smtp_sender'] = '88888888@qq.com';
$System_Config['smtp_passsword'] = 'vfwtiglqdaqxeabf';这是生成的授权码，去邮箱设置里生成
$System_Config['smtp_ssl'] = 'true';开

**Comment by hly9469** [comment]
Ok、thanks、我试试QQ、163邮箱死活不行

**Comment by jinshijie** [comment]
程序做的有问题，看F12就知道了

**Comment by esdeathlove** [comment]
duplicated https://github.com/esdeathlove/ss-panel-v3-mod/issues/542
