### ISSUE TITLE
php -n xcat createAdmin出错，求助，提示如下

### ISSUE THREAD

**Issue by andy817** [esdeathlove/ss-panel-v3-mod#547]
确认来确认创建管理员账户..... Y
start create admin account
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)' in /home/wwwroot/www.netbridge.ml/vendor/illuminate/database/Connectors/Connector.php:55
Stack trace:
#0 /home/wwwroot/www.netbridge.ml/vendor/illuminate/database/Connectors/Connector.php(55): PDO->__construct('mysql:host=loca...', '', '', Array)
#1 /home/wwwroot/www.netbridge.ml/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 /home/wwwroot/www.netbridge.ml/vendor/illuminate/database/Connectors/ConnectionFactory.php(61): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 /home/wwwroot/www.netbridge.ml/vendor/illuminate/database/Connection.php(908): call_user_func(Object(Closure))
#5 /home/wwwroot/www.netbridge.ml/vendor/illuminate/database/Co in /home/wwwroot/www.netbridge.ml/vendor/illuminate/database/Connectors/Connector.php on line 55

我是之前网站做错了，删掉网站目录，删掉vhost，然后全部重来，，出现这个错误。求助。是数据库无法连接吗？数据库是localhost   ALL PRIVILEGES，，，，求助。。。

**Comment by andy817** [comment]
我直接在数据库插入用户数可以吗？

**Comment by andy817** [comment]
已解决，添麻烦了。。。

**Comment by myfingerhurt** [comment]
Most possibility is you have wrong username or database name. 
Beware that, the default data base name setting is different from the name you have imported from db.sql.

db_driver = 'mysql'
db_host = 'localhost'
db_port = '3306'
db_database = 'sspanel'  --- different to db.sql
db_username = 'sspanel' --- different
db_password = 'sspanel' --- different
db_charset = 'utf8'
db_collation = 'utf8_general_ci'
db_prefix = ''

**Comment by BlingRabbit** [comment]
>start create admin account
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'expire_in' in 'field list'' in /home/wwwroot/Rabbit/vendor/illuminate/database/Connection.php:457
Stack trace:
#0 /home/wwwroot/Rabbit/vendor/illuminate/database/Connection.php(457): PDO->prepare('insert into `us...')
#1 /home/wwwroot/Rabbit/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `us...', Array)
#2 /home/wwwroot/Rabbit/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#3 /home/wwwroot/Rabbit/vendor/illuminate/database/Connection.php(458): Illuminate\Database\Connection->run('insert into `us...', Array, Object(Closure))
#4 /home/wwwroot/Rabbit/vendor/illuminate/database/Connection.php(414): Illuminate\Database\Connection->statement('insert into `us...', Array)
#5 /home/wwwroot/Rabbit/vendor in /home/wwwroot/Rabbit/vendor/illuminate/database/Connection.php on line 729

求助 基本上同样的问题 怎么解决？
已安装radius
