### ISSUE TITLE
怎么没有安装说明呢

### ISSUE THREAD

**Issue by jinshijie** [esdeathlove/ss-panel-v3-mod#548]
恕我眼拙！似乎没有WIKI

**Comment by CxiaoyuN** [comment]
有https://github.com/esdeathlove/ss-panel-v3-mod/wiki

**Comment by echoowall** [comment]
你知道吗，现在赵老师要被你气炸了。现在跟着我做，先Crtl + F，然后输入Wiki，你就看到了

**Comment by jinshijie** [comment]
呵呵，还真学会了如何搜索wiki了，谢谢哈，小可这厢礼过去了
