### ISSUE TITLE
说来奇怪加上这两句，网站就打不开了

### ISSUE THREAD

**Issue by jinshijie** [esdeathlove/ss-panel-v3-mod#550]
当然我加入到了/usr/local/nginx/conf/vhost/ss.panel.conf中，
root /www/wwwroot/ssr/public;
      location / {
                        try_files $uri $uri/ /index.php$is_args$args;
                }
显示HTTP ERROR 500
如果去掉就正常
但按装ss-panel别的版按这种方法就可以
我一狠心，把文件夹设为了777也不行

**Comment by ziluopao** [comment]
呵呵，多了个逗号，解决了
