### ISSUE TITLE
SSpanel安装完成后能够发送邮件，但打开网页白屏

### ISSUE THREAD

**Issue by JuiceCC** [esdeathlove/ss-panel-v3-mod#551]
按照WIKI上流程来的。。然而并不知道哪里错了。安装完成后打开就是白屏。求解决

**Comment by JuiceCC** [comment]
开了Debug模式后的提示：

RuntimeException thrown with message "Unexpected data in output buffer. Maybe you have characters before an opening <?php tag?"

Stacktrace:
#4 RuntimeException in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/App.php:552
#3 Slim\App:finalize in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/App.php:344
#2 Slim\App:process in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/App.php:298
#1 Slim\App:run in /home/wwwroot/ss.panel/config/routes.php:294
#0 require in /home/wwwroot/ss.panel/public/index.php:11

**Comment by esdeathlove** [comment]
请检查你在配置文件 php标签符 前后有没有加一些奇怪的东西，特别注意要用 UTF-8 编码保存。

**Comment by JuiceCC** [comment]
@esdeathlove 首先感谢作者给我的回复，我想问下您指的配置文件是.config.php那个么

**Comment by esdeathlove** [comment]
@JuiceCC 我不是作者，只是我来接手了。对的，检查你的输入。

**Comment by JuiceCC** [comment]
@esdeathlove 嗯。感谢维护人员给我回复。已经可以进去了。我是用WinSCP进我的VPS下载.config.php文件进行更改的。在Notepad++里的格式菜单里把文件转化成了UTF-8的模式。没选择UTF-8无Bom编码格式。转换了一下就可以了。谢谢dalao，请问大佬可以把您的联系方式给我么。我有问题可以找您联系

**Comment by esdeathlove** [comment]
@JuiceCC 这里，或者 telegram。

**Comment by JuiceCC** [comment]
那请问您的telegram账号是？

**Comment by JuiceCC** [comment]
那个请问下，首页下面提示密码的那几个字看的有点丑，我想让密码高亮，请问在哪弄？
