### ISSUE TITLE
好象这里有一个bug,即注册时发送邮箱验证码失败

### ISSUE THREAD

**Issue by jinshijie** [esdeathlove/ss-panel-v3-mod#552]
试了几个知名的邮箱也不管用，开始还以为是否是被屏蔽了呢,我看了一下 config配置，好象里面也没有这方面的设置
这是f12
<img src="https://raw.githubusercontent.com/jinshijie/tupian/master/mod%E5%89%8D%E7%AB%AF%E5%8F%91BUG.png"/>

**Comment by jinshijie** [comment]
感觉前端js做的有问题，看f12就知道了

**Comment by esdeathlove** [comment]
@jinshijie 那为什么别人没遇到这个问题？

**Comment by esdeathlove** [comment]
@jinshijie glzjin:
每日 tips 第四期：

如何正确地排查与反馈问题。

注意，此处的问题指的是功能上，技术上的问题，你运营上的问题别来找我(不过其实就算是符合条件的问题我都不一定有时间回答)。

所以，接下来讲一下如何正确地排查和提出问题。

关于排查问题：

当你遇到一个问题时，请首先确认你的操作是否正确符合界面上的提示，以及是否正确参照说明来进行搭建，升级等操作。如果没有，请你自己仔细检查哪一步有问题。

当你确认完自己的操作无误之后，接下来就该抓取错误信息了。后端的错误信息好说，就是终端输出的日志信息，如果你是 按照安装说明里的 supervisord 设置而后运行的，那么日志就在 /var/log/mu.log (/var/log 下没有就到 /tmp 下看看，有 mu 打头的 log 文件没)里，看这个文件，不要觉得自己看不懂，里面的英文都很基础的，看完你就会发现哪里出毛病了。如果你看完确定自己解决不了，那么就发个 issue 到后端那个项目上，详细描述现象，并附上日志，会有人来看看的。

而对于前端抓取错误信息，你要做的就是首先将 debug 开关打开，这个开关在 config/.config.php 就是你安装时候编辑的那个设置文件里，看到

$System_Config['debug'] = 'false'; 

将其改为

$System_Config['debug'] = 'true';

就打开了 debug 开关了。

再回到你失败的操作上，例如你打开某个页面报 500，那么就重新打开那个页面，你就会发现它并没有跳转到 500 默认页了，会出现详细的错误信息。仔细看，你会发现很多东西的。甚至于你看完就知道哪里错了。当然，如果你实在不明白，就发个 issue 到前端那，附上详细的现象描述和 debug 界面输出的错误信息，有人会去看的。

又比如那你遇到的是执行某个请求时无返回(就一个白框弹出来之类的)，这时请保持 debug 开关打开，用浏览器抓这个请求的返回信息。具体抓取步骤请看下面的链接(Firefox 的，Chrome 的话自己上网搜)。

https://developer.mozilla.org/zh-CN/docs/Tools/Network_Monitor

然后看返回信息，一般你也能知道你怎么错了，会写出来的。如果还是不明白，就发 issue 吧，附上详细的现象描述和这个返回信息。



特别是发 issue 时，不要就丟个“xxx不行，求解”之类的话，你这样根本解决不了问题。你调试和打字嫌累，别人回答你更加嫌累呢。说话就说详细，这样才有助于解决问题。

特别是别说自己是小白，即便你真的是小白。你弱，你并没有理。

就这样，晚安。

**Comment by 693098385** [comment]
都一年的产物了。。

**Comment by jinshijie** [comment]
别人不说这个问题不能推理说没有，也可能是有也可能是没有，也可能，好多情况，你是做程序的，这种逻辑思维应该有吧

**Comment by esdeathlove** [comment]
@jinshijie 那既然如此就请你拿出更加具体的证据来证明有问题，证明不是你的设置问题而是程序本身的问题。都是标准化的东西，请先检查自己的设置。

**Comment by jinshijie** [comment]
见一楼不就行了，我那不是发个图吗

**Comment by esdeathlove** [comment]
@jinshijie 请按照我给的说明来抓取错误。这个只是说明 PHP 出错了，发送了错误的数据给 js。

**Comment by jinshijie** [comment]
呵呵，你在关键的地方设置了一下，不错哈

**Comment by jinshijie** [comment]
我总感觉你对提问的人心里有某种仇视感！这样对你今后的程序生涯是没有好处的

**Comment by 693098385** [comment]
放寒假作业太少的节奏

**Comment by esdeathlove** [comment]
@jinshijie 很真诚地建议你读一下这篇东西

**Comment by echoowall** [comment]
小学生放假了系列

**Comment by jinshijie** [comment]
给你提一个问题，却激起你心中无限的那个啥，是俺 没有想到的

**Comment by esdeathlove** [comment]
@jinshijie 请想想你自己提问的方式。你一上来就说程序有问题，你为什么不想想自己的操作呢。

**Comment by jinshijie** [comment]
至于读啥，其实不用你告诉，不能因为我要解决这个问题，前提是我要变一个哲学家或数学家还有文学家吧！其实吧，也就是吧，要端正心态！

**Comment by 693098385** [comment]
都说了叫你debug。。。

**Comment by jinshijie** [comment]
是啊，我不知道你是喜欢咸的，还是辣的，或甜的，当然了，你感觉是苦的，所以我说的没错，要端正心态，你！

**Comment by esdeathlove** [comment]
@jinshijie 不能因为你是新手，而可以肆无忌惮，无所顾忌，谢谢。

**Comment by jinshijie** [comment]
一个问题引起了一个哲学问题，是我没有想到也不愿意看到的

**Comment by esdeathlove** [comment]
@jinshijie 是你自己想往那个方面引，我就告诉你这样提问并不能有效地解决问题。

**Comment by jinshijie** [comment]
一个程序员因为一个问题变的如此狂燥，这更是我没有想到，也不原意看到的！心态很重要的，对你，如果你的心态好，你的程序会融入这种心态，程序也是有灵魂的！

**Comment by esdeathlove** [comment]
@jinshijie 好的，那请你卸载吧，既然你不能接受这些规则，不能好好说话的话。

**Comment by shmily0827** [comment]
@jinshijie 程序有没有问题我不清楚，至少我用起来很顺手，不过你没有脑子，这个倒是肯定的
