### ISSUE TITLE
后端配置是问题，求教

### ISSUE THREAD

**Issue by andy817** [esdeathlove/ss-panel-v3-mod#553]
![nodeid](https://cloud.githubusercontent.com/assets/10892833/21747024/3b7ed118-d594-11e6-9168-a09b80cec8f5.JPG)
![userapiconfig](https://cloud.githubusercontent.com/assets/10892833/21747025/3b818a2a-d594-11e6-99db-f68b3fd1f2dd.JPG)
![user-config](https://cloud.githubusercontent.com/assets/10892833/21747026/3b879c62-d594-11e6-84e3-59bbf6631eca.JPG)
![run](https://cloud.githubusercontent.com/assets/10892833/21747031/7f9b4458-d594-11e6-8e70-0581e3c2eb20.JPG)

后端与网站不在一个ip上，，数据库用户是%，，查看也在运行啊，求助。

**Comment by andy817** [comment]
后端使用的是mod版推荐的版本

**Comment by esdeathlove** [comment]
@andy817 glzjin:
每日 tips 第四期：

如何正确地排查与反馈问题。

注意，此处的问题指的是功能上，技术上的问题，你运营上的问题别来找我(不过其实就算是符合条件的问题我都不一定有时间回答)。

所以，接下来讲一下如何正确地排查和提出问题。

关于排查问题：

当你遇到一个问题时，请首先确认你的操作是否正确符合界面上的提示，以及是否正确参照说明来进行搭建，升级等操作。如果没有，请你自己仔细检查哪一步有问题。

当你确认完自己的操作无误之后，接下来就该抓取错误信息了。后端的错误信息好说，就是终端输出的日志信息，如果你是 按照安装说明里的 supervisord 设置而后运行的，那么日志就在 /var/log/mu.log (/var/log 下没有就到 /tmp 下看看，有 mu 打头的 log 文件没)里，看这个文件，不要觉得自己看不懂，里面的英文都很基础的，看完你就会发现哪里出毛病了。如果你看完确定自己解决不了，那么就发个 issue 到后端那个项目上，详细描述现象，并附上日志，会有人来看看的。

而对于前端抓取错误信息，你要做的就是首先将 debug 开关打开，这个开关在 config/.config.php 就是你安装时候编辑的那个设置文件里，看到

$System_Config['debug'] = 'false'; 

将其改为

$System_Config['debug'] = 'true';

就打开了 debug 开关了。

再回到你失败的操作上，例如你打开某个页面报 500，那么就重新打开那个页面，你就会发现它并没有跳转到 500 默认页了，会出现详细的错误信息。仔细看，你会发现很多东西的。甚至于你看完就知道哪里错了。当然，如果你实在不明白，就发个 issue 到前端那，附上详细的现象描述和 debug 界面输出的错误信息，有人会去看的。

又比如那你遇到的是执行某个请求时无返回(就一个白框弹出来之类的)，这时请保持 debug 开关打开，用浏览器抓这个请求的返回信息。具体抓取步骤请看下面的链接(Firefox 的，Chrome 的话自己上网搜)。

https://developer.mozilla.org/zh-CN/docs/Tools/Network_Monitor

然后看返回信息，一般你也能知道你怎么错了，会写出来的。如果还是不明白，就发 issue 吧，附上详细的现象描述和这个返回信息。



特别是发 issue 时，不要就丟个“xxx不行，求解”之类的话，你这样根本解决不了问题。你调试和打字嫌累，别人回答你更加嫌累呢。说话就说详细，这样才有助于解决问题。

特别是别说自己是小白，即便你真的是小白。你弱，你并没有理。

就这样，晚安。

**Comment by esdeathlove** [comment]
所以，请发后端日志出来。

**Comment by CxiaoyuN** [comment]
节点是黄色感叹号吗？

**Comment by andy817** [comment]
@esdeathlove 我看到通知后，自己重新做了几次，但是还是没有解决。而且在tmp和log文件夹下，均没有找到l相关log。
网站正常，可以打开。后端都是按照安装说明来的。
现在shadowsocks安装目录是/root/shadowsocks
![temp](https://cloud.githubusercontent.com/assets/10892833/21791212/4153a3b4-d71c-11e6-868c-12d0c5fe8b8d.jpg)

![log](https://cloud.githubusercontent.com/assets/10892833/21791176/131025c2-d71c-11e6-89b9-f3ed91c2e177.jpg)

**Comment by feileb** [comment]
shadowsocks目录下面./logrun.sh，然后./tail.sh看看日志有什么输出

**Comment by andy817** [comment]
输出如图。
![tail](https://cloud.githubusercontent.com/assets/10892833/21792834/88f7bb78-d727-11e6-8a40-5abfa2c6104a.jpg)

进程多了
![grep](https://cloud.githubusercontent.com/assets/10892833/21792827/78301fec-d727-11e6-88bb-e4eebd880bd5.jpg)
我kill  5050之后 reboot vps，还是没有反应。
我应该怎么去排除问题？

**Comment by feileb** [comment]
现在的log还是显示address already in use?
你这看起来数据库啥的是好的
日志不在/tmp和/log，是shadowsocks/ssserver.log
问题是连不上？iptables -L看看

**Comment by andy817** [comment]
![1](https://cloud.githubusercontent.com/assets/10892833/21797106/181ac802-d748-11e6-995c-8042de0ea7a2.jpg)
![2](https://cloud.githubusercontent.com/assets/10892833/21797107/184ef276-d748-11e6-9b25-9bbbacf5d824.jpg)
![3](https://cloud.githubusercontent.com/assets/10892833/21797171/72f13b26-d748-11e6-9d9f-c6192c00ce67.jpg)
![4](https://cloud.githubusercontent.com/assets/10892833/21797172/72fd9736-d748-11e6-80e8-964ea9d8eb31.jpg)
![5](https://cloud.githubusercontent.com/assets/10892833/21797108/18aa819a-d748-11e6-86d8-9861d522aa16.jpg)

我截取了一下，我找不出原因了

**Comment by andy817** [comment]
[ssserver.txt](https://github.com/esdeathlove/ss-panel-v3-mod/files/695494/ssserver.txt)


log         .log无法上传，改为txt了

**Comment by feileb** [comment]
你vps上防火墙应该是好的，你是哪家的，是不是在面板里面要打开防火墙，你上网搜下看看
然后，测试下
1,netstat -an | grep 2169 你开了服务的端口看看
2，测试客户端能不能连上
./stop.sh  先停止
./logrun.sh  开始服务
./tail.sh 开着，然后用客户端连ss，看看有没有输出，如果没有新增加的输出说明客户端连不到你的服务器。

**Comment by andy817** [comment]
![test](https://cloud.githubusercontent.com/assets/10892833/21809626/843bbe2a-d783-11e6-9803-ab60aef073d2.JPG)
如图所示，，，似乎没有问题，但是就是客户端没有网速，我是否有配置错误？我之前搭建过另外版本的sspanel，，不过那个前后端在一个vps上，这次，前后端不在一个vps上，我觉得问题可能出在这里，两台vps操作有哪里是非常容易出错的地方吗？我去排查一下。
![ss](https://cloud.githubusercontent.com/assets/10892833/21809826/4ca57bd0-d784-11e6-9d0f-40b3fbe5d496.JPG)

**Comment by andy817** [comment]
我感觉是这个vps没有连接到之前vps的数据库，，有没有方法可以测试，是否连接到数据库？

**Comment by feileb** [comment]
./tail.sh在你客户端连接的时候没有显示类似下面的打印吗
2016-12-02 23:20:29 ERROR    tcprelay.py:847 [Errno 104] Connection reset by peer
2016-12-02 23:20:29 ERROR    tcprelay.py:849 when connect to google.com:80
2016-12-02 23:20:36 INFO     tcprelay.py:1020 port 29821 connections up to 25
2016-12-02 23:20:51 INFO     tcprelay.py:1023 port 29821 connections down to 0
2016-12-02 23:21:18 ERROR    tcprelay.py:847 [Errno 104] Connection reset by peer
2016-12-02 23:21:18 ERROR    tcprelay.py:849 when connect to google.cn:80
2016-12-02 23:21:36 INFO     tcprelay.py:1020 port 12634 connections up to 25
2016-12-02 23:23:33 INFO     tcprelay.py:1023 port 12634 connections down to 0
如果没有就是客户端连不到服务端

数据库应该是连上了，要不不会出现
2017-01-09 22:25:38 INFO     server_pool.py:165 starting server at 0.0.0.0:1025
shadowsocks/userapiconfig.py改了API_INTERFACE，SERVER_PUB_ADDR没有

**Comment by andy817** [comment]
![userapiconfig py](https://cloud.githubusercontent.com/assets/10892833/21839496/05df01a0-d813-11e6-9194-7906b93f6962.jpg)
![user-config json](https://cloud.githubusercontent.com/assets/10892833/21839497/068dcf82-d813-11e6-9bcb-ea6da86b538a.jpg)
![Uploading 第二次.jpg…]()
![default](https://cloud.githubusercontent.com/assets/10892833/21839502/0ca3ea14-d813-11e6-8a2f-c4acc33f4da7.jpg)
![Uploading 第一次.jpg…]()
![log](https://cloud.githubusercontent.com/assets/10892833/21839504/0d8a8d2a-d813-11e6-8aae-03d4d714408b.jpg)
客户端日志提示错误。。。而且有一次测试出现keyerror

**Comment by andy817** [comment]
![default](https://cloud.githubusercontent.com/assets/10892833/21839589/7d0f1dd2-d813-11e6-9a18-47e4dbcbf4b7.jpg)
![default](https://cloud.githubusercontent.com/assets/10892833/21839581/764ff3cc-d813-11e6-9847-5689238dedbf.jpg)
补图，三次 ， 有一次出错

**Comment by andy817** [comment]
出现keyerror是第一次

**Comment by feileb** [comment]
应该是客户端没连上，如果连上了keyerror的话会打印日志的，还是找下防火墙啥的设置吧

**Comment by andy817** [comment]
我service   iptables stop   关闭了防火墙 就可以连接了，防火墙可以永久关闭吗？或者这是什么原因？

**Comment by G-g-beringei** [comment]
永久关闭防火墙chkconfig iptables off，重启生效
