### ISSUE TITLE
后端报错TCP协义错误，错误的加密方式或密码！

### ISSUE THREAD

**Issue by quanqingzhong** [esdeathlove/ss-panel-v3-mod#555]
1、新装的后端，装完后启动都会报这个错误。但是很奇怪，虽然报错但是又能正常连上外网，使用上没有任何问题.之前装的后端也会出这个错误。但是能正常使用，也没去多管它。
2、我检查了前端节点和config/.config.php与MYSQL里面的加密方式全都是一致的。协义也一致，然后就是密码，密码不对那就肯定连不上的，所以我就搞不明白了。
“
![qq 20170108151533](https://cloud.githubusercontent.com/assets/24617113/21748060/5f9b24fe-d5b5-11e6-88f3-d17dd27fe460.png)

**Comment by esdeathlove** [comment]
@quanqingzhong 你用户侧 节点列表里这个节点的详细信息 还有 管理员侧 这个节点的编辑信息界面

**Comment by quanqingzhong** [comment]
![1](https://cloud.githubusercontent.com/assets/24617113/21748222/c72519b8-d5ba-11e6-9617-3378c1fad1d5.png)
![2](https://cloud.githubusercontent.com/assets/24617113/21748223/c72be342-d5ba-11e6-8a37-82b0bea2a404.png)
![3](https://cloud.githubusercontent.com/assets/24617113/21748224/c7323080-d5ba-11e6-8632-3a93d2768fa8.png)
![4](https://cloud.githubusercontent.com/assets/24617113/21748225/c76c52ce-d5ba-11e6-94ac-860e53af93b8.png)

**Comment by esdeathlove** [comment]
@quanqingzhong 请开启自定义加密还有自定义混淆后再重新导入节点进行连接。

**Comment by quanqingzhong** [comment]
这回复速度，赞！

**Comment by quanqingzhong** [comment]
赵老师，你好，我的问题还没有解决。我之所以没有回复，是因为之前的节点过二天后又没有这个问题了。所以前天没法照你的方法验证，刚刚我增加新后端，照你所说的开启自定义加密与协议并重新导入节点，但是问题还是一样。后端我也重启过，也是一样报错。我把现在的后端日志传上来给你帮我看看，谢谢！
![2](https://cloud.githubusercontent.com/assets/24617113/21771080/f8c5c484-d6c0-11e6-9a14-c464e2345f37.png)

**Comment by esdeathlove** [comment]
自己检查。
