### ISSUE TITLE
如果右上角图标无法显示

### ISSUE THREAD

**Issue by moqiaoduo** [esdeathlove/ss-panel-v3-mod#558]
主要是Gravatar源无法访问（该程序默认用了原来赵大的源，现在好像https失效了），请更换源，官方源也是可以用的，上https的就好，比如https://secure.gravatar.com/avatar/。
修改方法：./app/Models中的User.php，搜索getGravatarAttribute，将return后面的网址更换即可。

**Comment by esdeathlove** [comment]
@moqiaoduo 并没有失效，这个 CDN 他说在又拍云上。请自行检查网络问题。

**Comment by moqiaoduo** [comment]
是可以访问，但是https证书过期了貌似，我也只是提供修改方法，没问题的话就不改了

**Comment by esdeathlove** [comment]
@moqiaoduo 并没有过期，谢谢。

**Comment by moqiaoduo** [comment]
那就不清楚了，我这里显示的证书错误

**Comment by esdeathlove** [comment]
@moqiaoduo 请检查你是否遭受了中间人攻击。

**Comment by moqiaoduo** [comment]
有这个可能。

**Comment by esdeathlove** [comment]
已经做了相应的优化。
