### ISSUE TITLE
今日流量不重置，管理员ss帐号失效

### ISSUE THREAD

**Issue by lithromantic** [esdeathlove/ss-panel-v3-mod#559]
之前一直正常，这两天貌似是配置telegram bot 后（php setTelegram 返回值1  貌似因为telegram api升级，原借口失效），开始出现异常，用户每日流量不重置，备份邮件也停止发送，并且管理员帐号所有节点连接不上， 已经不能访问，普通用户则是正常使用，看了一下源码，由于本人能力不够，所以前来寻找解决方法。

**Comment by esdeathlove** [comment]
请详细描述。

**Comment by lithromantic** [comment]
开debug 没有任何提示，查了一下crontab记录 也一切正常，但是自从前段时间开始，就收不到每日备份邮件了，面板每个用户的今日流量也没有重置，另外管理员的1025端口在新添加的节点上才能用，以前的节点连不上
