### ISSUE TITLE
很多时候加载不出来，登陆无法应

### ISSUE THREAD

**Issue by alstarking** [esdeathlove/ss-panel-v3-mod#560]
只要是下面加载出错，就无法登陆，无法注册之类的。。。刷新也不中。。换浏览器也不行，感觉不是网络的问题。。就得碰运气没准什么时候就好使。。

![error](https://cloud.githubusercontent.com/assets/24618335/21952968/5b0a6110-da66-11e6-8de8-2b2c16e9fd81.png)

**Comment by esdeathlove** [comment]
已经做了相应的优化。
