### ISSUE TITLE
Mac端无法上网问题

### ISSUE THREAD

**Issue by nelson0707** [esdeathlove/ss-panel-v3-mod#561]
在Win客户端、Android客户端下均可以正常上网，在Mac客户端下可以ping通但是无法打开网页是什么情况？

**Comment by qinyuhang** [comment]
有详细log吗？检查过参数填写是否正确吗？

**Comment by nelson0707** [comment]
![d83d5ec0-624b-c146-9677-2a6d887248ba](https://cloud.githubusercontent.com/assets/18087236/21953386/21573c22-da70-11e6-8dd4-0abb49ddb41e.jpeg)
端口和密码都没有问题

**Comment by xushao1990** [comment]
我已开始也这样，我调整了一下配置就OK了。
你按照下图的设置弄一下。速度很快！
<img width="529" alt="2017-01-16 10 38 44" src="https://cloud.githubusercontent.com/assets/5080109/21969287/197209e2-dbd8-11e6-9099-547e01e2f264.png">
<img width="564" alt="2017-01-16 10 38 53" src="https://cloud.githubusercontent.com/assets/5080109/21969290/1b8a4aa0-dbd8-11e6-9a1a-067180528009.png">
另外，我刚注册的账号，但是发现公告的优惠码刚过期，能不能发给我一个可用的？^_^

**Comment by nelson0707** [comment]
@xushao1990还是不行呢
