### ISSUE TITLE
单端口多用户提示md5 is mismatch，已自行检查，前后配置相同仍无效

### ISSUE THREAD

**Issue by lenovoy450** [esdeathlove/ss-panel-v3-mod#562]
已经检查和换端口实验多次，
其中config/.config.php设置
$System_Config['mu_suffix']='zhaoj.in';
$System_Config['mu_regex']='%5m%id.%suffix';

userapiconfig.py中设置
MU_SUFFIX = ‘zhaoj.in’
MU_REGEX = ‘%5m%id.%suffix’

日志错误提示为
2017-01-14 16:28:47 ERROR    tcprelay.py:960 The host:9aca93.zhaoj.in md5 is mismatch,so The connection has been rejected, when connect from ::ffff:117.61.130.206:2113 via port 443
2017-01-14 16:28:47 WARNING  tcprelay.py:495 Protocol ERROR, TCP ogn data 16030101990100019503035879e13fbc70a26305d4a272d1ca88193aaa9549343d8f374eff112d58c4915620922c9e7bb64f76e85295

感谢作者和好心人。

**Comment by esdeathlove** [comment]
@lenovoy450 请检查你是否正确地导入了面板上最新的节点配置否

**Comment by lenovoy450** [comment]
感谢作者耐心解答。
经进一步测试，最初创建的管理员普通端口和多用户端口正常。
其他用户无论是普通端口还是多用户端口均不能连接。在取消单端口的有关设置以后，普通用户普通端口恢复正常。
请问这种情况应如何进行排错？ 
可提供网站管理员帐号和SSH权限，烦请作者看看是不是有其他错误引起。

**Comment by esdeathlove** [comment]
@lenovoy450 检查节点以及用户的等级和群组是否匹配。

**Comment by lenovoy450** [comment]
@esdeathlove 所有节点分组都是0.

**Comment by esdeathlove** [comment]
@lenovoy450 你这个节点开了只开单端口多用户？还有等级是？

**Comment by lenovoy450** [comment]
@esdeathlove 感谢，这个节点有其他端口在用，并没有勾选“只开启单端口多用户”，节点等级是0。我现在再重新添加一次。

**Comment by lenovoy450** [comment]
将单端口多用户的承载用户设置为管理员，还是不能连接。 最初的管理员帐户正常。

**Comment by esdeathlove** [comment]
@lenovoy450 设置成那个并不正确，你照着说明里进行添加即可。

**Comment by lenovoy450** [comment]
感谢。普通用户正常使用。
