### ISSUE TITLE
建议：有效期重置相关。

### ISSUE THREAD

**Issue by andy817** [esdeathlove/ss-panel-v3-mod#564]
一方面，购买时，流量会被重置，但是等级有效期不会被重置，重复购买就会叠加有效期。（也不算大问题）

另外，购买时，账户有效期不会跟等级有效期一样，在目前的时间上，加相应天数。

这样就只能通过等级来重置流量。

仅供参考，有错之处，还请说明。

**Comment by esdeathlove** [comment]
会添加，根据具体情况的不同有不同的添加方式。
