### ISSUE TITLE
关于流量重置

### ISSUE THREAD

**Issue by kkbbzjh** [esdeathlove/ss-panel-v3-mod#565]
config中的流量重置，是重置使用流量还是重置总流量？

#注册时的流量重置日以及需要重置的流量,0不重置
$System_Config['reg_auto_reset_day']='1';
$System_Config['reg_auto_reset_bandwidth']='25';

这样子是1号重置，重置流量为25G？那使用流量如何清零？

**Comment by esdeathlove** [comment]
@kkbbzjh 0

**Comment by kkbbzjh** [comment]
@esdeathlove 设置为0即为清空使用流量？

**Comment by esdeathlove** [comment]
@kkbbzjh 会自动重置为 0 。。这种自己试试就会得到结果了

**Comment by kkbbzjh** [comment]
好的，谢谢
