### ISSUE TITLE
管理员登录状态下 /admin/* 跳转 /user

### ISSUE THREAD

**Issue by jcpwfloi** [esdeathlove/ss-panel-v3-mod#566]
/admin 是可以进的但是其他 /admin/* 的页面全都 302 到 /user 了

检查元素打开一看就是只有 302，debug 打开什么都没有输出……

我检查了数据库 is_admin 是 1 没有问题的 Orz

**Comment by esdeathlove** [comment]
开了 CDN 的话就检查 CDN。
