### ISSUE TITLE
安装同步时出现数据库连接问题

### ISSUE THREAD

**Issue by wangchunming** [esdeathlove/ss-panel-v3-mod#568]
到了sspannel添加管理员账户这一关  php -n xcat createAdmin 就出现了以下错误。。。。。

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)' in /home/wwwroot/ss.51kly.net/vendor/illuminate/database/Connectors/Connector.php:55

**Comment by esdeathlove** [comment]
自己检查数据库用户。
