### ISSUE TITLE
[建议] 单端口多用户只在指定节点启用

### ISSUE THREAD

**Issue by Indexyz** [esdeathlove/ss-panel-v3-mod#572]
在有些节点会启用一些特殊的端口 但是在其他的一些服务器上这些端口是被占用的 这时候就希望能使单端口多用户在特点的服务器上运行了

**Comment by esdeathlove** [comment]
@Indexyz 你目前可以用 redirect 规则来进行复用。

**Comment by Indexyz** [comment]
如果进行 redirect 规则的话无法在面板显示啊……

**Comment by esdeathlove** [comment]
@Indexyz 可以，这个是后端的设置，与面板无关。

**Comment by Indexyz** [comment]
比如我使用socat重定向了一个443端口到80端口上的多用户单端口 
![image](https://cloud.githubusercontent.com/assets/7685264/22072910/d2779382-ddde-11e6-9979-468843d38842.png)
现在能够使用443链接这个端口 
但是前端无法显示这个多用户单端口 设定
（我感觉我的思路有点绕

**Comment by esdeathlove** [comment]
@Indexyz ssr 后端内置有 Redirect 规则，请自行研究，无需 socat .

**Comment by zzjby** [comment]
那既然多用户可以单端口了，那能不能做得更像一个网站？完全可以的，如果是http的话，服务端安装一个nginx之类，把端口开在8080（监听127.0.0.1），然后SSR的端口开在80，同时在SSR的user-config.json里修改参数 "redirect" : "127.0.0.1:8080", 这时，直接用浏览器打开，就可以直接看到你开的网站了，而改成用SSR客户端连接就成了服务端了。不过注意的是这时候最好要开相应的混淆哦ヽ(´▽｀)ノ
引用自BreakWa11的博客

**Comment by esdeathlove** [comment]
@zzjby 是的，可以的。
