### ISSUE TITLE
本鹅来问一个事

### ISSUE THREAD

**Issue by Moehentai2333** [esdeathlove/ss-panel-v3-mod#574]
就是为什么后台管理的系统概览中的流量使用情况今日已使用的流量一直是总的使用流量，而已使用的流量一直是0呢，噗噗噗=￣ω￣=

**Comment by feileb** [comment]
crontab -e

30 22 * * * php /home/wwwroot/ss.panel/xcat sendDiaryMail
*/1 * * * * php /home/wwwroot/ss.panel/xcat synclogin
*/1 * * * * php /home/wwwroot/ss.panel/xcat syncvpn
0 0 * * * php -n /home/wwwroot/ss.panel/xcat dailyjob
*/1 * * * * php /home/wwwroot/ss.panel/xcat checkjob    
*/1 * * * * php -n /home/wwwroot/ss.panel/xcat syncnas

如果是ubuntu去掉-n

**Comment by Moehentai2333** [comment]
啊，忘记关闭issue了，本鹅是php7，之前发现了原来本鹅忘把n去掉了
