### ISSUE TITLE
搭建前端时遇到的问题

### ISSUE THREAD

**Issue by A1exLiu** [esdeathlove/ss-panel-v3-mod#575]
数据库全部正常导入，但在执行"php xcat createAdmin"时系统报错：
`PHP Parse error:  syntax error, unexpected '[' in /home/wwwroot/站点文件夹/vendor/react/promise/src/functions.php on line 15`
（站点名称已隐藏）
问题出在这里，我还有另一台已经搭好前段的机器，两台机器的functions.php是一模一样的，php版本也都是7.0.7，为什么会出现一台报错而另一台正常的现象呢？
麻烦指点一下，不胜感激。

**Comment by esdeathlove** [comment]
@A1exLiu 把这文件截图发上来

**Comment by esdeathlove** [comment]
@A1exLiu php -v 结果也发下

**Comment by A1exLiu** [comment]
问题已发现，不知道为什么lnmp选择了php 707却还是装了5.3，抱歉了

**Comment by A1exLiu** [comment]
经历了诡异的事件
昨天以为是版本安装错误，所以今天重开了台机器
这次已经确认好安装lnmp时选择的是php7
'php -v'输出信息也显示为php7
但是在导入原来机器(CentOS 6 x64, php7)的数据表之后
执行'php xcat createAdmin'进行测试，仍然报错
此时'php -v'输出信息已经变成了php 5.3版本
麻烦指点一下

**Comment by A1exLiu** [comment]
Checked
罪魁祸首是phpMyAdmin，yum自带的源太旧了
![image](https://cloud.githubusercontent.com/assets/21982749/22140702/0d9f9158-df29-11e6-92af-a734ad244b74.png)
