### ISSUE TITLE
赵大神，crontab -e添加了路径，过期后依然不降级

### ISSUE THREAD

**Issue by alstarking** [esdeathlove/ss-panel-v3-mod#576]
![1](https://cloud.githubusercontent.com/assets/24618335/22109782/28a2c37a-de94-11e6-8536-7c426e706fac.png)

大神请看。config里设置的值。

**#等级到期时是否重置流量
$System_Config['enable_class_expire_reset']='true';

#等级到期时重置为的流量值，GB
$System_Config['enable_class_expire_reset_traffic']='6';**

**Comment by miniaoe** [comment]
我是自己写了个脚本，30分钟检查一次，人少可以人多就笨重了

**Comment by miniaoe** [comment]
有没有重启 crontab

**Comment by JohnFreeman9** [comment]
你确保crond服务运行了吗？
job里是有两次等级归零的，目前而言应该不可能出现不归零情况

**Comment by alstarking** [comment]
@JohnFreeman9
Starting crond:                                            [  OK  ]
开着的。。

**Comment by waitli** [comment]
我也是存在这个问题，切换到spay版本的，不知道是不是跟这个有关系 ， 而且crontab 一直报警告，mail几乎每分钟都有邮件

**Comment by waitli** [comment]
Message 40491:
From root@localhost.localdomain  Fri Feb  3 15:06:02 2017
Return-Path: <root@localhost.localdomain>
Date: Fri, 3 Feb 2017 15:06:02 +0800
From: root@localhost.localdomain (Cron Daemon)
To: root@localhost.localdomain
Subject: Cron <root@localhost> /usr/local/php/bin/php  /data/wwwroot/www.ae86.pub/xcat checkjob    
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Status: R

PHP Notice:  Trying to get property of non-object in /data/wwwroot/www.ae86.pub/app/Command/Job.php on line 296
PHP Warning:  Creating default object from empty value in /data/wwwroot/www.ae86.pub/app/Command/Job.php on line 316
PHP Fatal error:  Call to undefined method stdClass::save() in /data/wwwroot/www.ae86.pub/app/Command/Job.php on line 323

& 
Message 40492:
From root@localhost.localdomain  Fri Feb  3 15:07:03 2017
Return-Path: <root@localhost.localdomain>
Date: Fri, 3 Feb 2017 15:07:03 +0800
From: root@localhost.localdomain (Cron Daemon)
To: root@localhost.localdomain
Subject: Cron <root@localhost> /usr/local/php/bin/php  /data/wwwroot/www.ae86.pub/xcat checkjob    
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Status: R

PHP Notice:  Trying to get property of non-object in /data/wwwroot/www.ae86.pub/app/Command/Job.php on line 296
PHP Warning:  Creating default object from empty value in /data/wwwroot/www.ae86.pub/app/Command/Job.php on line 316
PHP Fatal error:  Call to undefined method stdClass::save() in /data/wwwroot/www.ae86.pub/app/Command/Job.php on line 323

& 


上面是mail 上面的php警告

**Comment by esdeathlove** [comment]
清空 disconnect 表

**Comment by waitli** [comment]
好 我试试

**Comment by waitli** [comment]
+--------------------+
| Tables_in_ae86     |
+--------------------+
| alive_ip           |
| announcement       |
| auto               |
| blockip            |
| bought             |
| code               |
| coupon             |
| detect_list        |
| detect_log         |
| disconnect_ip      |
| email_verify       |
| link               |
| login_ip           |
| payback            |
| paylist            |
| radius_ban         |
| relay              |
| shop               |
| speedtest          |
| ss_invite_code     |
| ss_node            |
| ss_node_info       |
| ss_node_online_log |
| ss_password_reset  |
| ticket             |
| unblockip          |
| user               |
| user_token         |
| user_traffic_log   |
+--------------------+
29 rows in set (0.02 sec)

MySQL [ae86]> truncate disconnect_ip;
Query OK, 0 rows affected (0.06 sec)


数据库钟只有这个表， 但是空的

**Comment by waitli** [comment]
。。。。这边网站暴露了 ，，然后被打死了

**Comment by esdeathlove** [comment]
1.
