### ISSUE TITLE
面板中的自定义协义功能不管用

### ISSUE THREAD

**Issue by ziluopao** [esdeathlove/ss-panel-v3-mod#577]
试了N次了，只能读取json中的配置能管事
对了，不要问我启动自定义功能没，启了哈！这个不用担心

**Comment by esdeathlove** [comment]
@ziluopao 你开了节点的自定义吗？

**Comment by ziluopao** [comment]
启了

**Comment by esdeathlove** [comment]
@ziluopao 自定义协议功能？你指的是什么？请描述的清楚些。

**Comment by ziluopao** [comment]
我说一下我的完整操作，用管理员身份进入管理面板中，点击节点中的节点列表，进入某节点，在其中开启自定义加密和自定义协议&混淆两项，把按钮拖到右边呈现粉红色，修改保存。
再进入用户中的用户列表选项，点其中的一个用户，更改里面的自定义协议，改成，如auth_sha1_v2和自定义混淆方式tls1.2_ticket_auth，修改保存，退出！
在客户端一一对应其参数，进行测试，结果：屡次失败！
然后，把其中的参数再改成use-config.json中的协议参数，翻墙成功！
过程就是这样！以上测试搞了不下50次，上晚上的功夫！

**Comment by ziluopao** [comment]
# Config
API_INTERFACE = 'sspanelv2' #mudbjson, sspanelv2, sspanelv3, sspanelv3ssr, muapiv2(not support)
UPDATE_TIME = 60
SERVER_PUB_ADDR = '127.0.0.1' # mujson_mgr need this to generate ssr link

#mudb
MUDB_FILE = 'mudb.json'

# Mysql
MYSQL_CONFIG = 'usermysql.json'

# API
MUAPI_CONFIG = 'usermuapi.json'


~

**Comment by esdeathlove** [comment]
@ziluopao 哦，你没看这个后端的文档吗，能自定义的不是这个 API_INTERFACE。

**Comment by ziluopao** [comment]
哦，我去查看一下。
