### ISSUE TITLE
这个表还要自己建吗，或者说不建也行？当然这个不影响翻墙！

### ISSUE THREAD

**Issue by ziluopao** [esdeathlove/ss-panel-v3-mod#579]
2017-01-20 11:11:42 ERROR    db_transfer.py:480 (1146, u"Table 'shadowsocksr.ss_node_info_log' doesn't exist")

**Comment by esdeathlove** [comment]
@ziluopao 你就不能用我改过的后端？

**Comment by zzice** [comment]
求搭建教程地址

**Comment by ziluopao** [comment]
我怎么可能用别人的后端，到你的issues中报错呢？

**Comment by esdeathlove** [comment]
@ziluopao 不，这个是原版 SSR 的后端。

**Comment by ziluopao** [comment]
我是在这个页面https://github.com/esdeathlove/ss-panel-v3-mod中的code选项卡里下载的，难道这个是原版的？

**Comment by esdeathlove** [comment]
@ziluopao 什么，这里面没有后端下载。

**Comment by ziluopao** [comment]
你说的后端，是不是指的SSR的服务端？

**Comment by esdeathlove** [comment]
@ziluopao 对。

**Comment by ziluopao** [comment]
我是不是可以这样理解，如果不用你改的SSR服务端，而用原版的，那么在运行前端管理面板时会出很多问题，甚至不能使用？

**Comment by esdeathlove** [comment]
@ziluopao 功能不全。

**Comment by ziluopao** [comment]
这个面板配合哪个后端好些呢，是它吗shadowsocks-libev

**Comment by ziluopao** [comment]
我认为你即然是开源的，在wiki上应该提醒一下别人应该用啥不应该用啥，哪容易出现问题，你这些都没有提，而是在等测试的人和你在挤牙膏似的对话！

**Comment by esdeathlove** [comment]
@ziluopao 我写在安装说明里了，你自己没看到，怪谁呢。

**Comment by Fribyter** [comment]
给提这issue的哥们跪了
