### ISSUE TITLE
不知我的理解自定义对吗？

### ISSUE THREAD

**Issue by ziluopao** [esdeathlove/ss-panel-v3-mod#580]
数据库版的控制面板中的自定义，指的是管理员有这个权利，而普通用户是没有的，比如你注册了一个用户，买了一个ssr号，但是你不能自己定义协议，要定义只能申请管理员给你改。

**Comment by esdeathlove** [comment]
@ziluopao 不对。

**Comment by A1exLiu** [comment]
普通用户拥有自定义**自己**端口使用协议及混淆的权限，管理员或者站长可以通过修改数据库来更改任意用户使用的协议及混淆
