### ISSUE TITLE
邮箱验证返回的是空白 debug没查出原因

### ISSUE THREAD

**Issue by alstarking** [esdeathlove/ss-panel-v3-mod#581]
![error](https://cloud.githubusercontent.com/assets/24618335/22144598/41426a98-df39-11e6-9955-1688d2b7c35a.png)
AuthController.php我没有改动。一点验证就返回空白提示。
重置密码提示返回：正在发送，请稍候。。。  
之后就没有之后了。
请问，我该怎么做能解决？好几天了也没解决这个问题。火狐浏览器的网络监视器显示状态302.

**Comment by winnie20tu** [comment]
`cd /home/wwwroot/你的网站目录`
`nano config/.config.php`

找到//邮件，改为smtp
`$System_Config['mailDriver'] = 'smtp';`

并在底下# smtp 按要求修改

**Comment by esdeathlove** [comment]
按照说明开debug，一般是你没设置好。
