### ISSUE TITLE
我想问几个问题，有些烦人啊

### ISSUE THREAD

**Issue by wangchunming** [esdeathlove/ss-panel-v3-mod#582]
1.为什么在后台设置节点为shadowsocks多用户单端口后该节点无法显示？
2.为什么无法自动开户为多用户单端口，手动指定两个用户为混淆式多用户单端口后面的无法连接。
3.WIKI中的多用户单端口混淆要怎么用？设置了混淆参数要让用户写在客户端上吗？

。。。。。。。问着问着思路也乱了

目前没有站点，还没有搭建成功呢

**Comment by esdeathlove** [comment]
@wangchunming 1.请仔细阅读 wiki 里的添加步骤。
2.同上，自己理解。
3.你添加完就知道了。
