### ISSUE TITLE
计划任务提示错误。

### ISSUE THREAD

**Issue by wanguo06** [esdeathlove/ss-panel-v3-mod#583]
php -n /home/xxx/sspanel/xcat syncnas

提示
`X-Powered-By: PHP/5.6.29
Content-type: text/html; charset=UTF-8

<br />
<b>Fatal error</b>:  Interface 'JsonSerializable' not found in <b>/home/xxx/sspanel/vendor/illuminate/support/Fluent.php</b> on line <b>11</b><br />`

网站是在cp主机上运行。 cp里自定义php为php7版本。

是不是计划任务用的php默认版本（5.6）过低？ 如果是能不是计划任务改成curl http://ip/xcat方式执行？或者有其他解决办法吗？

**Comment by esdeathlove** [comment]
@wanguo06 不能，请检查 PHP 组件是否安装完全。

**Comment by wanguo06** [comment]
php5.6版本可以正常运行吗？

网站运行环境是没问题的。 就是系统默认php不清楚

**Comment by esdeathlove** [comment]
@wanguo06 组件。
