### ISSUE TITLE
在哪里可以修改gui-config.conf文件的生成参数？

### ISSUE THREAD

**Issue by kkbbzjh** [esdeathlove/ss-panel-v3-mod#585]
all-in-one生成win电脑版的那个配置文件，没有SSR的协议和混淆，导致节点无法使用，能否加进去？

**Comment by esdeathlove** [comment]
@kkbbzjh 有的，请确保你打开完整乐所有开关。

**Comment by kkbbzjh** [comment]
请问，打开所有开关是指？哪里的？

**Comment by esdeathlove** [comment]
SSR 功能开关。config里。

**Comment by kkbbzjh** [comment]
@esdeathlove 您好，我仔细的找了下.config.php里面的内容，是不是版本问题？我的并没有关于SSR的开关设置。网站是最近搭建的，近期应该没有更新吧？

#功能开关
$System_Config['enable_wecenter']='false';
$System_Config['enable_radius']='false';
$System_Config['enable_cloudxns']='false';
$System_Config['enable_duoshuo']='false';
$System_Config['enable_rss']='true';
$System_Config['enable_paymentwall']='true';
