### ISSUE TITLE
请问如果从另一个服务器上使用SSpanel控制ssr

### ISSUE THREAD

**Issue by JuiceCC** [esdeathlove/ss-panel-v3-mod#589]
请问如果从另一个服务器上使用SSpanel控制ssr，该怎么写配置文件。查看了WIKI也没有这方面的解释。

**Comment by zzjby** [comment]
安装ssr数据库版就行了

**Comment by JuiceCC** [comment]
额，但是我看见配置文件有个API还有manager的选项，能麻烦大佬告诉我怎么修改嘛？

**Comment by zzjby** [comment]
没懂你什么意思，要怎么控制？看wiki安装不就行了？

**Comment by silentstage** [comment]
sspanel服务器数据库建好，用户设置允许远程访问，iptables里端口打开，好像是3306？然后SSR服务器部署好后，userapiconfig.py里把数据库的信息填对，就完了

**Comment by JuiceCC** [comment]
你好。我的意思是。我买了一个搬瓦工和Vultr的服务器。然后在搬瓦工的服务器上装了lnmp和ss-panel-v3-mod。在Vultr的服务器上安装了Wiki里推荐的后端。SSpanel的是按照WIki上安装的。Vultr上的服务器连接搬瓦工的数据库总是连接不了。然后SSPanel也没办法查看Vultr服务器里的状态

**Comment by JuiceCC** [comment]
还有就是远程访问的话就是把Host设置成%就可以了么

**Comment by silentstage** [comment]
Host设成%，还要看搬瓦工上iptables里的规则，3306是不是Drop，改成accept。我也是搬瓦工装的sspanel+ssr，挂Vultr和另外个节点

**Comment by JuiceCC** [comment]
啊你好，我搬瓦工的服务器是centos6应该防火墙是全部开放的吧

**Comment by JuiceCC** [comment]
各位大佬，我记得Wiki推荐的那个后端配置文件里应该还有个API什么的，需要修改么？

**Comment by alstarking** [comment]
@JuiceCC 不需要。。如果vultr跟板瓦工连不上，多半是iptables 没关闭。。关闭防火墙chkconfig iptables off   
重启后生效。

**Comment by JuiceCC** [comment]
哦哦也就是说只用修改Mysql配置么，啊谢谢各位大佬，祝各位大佬鸡年大吉吧！
