### ISSUE TITLE
神啊，救救我吧。大神，获取验证码返回空。(已解决！)

### ISSUE THREAD

**Issue by alstarking** [esdeathlove/ss-panel-v3-mod#593]
![error](https://cloud.githubusercontent.com/assets/24618335/22207301/98dff5cc-e1b9-11e6-80af-5568beae1f7d.png)

这个问题我弄了很多天了，我今天特意新购买一个vps，开始怀疑是我vps的问题。新购买的vps还是这样。

大神，debug保持一直开启中。。。求大神帮调试一下，www.heimi.cf  （新注册的免费域名）

已经来回重复安装六七次了，原来用的lnmp，现在用的宝塔管理。都是返回空。。

附上我的日志
[www.heimi.cf.log.txt](https://github.com/esdeathlove/ss-panel-v3-mod/files/723855/www.heimi.cf.log.txt)

"POST /auth/send HTTP/1.1" 302 0 "http://heimi.cf/auth/register" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
"GET /500 HTTP/1.1" 500 4203 "http://heimi.cf/auth/register" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"

**Comment by JohnFreeman9** [comment]
已解决麻烦close好吗。。
