### ISSUE TITLE
观察窗怎么一直没有任何显示？

### ISSUE THREAD

**Issue by silentstage** [esdeathlove/ss-panel-v3-mod#596]
我搜了下issue，好像是说要装speedtest，我装了还是没有显示，是怎么回事呢？是有设置之类关联么？我就看到.config.php里面有一个测速间隔时间选项

**Comment by esdeathlove** [comment]
你后端怎么设置的？2017年1月26日 上午11:39，silentstage <notifications@github.com>写道：我搜了下issue，好像是说要装speedtest，我装了还是没有显示，是怎么回事呢？是有设置之类关联么？我就看到.config.php里面有一个测速间隔时间选项

**Comment by silentstage** [comment]
是不是我用的SSR后端的问题？我看改下配置也能用就没部署你的版本了

**Comment by esdeathlove** [comment]
是的。那个不支持。2017年1月26日 下午1:12，silentstage <notifications@github.com>写道：是不是我用的SSR后端的问题？我看改下配置也能用就没部署你的版本了

**Comment by silentstage** [comment]
嗯，回头部署看看，谢谢解答。
