### ISSUE TITLE
运行xcat syncusers报错

### ISSUE THREAD

**Issue by mxihan** [esdeathlove/ss-panel-v3-mod#597]
运行xcat syncusers报错
报错

syntax error, unexpected '[' in /home/wwwroot/ss.panel/vendor/react/promise/src/functions.php on line 15
请教一下是哪里的问题？

**Comment by esdeathlove** [comment]
更新 PHP 版本。2017年1月27日 下午3:09，mxihan <notifications@github.com>写道：运行xcat syncusers报错
报错
syntax error, unexpected '[' in /home/wwwroot/ss.panel/vendor/react/promise/src/functions.php on line 15
请教一下是哪里的问题？

**Comment by A1exLiu** [comment]
不要用php 5.3及以下版本

**Comment by mxihan** [comment]
问题已解决
