### ISSUE TITLE
执行service radiusd start && chkconfig radiusd on时提示faild

### ISSUE THREAD

**Issue by JuiceCC** [esdeathlove/ss-panel-v3-mod#602]
到了这一步提示
Starting radiusd                 [FAILED]
然后配置也没有错，并不知道哪里出了问题

**Comment by esdeathlove** [comment]
radiusd -X

**Comment by JuiceCC** [comment]
直接输这个指令就完了是么？话说为什么会出这个问题

**Comment by esdeathlove** [comment]
我也不知道，你自己的配置文件，那个是调试的命令。

**Comment by JuiceCC** [comment]
我记得我打了过后什么显示都没有，然后就没事了……配置文件也是按照wiki改的，难道跟Mysql版本有关？

**Comment by esdeathlove** [comment]
不可能什么都没有，要不然就是你没打对。

**Comment by JuiceCC** [comment]
等我回去重装试试，方便提供下您的Telegram帐号么

**Comment by JuiceCC** [comment]
![qq 20170131220534](https://cloud.githubusercontent.com/assets/20995257/22467985/bb4232a8-e801-11e6-8de2-7e552ffd7769.png)
![qq 20170131220658](https://cloud.githubusercontent.com/assets/20995257/22467986/bb563384-e801-11e6-8020-94287eb8b144.png)
这是我服务器的 截图。不知道是什么情况

**Comment by JuiceCC** [comment]
![231](https://cloud.githubusercontent.com/assets/20995257/22468105/23f8cd20-e802-11e6-9494-5c4232fef5a5.png)
这是Mysql的数据库截图。可以麻烦您看下么

**Comment by JuiceCC** [comment]
我是centos6.5 x64

**Comment by esdeathlove** [comment]
radius 看起来是正常运行了，建议你查查 /var/log 下面的日志文件有没有端倪。

**Comment by etnperlong** [comment]
我知道是什么原因了，Ubuntu下安装的freeradius路径以及用户和用户组都不一样。

以下是我根据提供的radiusd.conf 所作的修改，不知道有没有缺漏
logdir字段 修改为 ${localstatedir}/log/freeradius
name字段 修改为 freeradius
user和group修改为 freerad

在我的Ubuntu 16.04 上测试成功，可以启动服务。
