### ISSUE TITLE
zfbjk的回调地址问题

### ISSUE THREAD

**Issue by sd362318** [esdeathlove/ss-panel-v3-mod#604]
回调地址 /pay_callback直接访问405错误是正常的还是有问题的？
我在监控端回调地址设置的是[网站地址/pay_callback],显示通知失败。

**Comment by esdeathlove** [comment]
post 请求，另外因为 Zfbjk 那里我没条件测试，所以希望你们能帮我测试下。有调试日志的话可以给我。

**Comment by sd362318** [comment]
可以加我TG【@fireka】吗，我不知道怎么查这个问题的错误，但是我可以提供zfbjk这个测试条件给你。

**Comment by yjy11994** [comment]
域名/alipay_callback实测成功
