### ISSUE TITLE
执行php xcat initdownload时报错

### ISSUE THREAD

**Issue by A1exLiu** [esdeathlove/ss-panel-v3-mod#606]
在站点根目录执行`php xcat initdownload`时提示错误
`PHP Warning:  system() has been disabled for security reasons in /home/wwwroot/站点目录/app/Command/XCat.php on line 90`
站点目录已隐藏
劳烦解答一下，谢谢

**Comment by esdeathlove** [comment]
php -n 运行下

**Comment by A1exLiu** [comment]
@esdeathlove 没有输出

**Comment by A1exLiu** [comment]
已解决，执行`php -n xcat initdownload`即可

**Comment by A1exLiu** [comment]
@esdeathlove 建议作者修改一下更新说明
