### ISSUE TITLE
执行更新之后站点无法访问

### ISSUE THREAD

**Issue by A1exLiu** [esdeathlove/ss-panel-v3-mod#608]
执行完今天的更新之后，站点直接变成空白页面
麻烦帮忙看一下
站点: https://ss.a1ex.pw
debug已打开

**Comment by esdeathlove** [comment]
你配置文件前加了东西，或者用了不合适的编辑器。

**Comment by A1exLiu** [comment]
@esdeathlove 已解决，在用别人的电脑所以没有notepad++。另外另一个问题能不能劳烦看一下？
