### ISSUE TITLE
spay充值出现504网关错误

### ISSUE THREAD

**Issue by laoxiu001** [esdeathlove/ss-panel-v3-mod#609]
之前用的spay_back分支，前几天突然一直显示504网关超时或解析器有误，但是进入spay后台接口日志能看见等待付款订单，今天刚刚更新了新分支，更新了之后还是504错误。
尝试了开debug，没有错误提示；试过git reset --hard重置也不行；问了spay那边的客服说是我这边的网络问题，但是所有用户都无法充值。所以想问下这种问题应该怎么解决呢？谢谢

**Comment by esdeathlove** [comment]
504 bad gateway 请检查php和nginx之间的连接。

**Comment by A1exLiu** [comment]
@esdeathlove 我这里碰到了类似的问题，spay通知提示`504 Gateway Time-out`，如果检查的话应该使用什么命令呢？能否指教一下？

**Comment by A1exLiu** [comment]
@esdeathlove 重启之后由504变成了502…
`<html> <head><title>502 Bad Gateway</title></head> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <body bgcolor=\"white\"> <center><h1>502 Bad Gateway</h1></center> <center>可能被http接口方拒绝，请按照<a href="http://www.sinacloud.com/doc/sae/services/fetchurl.html?highlight=fetchurl">文档</a>添加白名单</center> <hr><center>FetchUrl</center> </body> </html>`

**Comment by laoxiu001** [comment]
@A1exLiu 你看下nginx的日志怎么报错的？我的报错是这样的：
`2017/01/31 18:01:48 [emerg] 9928#0: "fastcgi_intercept_errors" directive is duplicate in /usr/local/nginx/conf/nginx.conf:60
2017/01/31 18:02:13 [emerg] 10505#0: "fastcgi_intercept_errors" directive is duplicate in /usr/local/nginx/conf/nginx.conf:60`
谷歌找了很多资料还是没有头绪，突然出现的错误。。。

**Comment by laoxiu001** [comment]
找到日志问题了
`2017/02/01 16:11:46 [crit] 7608#0: *1 connect() to unix:/tmp/php-cgi.sock failed (2: No such file or directory) while connecting to upstream, client: 10.12.22.203, server: www.****.com, request: "GET /user/code HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "www.****.com", referrer: "https://www.****.com/user/code"`

**Comment by A1exLiu** [comment]
@laoxiu001 你的日志是在哪儿里找的，我在`/usr/local/php/log`和`/usr/local/nginx/logs`都没找到记录

**Comment by laoxiu001** [comment]
@A1exLiu /home/wwwlogs/nginx_error.log

**Comment by A1exLiu** [comment]
@laoxiu001 空文件，没有任何内容

**Comment by A1exLiu** [comment]
已恢复正常，@laoxiu001 重启fpm之后等一段时间再看看`lnmp php-fpm restart`

**Comment by laoxiu001** [comment]
@A1exLiu 好吧，我这边用这个命令试过了，不行。
不过最近发现另外一个支付宝接口，感觉还不错，如果有多几个接口一起使用的话肯定会好一点。
http://api.web567.net/plugin.php?id=add
