### ISSUE TITLE
恢复站点，登录成功后500错误

### ISSUE THREAD

**Issue by Bigblackbanner** [esdeathlove/ss-panel-v3-mod#611]
![1](https://cloud.githubusercontent.com/assets/21064246/22546733/3243f8c8-e979-11e6-84e3-9c12452fe17b.png)

错误如图，登录站点500错误，都是原来的 config文件和数据库

我没有开启  telegram_bot 不知道为什么这样报错。

**Comment by Bigblackbanner** [comment]
我的是以前的数据库和配置文件备份。这次是重新git安装，然后就无法使用了。

**Comment by esdeathlove** [comment]
请按照更新说明添加配置项。
