### ISSUE TITLE
希望添加节点界面增加一个功能

### ISSUE THREAD

**Issue by IMAsukininaru** [esdeathlove/ss-panel-v3-mod#612]
希望添加节点时可以有一个选项，是对此节点使用审计或不对此节点使用审计。
因为国内分享环境太差，需要使用一些罗马尼亚的节点来下bt之类的资源。但是又不想让用户使用其他节点下BT以免被投诉。希望能增加一个对单个节点不审计的功能

**Comment by gaoyuoppa** [comment]
希望加入。
