### ISSUE TITLE
恢复站点，进入首页Error 500

### ISSUE THREAD

**Issue by Tedjiuis** [esdeathlove/ss-panel-v3-mod#613]
![r r g_ g c ed szpysrsqj](https://cloud.githubusercontent.com/assets/25507345/22552887/ad2a59c6-e995-11e6-9988-59029a03450c.png)
![mv 4offa 51plogfiv 5fw](https://cloud.githubusercontent.com/assets/25507345/22552888/ad303e54-e995-11e6-898b-7c478439fb99.png)
如图，数据库是以前备份恢复过来的，config也是最新的，文件权限全755，ssl也正常，按照安装文档配置的，但是尝试多次打不开页面，代码是今天刚git过来的。

**Comment by esdeathlove** [comment]
请按照 https://github.com/esdeathlove/ss-panel-v3-mod/issues/554 的说明进行排错。

**Comment by Tedjiuis** [comment]
![_ 0as 5 ho qj2r40373kvq](https://cloud.githubusercontent.com/assets/25507345/22589066/49d3239a-ea43-11e6-892d-3d4f490d7e31.png)
![x d x dhffiawu00s2gafj6](https://cloud.githubusercontent.com/assets/25507345/22589067/49dbfccc-ea43-11e6-90e2-b3add4d6b346.png)
打开了debug开关，但是前端并没有输出错误信息
![7 nf24umlxu1k2wolf8_ 5k](https://cloud.githubusercontent.com/assets/25507345/22589163/e3916974-ea43-11e6-9ce7-545b20ef9b71.png)

**Comment by imyvm** [comment]
新安装，一直500报错，开了debug也毫无报错信息。

**Comment by esdeathlove** [comment]
开 php 的报错信息。。。

**Comment by imyvm** [comment]
`Warning: require(): open_basedir restriction in effect. File(/home/wwwroot/example/bootstrap.php) is not within the allowed path(s): (/home/wwwroot/example/public/:/tmp/:/proc/) in /home/wwwroot/example/public/index.php on line 7

Warning: require(/home/wwwroot/example/bootstrap.php): failed to open stream: Operation not permitted in /home/wwwroot/example/public/index.php on line 7

Fatal error: require(): Failed opening required '/home/wwwroot/example/public/../bootstrap.php' (include_path='.:/usr/local/php/lib/php') in /home/wwwroot/example/public/index.php on line 7`

尝试设置php.ini和nginx配置，但还是这个错误提示。

**Comment by Tedjiuis** [comment]
Warning: require(): open_basedir restriction in effect. File(/home/wwwroot/sp/bootstrap.php) is not within the allowed path(s): (/home/wwwroot/sp/public/:/tmp/:/proc/) in /home/wwwroot/sp/public/index.php on line 7

Warning: require(/home/wwwroot/sp/bootstrap.php): failed to open stream: Operation not permitted in /home/wwwroot/sp/public/index.php on line 7

Fatal error: require(): Failed opening required '/home/wwwroot/sp/public/../bootstrap.php' (include_path='.:/usr/local/php/lib/php') in /home/wwwroot/sp/public/index.php on line 7

**Comment by ownones** [comment]
看看 /home/wwwroot/'xxx' 目录下是否有 vendor 文件夹

**Comment by Tedjiuis** [comment]
有
![f329wxwmztwgko7_x ytq f](https://cloud.githubusercontent.com/assets/25507345/22593005/74bc5694-ea57-11e6-9c8c-6c0174a8368b.png)

**Comment by esdeathlove** [comment]
加进你的 opendir 里。2017年2月3日 下午9:18，Tedjiuis <notifications@github.com>写道：Warning: require(): open_basedir restriction in effect. File(/home/wwwroot/sp/bootstrap.php) is not within the allowed path(s): (/home/wwwroot/sp/public/:/tmp/:/proc/) in /home/wwwroot/sp/public/index.php on line 7
Warning: require(/home/wwwroot/sp/bootstrap.php): failed to open stream: Operation not permitted in /home/wwwroot/sp/public/index.php on line 7
Fatal error: require(): Failed opening required '/home/wwwroot/sp/public/../bootstrap.php' (include_path='.:/usr/local/php/lib/php') in /home/wwwroot/sp/public/index.php on line 7

**Comment by Tedjiuis** [comment]
加进去了，还是这样

**Comment by zzjby** [comment]
用的LNMP ？
把 /usr/local/nginx/conf/fastcgi.conf
中的fastcgi_param PHP_ADMIN_VALUE "open_basedir=$document_root/:/tmp/:/proc/"; 注释掉试试

**Comment by Tedjiuis** [comment]
注释掉fastcgi_param PHP_ADMIN_VALUE "open_basedir=$document_root/:/tmp/:/proc/";之后
出现了如下错误
Whoops\Exception\ErrorException thrown with message "scandir() has been disabled for security reasons"

Stacktrace:
#17 Whoops\Exception\ErrorException in /home/wwwroot/sp/app/Controllers/HomeController.php:108
#16 scandir in /home/wwwroot/sp/app/Controllers/HomeController.php:108
#15 App\Controllers\HomeController:page500 in /home/wwwroot/sp/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:41
#14 call_user_func in /home/wwwroot/sp/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:41
#13 Slim\Handlers\Strategies\RequestResponse:__invoke in /home/wwwroot/sp/vendor/slim/slim/Slim/Route.php:344
#12 Slim\Route:__invoke in /home/wwwroot/sp/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:116
#11 Slim\Route:callMiddlewareStack in /home/wwwroot/sp/vendor/slim/slim/Slim/Route.php:316
#10 Slim\Route:run in /home/wwwroot/sp/vendor/slim/slim/Slim/App.php:438
#9 Slim\App:__invoke in /home/wwwroot/sp/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php:62
#8 Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware:__invoke in /home/wwwroot/sp/vendor/slim/slim/Slim/DeferredCallable.php:43
#7 call_user_func_array in /home/wwwroot/sp/vendor/slim/slim/Slim/DeferredCallable.php:43
#6 Slim\DeferredCallable:__invoke in /home/wwwroot/sp/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:67
#5 call_user_func in /home/wwwroot/sp/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:67
#4 Slim\App:Slim\{closure} in /home/wwwroot/sp/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:116
#3 Slim\App:callMiddlewareStack in /home/wwwroot/sp/vendor/slim/slim/Slim/App.php:332
#2 Slim\App:process in /home/wwwroot/sp/vendor/slim/slim/Slim/App.php:293
#1 Slim\App:run in /home/wwwroot/sp/config/routes.php:303
#0 require in /home/wwwroot/sp/public/index.php:11

然后把sandir函数解禁了，然后又出现

SmartyException thrown with message "Unable to load template 'file:analytics.tpl' in 'file:footer.tpl'"

Stacktrace:
#29 SmartyException in /home/wwwroot/sp/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:185
#28 Smarty_Internal_Template:render in /home/wwwroot/sp/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:372
#27 Smarty_Internal_Template:_subTemplateRender in /home/wwwroot/sp/storage/framework/smarty/compile/0d887f439e3c62658d8527496c324d929d3d00f8_0.file.footer.tpl.php:30
#26 content_589725d93d26b1_90966318 in /home/wwwroot/sp/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:128
#25 Smarty_Template_Resource_Base:getRenderedTemplateCode in /home/wwwroot/sp/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php:172
#24 Smarty_Template_Compiled:render in /home/wwwroot/sp/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:206
#23 Smarty_Internal_Template:render in /home/wwwroot/sp/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:372
#22 Smarty_Internal_Template:_subTemplateRender in /home/wwwroot/sp/storage/framework/smarty/compile/01b772263107d4c9f2a5bf7f4982894ad8b72183_0.file.500.tpl.php:91
#21 content_58972677123127_40301974 in /home/wwwroot/sp/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:128
#20 Smarty_Template_Resource_Base:getRenderedTemplateCode in /home/wwwroot/sp/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php:172
#19 Smarty_Template_Compiled:render in /home/wwwroot/sp/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:206
#18 Smarty_Internal_Template:render in /home/wwwroot/sp/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php:216
#17 Smarty_Internal_TemplateBase:_execute in /home/wwwroot/sp/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php:122
#16 Smarty_Internal_TemplateBase:display in /home/wwwroot/sp/app/Controllers/HomeController.php:119
#15 App\Controllers\HomeController:page500 in /home/wwwroot/sp/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:41
#14 call_user_func in /home/wwwroot/sp/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:41
#13 Slim\Handlers\Strategies\RequestResponse:__invoke in /home/wwwroot/sp/vendor/slim/slim/Slim/Route.php:344
#12 Slim\Route:__invoke in /home/wwwroot/sp/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:116
#11 Slim\Route:callMiddlewareStack in /home/wwwroot/sp/vendor/slim/slim/Slim/Route.php:316
#10 Slim\Route:run in /home/wwwroot/sp/vendor/slim/slim/Slim/App.php:438
#9 Slim\App:__invoke in /home/wwwroot/sp/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php:62
#8 Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware:__invoke in /home/wwwroot/sp/vendor/slim/slim/Slim/DeferredCallable.php:43
#7 call_user_func_array in /home/wwwroot/sp/vendor/slim/slim/Slim/DeferredCallable.php:43
#6 Slim\DeferredCallable:__invoke in /home/wwwroot/sp/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:67
#5 call_user_func in /home/wwwroot/sp/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:67
#4 Slim\App:Slim\{closure} in /home/wwwroot/sp/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:116
#3 Slim\App:callMiddlewareStack in /home/wwwroot/sp/vendor/slim/slim/Slim/App.php:332
#2 Slim\App:process in /home/wwwroot/sp/vendor/slim/slim/Slim/App.php:293
#1 Slim\App:run in /home/wwwroot/sp/config/routes.php:303
#0 require in /home/wwwroot/sp/public/index.php:11

**Comment by esdeathlove** [comment]
把 scandir 解除禁用
