### ISSUE TITLE
网站打不开,看了下日志没看懂,附debug日志

### ISSUE THREAD

**Issue by evolot** [esdeathlove/ss-panel-v3-mod#618]
RuntimeException thrown with message "Unexpected data in output buffer. Maybe you have characters before an opening <?php tag?"

Stacktrace:
#4 RuntimeException in /home/wwwroot/www.loneranger.us/vendor/slim/slim/Slim/App.php:552
#3 Slim\App:finalize in /home/wwwroot/www.loneranger.us/vendor/slim/slim/Slim/App.php:344
#2 Slim\App:process in /home/wwwroot/www.loneranger.us/vendor/slim/slim/Slim/App.php:298
#1 Slim\App:run in /home/wwwroot/www.loneranger.us/config/routes.php:294
#0 require in /home/wwwroot/www.loneranger.us/public/index.php:11
![](http://ww1.sinaimg.cn/large/5b6beed7gy1fce8o4novpj21kw0psn8q)
只是改了下签到流量,别的没动就打不开了

**Comment by esdeathlove** [comment]
你用的编辑器不对或者在配置文件 php 标签前加了东西。2017年2月4日 上午10:43，evolot <notifications@github.com>写道：RuntimeException thrown with message "Unexpected data in output buffer. Maybe you have characters before an opening <?php tag?"
Stacktrace:
#4 RuntimeException in /home/wwwroot/www.loneranger.us/vendor/slim/slim/Slim/App.php:552
#3 Slim\App:finalize in /home/wwwroot/www.loneranger.us/vendor/slim/slim/Slim/App.php:344
#2 Slim\App:process in /home/wwwroot/www.loneranger.us/vendor/slim/slim/Slim/App.php:298
#1 Slim\App:run in /home/wwwroot/www.loneranger.us/config/routes.php:294
#0 require in /home/wwwroot/www.loneranger.us/public/index.php:11

只是改了下签到流量,别的没动就打不开了

**Comment by evolot** [comment]
谢谢 之前用的自带编辑器,用notepad++重新写一遍好了
