### ISSUE TITLE
切换新分支后进入用户列表报错500

### ISSUE THREAD

**Issue by zhaoyan1245** [esdeathlove/ss-panel-v3-mod#621]
大神你好，前几天我切换新分支后，今天准备进后台修改用户的端口，但是却发现用户列表提示500错误，还有就是在线IP之前一直都显示正常，现在不显示了，请大神指教！

**Comment by esdeathlove** [comment]
请按照排错说明开启 debug 进行调试。

**Comment by DreamChanSS** [comment]
我也遇到这个问题 不过我是因为没有导入新的数据库的原因 导入后正常了
