### ISSUE TITLE
Telegram机器人的问题

### ISSUE THREAD

**Issue by sunnus163** [esdeathlove/ss-panel-v3-mod#624]
已经完整添加过，使用测试站点测试一切正常，但是转到正式站点就一直显示typing，节点的掉线在线皆有通知，但是ping等命令皆无反应，不知是什么原因

**Comment by esdeathlove** [comment]
你 set telegram 命令了吗2017年2月5日 上午12:44，sunnus163 <notifications@github.com>写道：已经完整添加过，使用测试站点测试一切正常，但是转到正式站点就一直显示typing，节点的掉线在线皆有通知，但是ping等命令皆无反应，不知是什么原因

**Comment by sunnus163** [comment]
set了，显示设置成功，只不过它回复不了，不管发什么都是typing。。。

**Comment by sunnus163** [comment]
试了一下，似乎是远程数据库的原因，用本地的就没问题，不知道有什么要注意的吗

**Comment by Kosonlee** [comment]
远程数据库是啥意思? 我这边是本地数据库也是这个问题

**Comment by sunnus163** [comment]
就是数据库填的不是localhost

**Comment by Kosonlee** [comment]
已经解决  user里面的ID没加进去

**Comment by hinext** [comment]
@Kosonlee user里面的ID没加进去，什么意思？怎么解决的，我遇到了同样问题

**Comment by Kosonlee** [comment]
@hinext 数据库 user表 你重新导入或者开debug看看

**Comment by hinext** [comment]
@Kosonlee 数据库 user表重新导入错误，话说debug怎么弄，如果方便可以加一下tg么 ？ 我是  hinext
