### ISSUE TITLE
如果网站用了CDN后，登陆的IP是CDN的IP呢？

### ISSUE THREAD

**Issue by gaoyuoppa** [esdeathlove/ss-panel-v3-mod#625]
如题。

**Comment by gaoyuoppa** [comment]
经过尝试。这个问题解决了。先导入新的数据库。再导入原先的数据库就可以了。
（而且， 我也是出现了类似这种问题【切换新分支后进入用户列表报错500】）

**Comment by sunnus163** [comment]
可以使用nginx的realip功能吧

**Comment by tsongneil** [comment]
同问
nginx 的realip感觉不是很好用 有其他方法么

**Comment by esdeathlove** [comment]
这个不好用你还要什么？2017年2月7日 下午12:37，tsongneil <notifications@github.com>写道：同问
nginx 的realip感觉不是很好用 有其他方法么

**Comment by gaoyuoppa** [comment]
现在的确没什么用了。- -！大佬都已经尽量隐藏用户信息了。。。。
