### ISSUE TITLE
求助网站无法备份，都设置好了。

### ISSUE THREAD

**Issue by CxiaoyuN** [esdeathlove/ss-panel-v3-mod#626]
多久时间备份一次，为什么我一直没收到备份邮件，服务器也没有。

**Comment by esdeathlove** [comment]
检查计划任务的运行状况。2017年2月5日 下午11:44，CxiaoyuN <notifications@github.com>写道：多久时间备份一次，为什么我一直没收到备份邮件，服务器也没有。

**Comment by CxiaoyuN** [comment]
在运行，但是就是不发文件，怎么检查，我看了日志，没什么问题

**Comment by esdeathlove** [comment]
phone xcat backup
