### ISSUE TITLE
db_transfer.py:484 (1146, u"Table 'sspanel.ss_node_info_log' doesn't exist")

### ISSUE THREAD

**Issue by SuanDan** [esdeathlove/ss-panel-v3-mod#627]
数据库确实还没有ss node info log这么一项…

**Comment by esdeathlove** [comment]
请切换到SSR原版后端的dev分支。2017年2月6日 上午2:42，SuanDan <notifications@github.com>写道：数据库确实还没有ss node info log这么一项…

**Comment by SuanDan** [comment]
可以了，谢谢g大
