### ISSUE TITLE
进入资料编辑500了

### ISSUE THREAD

**Issue by DreamChanSS** [esdeathlove/ss-panel-v3-mod#628]
开debug后显示这个
Illuminate\Database\QueryException thrown with message "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sspanel.telegram_session' doesn't exist (SQL: select * from `telegram_session` where `type` = 0 and `user_id` = 1 limit 1)"

**Comment by esdeathlove** [comment]
自己看更新日志。2017年2月6日 上午10:12，DreamChanSS <notifications@github.com>写道：开debug后显示这个
Illuminate\Database\QueryException thrown with message "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sspanel.telegram_session' doesn't exist (SQL: select * from telegram_session where type = 0 and user_id = 1 limit 1)"
