### ISSUE TITLE
大佬，审计规则能分享一个吗

### ISSUE THREAD

**Issue by gaoyuoppa** [esdeathlove/ss-panel-v3-mod#629]
比如屏蔽BT和邮件的。

**Comment by Woophp** [comment]
(torrent|\.torrent|peer_id=|announce|info_hash|get_peers|find_node|BitTorrent|announce_peer|protocol|announce\.php\?passkey=)

**Comment by Woophp** [comment]
(Subject|HELO|SMTP)

**Comment by gaoyuoppa** [comment]
大佬。  数据包明文匹配  是这个类型吗？

**Comment by WEGOTOFQSS** [comment]
是的

**Comment by benzBrake** [comment]
大佬，用了`(Subject|HELO|SMTP)`还是能发邮件是什么情况
