### ISSUE TITLE
issue请包含以下几个

### ISSUE THREAD

**Issue by esdeathlove** [esdeathlove/ss-panel-v3-mod#63]
1.遇到故障请先打开 config/.config.php 里的 $SystemConfig['debug']=true;

2.然后把报错信息截图发上来，ajax请求报错(就是看不到错误信息，对话框提示500)请按f12，抓包，把提交这个提交请求之后的返回信息发送给我。

3.功能故障请详细描述障碍情况。

4.提问请新开issue。

**Comment by 512557852** [comment]
debug信息在哪查看，在网页目录和/var/log/php-fpm目录下都没有发现相关的信息
