### ISSUE TITLE
显示用户当前的连接IP数量

### ISSUE THREAD

**Issue by Woophp** [esdeathlove/ss-panel-v3-mod#631]
🙈现在不显示用户连接IP了，为了保护隐私我表示支持，那么能否加一个显示用户当前的连接IP数量。 为防止节点被恶意分享我做了连接数限制 ，看不到连接数不方便排错。

**Comment by gaoyuoppa** [comment]
这个可以的。

**Comment by gaoyuoppa** [comment]
设置套餐的时候可以设置  连接IP数量  就好了。

**Comment by esdeathlove** [comment]
自己看用户列表。
