### ISSUE TITLE
关于TG的问题

### ISSUE THREAD

**Issue by WEGOTOFQSS** [esdeathlove/ss-panel-v3-mod#632]
本人在配置TG机器人的时候遇到了些问题，现在一一列出：
1.ping指令是没有存在的，我添加了之后，仍然是没有出现chatid
2.即使最后我通过api.telegram.org获取到了chatid，但是在执行php xcat setTelegram
的时候出错，下面是出错信息
PHP Fatal error:  Uncaught exception 'TelegramBot\Api\HttpException' with message 'Not Found' in /home/wwwroot/www.paperplane.life/vendor/telegram-bot/api/src/BotApi.php:261
Stack trace:
#0 /home/wwwroot/www.paperplane.life/vendor/telegram-bot/api/src/BotApi.php(241): TelegramBot\Api\BotApi::curlValidate(Resource id #70)
#1 /home/wwwroot/www.paperplane.life/vendor/telegram-bot/api/src/BotApi.php(210): TelegramBot\Api\BotApi->executeCurl(Array)
#2 /home/wwwroot/www.paperplane.life/vendor/telegram-bot/api/src/BotApi.php(415): TelegramBot\Api\BotApi->call('setWebhook', Array)
#3 /home/wwwroot/www.paperplane.life/app/Command/XCat.php(175): TelegramBot\Api\BotApi->setWebhook('http://www.pape...')
#4 /home/wwwroot/www.paperplane.life/app/Command/XCat.php(35): App\Command\XCat->setTelegram()
#5 /home/wwwroot/www.paperplane.life/xcat(11): App\Command\XCat->boot()
#6 {main}
  thrown in /home/wwwroot/www.paperplane.life/vendor/telegram-bot/api/src/BotApi.php on line 261
望dalao帮助！谢谢！

**Comment by esdeathlove** [comment]
你baseurl填了吗

**Comment by WEGOTOFQSS** [comment]
填了

**Comment by imyvm** [comment]
站点启用HTTPS试试

**Comment by WEGOTOFQSS** [comment]
已经启用了，但是还是无济于事

**Comment by esdeathlove** [comment]
baseurl 要填写正确。
