### ISSUE TITLE
建议更换sql文件的名字

### ISSUE THREAD

**Issue by zxzllyj** [esdeathlove/ss-panel-v3-mod#634]
sql文件名字目前是以序号的形式命名的，这样文件辨识度不是很高，建议改下名字，将原本的`glzjin_xx.sql`的命名改为`20170201_fix_alipay_error.sql` 这样附带时间戳和简单描述的文件名，这样一眼就能看出这个sql文件是干啥的。
ps：关于这种sql命名规则，是前公司的开发规范之一，觉得不错，推荐下

**Comment by esdeathlove** [comment]
没必要，更新日志里都写了作用。
