### ISSUE TITLE
晚上好，昨天做的迁移，迁移后邮箱验证功能出现502的错误

### ISSUE THREAD

**Issue by alstarking** [esdeathlove/ss-panel-v3-mod#635]
原来IP被墙，被迫做的迁移，使用的ZIP命令打包的原来魔改，之后到新的VPS上解压。解压后，今天发现邮箱验证码，跟找回密码功能都出现502的错误。是有什么隐藏文件没有被打包过来吗？谢谢了。

**Comment by nailuoGG** [comment]
调试信息呢？

**Comment by lstanyu** [comment]
smtp还是mailgun，smtp要测试mailx是否正常

**Comment by Ehco1996** [comment]
数据库怎么迁移的？

**Comment by ikingi** [comment]
@Ehco1996 导出sql啊。。
