### ISSUE TITLE
请问下，geetest验证码偶尔不显示，需要频繁刷新

### ISSUE THREAD

**Issue by tsongneil** [esdeathlove/ss-panel-v3-mod#636]
geetest.5.10.0.js:1 GET https://api.geetest.com/get.php?gt=9d2847&challen…ath=/static/js/geetest.5.10.0.js&type=slide&callback=geetest_228397 E @ geetest.5.10.0.js:1G @ geetest.5.10.0.js:1c @ geetest.5.10.0.js:1d @ geetest.5.10.0.js:1init @ gt.js:232(anonymous function) @ gt.js:252(anonymous function) @ gt.js:150(anonymous function) @ gt.js:92
geetest.5.10.0.js:1 GeeTest Error: request https://api.geetest.com/get.php?gt=151c875901255d28&challen…uct=float&offline=0&protocol=&path=/static/js/geetest.5.10.0.js&type=slide can not access
geetest.5.10.0.js:2 Uncaught TypeError: c is not a functionpa.Z @ geetest.5.10.0.js:2ra.onError @ geetest.5.10.0.js:2k.v @ geetest.5.10.0.js:1(anonymous function) @ geetest.5.10.0.js:1E.c.onerror @ geetest.5.10.0.js:1

报错如下  返回404错误  刷新又好了  极大概率出现

**Comment by esdeathlove** [comment]
geetest的问题了。
