### ISSUE TITLE
添加管理员命令的问题

### ISSUE THREAD

**Issue by a489651605** [esdeathlove/ss-panel-v3-mod#638]
php xcat createAdmin
添加管理员账号提示这些
PHP Warning:  require(/home/wwwroot/XXX/vendor/autoload.php): failed to open stream: No such file or directory in /home/wwwroot/XXX/bootstrap.php on line 17
PHP Fatal error:  require(): Failed opening required '/home/wwwroot/XXX/vendor/autoload.php' (include_path='.:/usr/local/php/lib/php') in /home/wwwroot/XXX/bootstrap.php on line 17

**Comment by a489651605** [comment]
刚刚翻了一下文件夹，发现没有vendor这个文件夹，网站上也没有

**Comment by esdeathlove** [comment]
自己看安装说明。

**Comment by a489651605** [comment]
有网站链接么？

**Comment by naturalmaster** [comment]
解决了吗，我也遇到了，可以说说怎么解决的么

**Comment by ererermao** [comment]
需要执行：php composer.phar install
