### ISSUE TITLE
管理员后台无法修改会员

### ISSUE THREAD

**Issue by iori8421** [esdeathlove/ss-panel-v3-mod#639]
修改后点击保存 出现一个空白的提示框“知道了”。但是修改没有生效

**Comment by gaoyuoppa** [comment]
如果开了CDN会这样的。

**Comment by esdeathlove** [comment]
自己按照排错方法抓日志。2017年2月8日 上午8:56，iori8421 <notifications@github.com>写道：修改后点击保存 出现一个空白的提示框“知道了”。但是修改没有生效

**Comment by iori8421** [comment]
请问哪里有排错方法说明文件？

**Comment by a489651605** [comment]
esdeathlove
别无视我呢

**Comment by esdeathlove** [comment]
https://github.com/esdeathlove/ss-panel-v3-mod/issues/554

**Comment by iori8421** [comment]
搞定 谢谢
