### ISSUE TITLE
请勿移除底部的staff链接和页面

### ISSUE THREAD

**Issue by esdeathlove** [esdeathlove/ss-panel-v3-mod#64]
在新开 issue 的时候，请一并提交站点地址，这是核验你有没有修改底部的版权信息，移除了 staff 链接和页面的一律不回答。

**Comment by lion1991** [comment]
能设置成私密的issues吗?如果都是公开的话不是暴漏了...

**Comment by glzjin** [comment]
看完我会帮你删除地址的

**Comment by errorlife** [comment]
之前的站都找不到链接的。。这个给我看到了

**Comment by AndrewRussellGarfield** [comment]
谁没事删除这个，
问个问题就要把网站地址给你吗 
那不是活活被d

**Comment by glzjin** [comment]
@AndrewRussellGarfield 你可以自己看看耻辱柱里的网页

**Comment by AndrewRussellGarfield** [comment]
极少数吧 
我刚发了个issue
站还刚建 没安装完

**Comment by AndrewRussellGarfield** [comment]
@glzjin 看了  这种人毕竟少

**Comment by jinshijie** [comment]
我没有删除，尊重作者，感谢作者
