### ISSUE TITLE
请问有没有关于支付系统的使用设置说明

### ISSUE THREAD

**Issue by iori8421** [esdeathlove/ss-panel-v3-mod#644]
充值码怎么销售

**Comment by nickeyfff** [comment]
挂淘宝啊

**Comment by 4D4937** [comment]
config/.config.php.example

> #支付系统
> 
> #取值 paymentwall,zfbjk,spay,none
> $System_Config['payment_system']='none';
> 
> #PaymentWall
> $System_Config['pmw_publickey']='';
> $System_Config['pmw_privatekey']='';
> $System_Config['pmw_widget']='m2_1';
> $System_Config['pmw_height']='350px';
> 
> #alipay,spay
> $System_Config['alipay_id']='';
> $System_Config['alipay_key']='';
> 
> #alipay,zfbjk.com
> $System_Config['zfbjk_pid']='';
> $System_Config['zfbjk_key']='';
> $System_Config['zfbjk_qrcodeurl']='https://www.zhaojin97.cn/wp-content/uploads/2016/01/630c50ab52bc139b2a33af8cc64e47ad2016010111570425541.jpg';
>

**Comment by atrong** [comment]
联系我 教你

**Comment by tyuexingzhe** [comment]
怎么联系，我也有这个问题呢

**Comment by atrong** [comment]
1019898999
