### ISSUE TITLE
关于取消在线用户来源IP显示的想法及建议

### ISSUE THREAD

**Issue by sophauer** [esdeathlove/ss-panel-v3-mod#648]
新版本取消了在线用户来源IP显示功能
从站长的角度看.
保护隐私的想法是好的.仔细想想,来源IP其实并不侵犯用户隐私.撷取用户流量,窥探内容才是.
但是一些用户拿服务器当二次代理干些黑客的活,站长不可能老是去看用户纪录.
请开发大大考虑一下恢复这个功能

**Comment by esdeathlove** [comment]
你抓来源IP也并不能解决这个问题，用好审计规则吧。
