### ISSUE TITLE
ss-panel里的节点测速什么的没用

### ISSUE THREAD

**Issue by vazyine** [esdeathlove/ss-panel-v3-mod#650]
在ss-panel的config里面的测速打开了，后端的测速也打开了，两个时间一样，可是在ss-panel的节点详细信息里一直没有测速的信息

**Comment by vazyine** [comment]
![screenshot_2017-02-11-15-55-18-494_com android chrome](https://cloud.githubusercontent.com/assets/17759624/22852252/ae9e24cc-effd-11e6-9cc4-53765aed5ead.png)
![Uploading Screenshot_2017-02-11-15-56-07-638_com.android.chrome.png…]()

**Comment by vazyine** [comment]
![screenshot_2017-02-11-15-55-18-494_com android chrome](https://cloud.githubusercontent.com/assets/17759624/22852263/f5ca779c-effd-11e6-9344-80930e69cb54.png)



![screenshot_2017-02-11-15-56-07-638_com android chrome](https://cloud.githubusercontent.com/assets/17759624/22852273/400bf862-effe-11e6-987a-5a55dc09c358.png)


图1是我的，图2是一个朋友的，我的那个里面每个节点前面的感叹号好像代表出了什么问题？明明有人连着，他永远不变，也不测速

**Comment by esdeathlove** [comment]
自己查后端日志。2017年2月11日 下午4:00，vazyine <notifications@github.com>写道：
