### ISSUE TITLE
一个关于TCP Fast Open的问题…

### ISSUE THREAD

**Issue by Woophp** [esdeathlove/ss-panel-v3-mod#653]
这几天打开了服务端的TCP Fast Open，之前一直是关闭的，发现了一点小问题，会导致某些应用无法连接，不知道是不是我姿势不对，具体如下：
1、打开TCP Fast Open后发现导致Mobile Legends这个游戏无法连接，关闭tfo后正常。
2、GCM服务无法连接！*#*#426#*#*里面提示not connected，关闭tfo后正常！

其他应用正常连接，没发现哪里不对，不知道是我服务器配置出了问题还是？

服务端使用的是centos 7 64bit 
 3.10内核+锐速、4.9内核+bbr、均有以上问题…
测试手机：一加3T，Android N

**Comment by esdeathlove** [comment]
那就先暂时关掉吧。
