### ISSUE TITLE
关于在线IP取消，能否加个替代功能？

### ISSUE THREAD

**Issue by salty1** [esdeathlove/ss-panel-v3-mod#656]
既然取消了在线ip显示，能否增加一个功能在后台，列出每个用户的当前在线ip数目？
我知道用户列表里有，但是那个表数目太庞大，不太直观，希望考虑增加。
谢谢！

**Comment by esdeathlove** [comment]
你认为怎么才直观呢？2017年2月12日 上午2:50，salty1 <notifications@github.com>写道：既然取消了在线ip显示，能否增加一个功能在后台，列出每个用户的当前在线ip数目？
我知道用户列表里有，但是那个表数目太庞大，不太直观，希望考虑增加。
谢谢！

**Comment by salty1** [comment]
比如说还像在线ip那样，列个表只显示现在在线的，然后在后面显示在线ip数。
如果可以加个输入框，可以输入"显示在线ip大于几的用户"，这样比较方便审查违规合用的用户。
感谢回复

**Comment by gaoyuoppa** [comment]
商品购买的时候能直接设置就好了，自动限制套餐1在线1

**Comment by salty1** [comment]
还是想加入人工可以看的列表,如果可行的话

**Comment by gaoyuoppa** [comment]
有了最好。
