### ISSUE TITLE
V3协议式单端口多用户承载端口无网络

### ISSUE THREAD

**Issue by hezhiguang1991** [esdeathlove/ss-panel-v3-mod#658]
感谢作者的辛苦开发，搭建之后发现使用混淆式单端口模式链接后有网络，但用协议式无网络，不知问题可能出现在哪里，似乎不是个例，两个人单独搭建都有此问题。

谢谢！
我的页面地址：www.uwphome.top

**Comment by Hcax-Y** [comment]
我也是一样

**Comment by esdeathlove** [comment]
协议式请确定你的承载用户协议是否选择为 auth_aes128_*
