### ISSUE TITLE
支付宝spay付款方式

### ISSUE THREAD

**Issue by ymg5206** [esdeathlove/ss-panel-v3-mod#659]
#alipay,spay
$System_Config['alipay_id']='';
$System_Config['alipay_key']='';
这个方式充值应该是最方便的了，话说怎么用啊 个人商户版可以用吗

**Comment by ymg5206** [comment]
新的版本出了几个支付方式，稍微来一点说明吧
万分感谢啊

**Comment by echoowall** [comment]
那是spay的付款方式，非支付宝企业接口。详情自行百度spay。

**Comment by iori8421** [comment]
我也在询问怎么用这个

**Comment by gaoyuoppa** [comment]
但是只支持支付宝。。。。要是集成 passpay 这种多支付方式的接口就好了。
