### ISSUE TITLE
TG机器人故障

### ISSUE THREAD

**Issue by ccwy** [esdeathlove/ss-panel-v3-mod#660]
在面板公告里面加入TG机器人的链接后，更新公告不弹出修改成功的提示，机器人也不在TG群里发公告，但移除公告里面的TG机器人链接后，修改公告就能弹出修改成功的提示，并且机器人也可以正常在群里发公告。
开DEBUG抓包看了下，报错内容如下：
{"error":{"type":"TelegramBot\\Api\\HttpException","message":"Bad Request","file":"\/www\/wwwroot\/ss\/vendor\/telegram-bot\/api\/src\/BotApi.php","line":261}}

**Comment by esdeathlove** [comment]
检查 api token 和 chatid 是否填写正确。
