### ISSUE TITLE
关于自动清理

### ISSUE THREAD

**Issue by moqiaoduo** [esdeathlove/ss-panel-v3-mod#661]
能不能设计一个自动清理旧的流量记录和登录记录的功能呢？

**Comment by HanC890** [comment]
phpmyadmin里面设置定时删除的事件

BEGIN
TRUNCATE table ss_node_online_log;
TRUNCATE table login_ip
TRUNCATE table detect_log;
TRUNCATE table user_traffic_log;
END

**Comment by esdeathlove** [comment]
目前流量记录是会自动清理的。
