### ISSUE TITLE
关于中转的问题

### ISSUE THREAD

**Issue by masonyeung** [esdeathlove/ss-panel-v3-mod#662]
请教赵大和目前维护的大佬：
配置了一条国内中转，中转规则选取的80端口，json里已添加：
![image](https://cloud.githubusercontent.com/assets/23232232/22879247/0906a062-f218-11e6-97fe-3dae403dd7d5.png)
然后调试结果如下：
![image](https://cloud.githubusercontent.com/assets/23232232/22879268/20b6df92-f218-11e6-9b2c-23e540c1bd8d.png)
现在无法正常连接

**Comment by esdeathlove** [comment]
因为你是国内阿里云
