### ISSUE TITLE
节点添加后，可用，但是网站列表显示红色三角

### ISSUE THREAD

**Issue by andy817** [esdeathlove/ss-panel-v3-mod#666]
![node](https://cloud.githubusercontent.com/assets/10892833/22957553/0058301e-f364-11e6-8e63-d3a25111fe4d.jpg)
![ssserver](https://cloud.githubusercontent.com/assets/10892833/22957572/1e741f5e-f364-11e6-90f4-e6a650c6ae19.jpg)这个是log，该后缀为log就行。

![log](https://cloud.githubusercontent.com/assets/10892833/22957626/86a399f6-f364-11e6-8866-9e79d3c41f5f.jpg)

这是我在ssr电脑端打开日志的显示，这里却显示refused。不过发帖时间已经是九点五十了。

**Comment by andy817** [comment]
[ssserver.txt](https://github.com/esdeathlove/ss-panel-v3-mod/files/775816/ssserver.txt)
补发log

**Comment by andy817** [comment]
![default](https://cloud.githubusercontent.com/assets/10892833/22957734/48808c14-f365-11e6-832d-a19449876a0f.jpg)
客户端服务器记录。

**Comment by esdeathlove** [comment]
检查后端填写的节点IP

**Comment by andy817** [comment]
已经ok，，，请closed这个issue
