### ISSUE TITLE
请教，后端更新后，用api对接面板出现的问题。

### ISSUE THREAD

**Issue by masonyeung** [esdeathlove/ss-panel-v3-mod#667]
自查过：
1、面板节点ip填写正确
2、挂的cf的cdn，所以将节点ip列入了cf的白名单，应用于所有网站
3、更新步骤自查N次，无缺少部分

之前用数据库连接无任何问题，现在api对接面板出现mukey对接不上。
日志如下：
![image](https://cloud.githubusercontent.com/assets/23232232/22973979/1c2c9de6-f3bb-11e6-9149-d74d1bdf6b72.png)

**Comment by esdeathlove** [comment]
你在你面板上 wget -O- 你站点地址/mod_mu/nodes/12...就是最后那串GET的 看看执行结果

**Comment by masonyeung** [comment]
![image](https://cloud.githubusercontent.com/assets/23232232/22974250/68493bca-f3bc-11e6-8a70-050889daf71b.png)
感谢回复

**Comment by esdeathlove** [comment]
没东西 ？检查一下 CDN 的设置。

**Comment by masonyeung** [comment]
研究了很久，应该不是cdn的设置问题。现在换回了源站ip，解析完全切换到cloudxns，也还是一样的问题。
附图：
![image](https://cloud.githubusercontent.com/assets/23232232/22977322/20d30138-f3c9-11e6-9645-5a6fe208eb6f.png)
