### ISSUE TITLE
如何数据库里导入新的 sql 文件 sql/glzjin_30.sql , sql/glzjin_31.sql。😓求指导

### ISSUE THREAD

**Issue by tang1989324** [esdeathlove/ss-panel-v3-mod#668]
如何数据库里导入新的 sql 文件 sql/glzjin_30.sql , sql/glzjin_31.sql。😓求指导

**Comment by HanC890** [comment]
如果没改动phpmyadmin名称的话
默认是：你服务器的IP地址/phpmyadmin
进入数据库，然后导入
