### ISSUE TITLE
我以前使用的是 sspanelv3ssr，我可以转到您这个版本吗？

### ISSUE THREAD

**Issue by bao3** [esdeathlove/ss-panel-v3-mod#669]
您好，

我以前使用的是 https://github.com/lan894734188/ss-panel-ssr 这个版本，我现在想转到你这个上来，但发现配置文件变化比较大，更重要的是担心数据库也变化大。
请问我可以直接转过来吗？或者是有没有好的导入导出工具来协助完成这个过程。

感谢啦，您的这个版本提供了太多便利的方式。

**Comment by esdeathlove** [comment]
不好意思，目前没有转换工具，请自行补齐数据库结构。
