### ISSUE TITLE
建议对安装流程进行简化，方便安装与升级。

### ISSUE THREAD

**Issue by wanguo06** [esdeathlove/ss-panel-v3-mod#670]
建议改成网页方式安装，这样有以下好处。
1,网页图形化界面安装，简单、易懂、方便，这样可以降低门槛。
2,无需ssh权限，虚拟空间可以正常安装。（部分兄弟前端放在较稳定的虚拟空间上）

**Comment by gaoyuoppa** [comment]
如果没记错，就是不需要SSH权限的。
