### ISSUE TITLE
按教程安装完以后首页一片空白啊。

### ISSUE THREAD

**Issue by chinawenxu** [esdeathlove/ss-panel-v3-mod#671]
完全按照教程来的，PHP是7，不明白为什么还是一片空白，无法网页。。

**Comment by ikingi** [comment]
不知道。。我安装新版本也是一片空白。。通过FTP上传去年12月份的版本啥问题都没了。。这是一个未解之谜。。

**Comment by chinawenxu** [comment]
是V2版本?

ikingi <notifications@github.com>于2017年2月16日周四 下午7:00写道：

**Comment by ikingi** [comment]
@chinawenxu v3去年 年末的版本。

**Comment by chinawenxu** [comment]
能发一份给我吗？

ikingi <notifications@github.com>于2017年2月16日周四 下午7:52写道：

**Comment by chinawenxu** [comment]
chinawenxu@gmail.com

xuwenxu <chinawenxu@gmail.com>于2017年2月16日周四 下午7:54写道：

**Comment by feileb** [comment]
https://github.com/esdeathlove/ss-panel-v3-mod/issues/603
看看旧分支切换说明，全部搞定就行了

**Comment by chinawenxu** [comment]
我是全新安装的，不是从旧分支过来的也需要这样操作？？

2017-02-17 13:26 GMT+08:00 feileb <notifications@github.com>:

**Comment by esdeathlove** [comment]
不用

**Comment by chinawenxu** [comment]
不知道到底哪一步出错了，无论怎么按教程来，都是一片空白。

**Comment by lydasia** [comment]
什么鬼，我已经安装了两天了，还以为是我的问题。。

**Comment by KiyoshiKwok** [comment]
我也遇到了这个问题，装了很多次都是这样。试过直接不用虚拟主机用nginx的conf设置根路径但是还是不行。不知道新版本有没有解决这个问题。
