### ISSUE TITLE
求助：telegram_bot和邮件部分功能异常

### ISSUE THREAD

**Issue by lenovoy450** [esdeathlove/ss-panel-v3-mod#672]
感谢作者和其他好心人
异常情况及排查如下:
1.telegram里收不到每日网站运行情况:签到人数,流量使用等,能收到其他信息,如节点修改、公告，捐赠，备份完成等提示；
个人排查如下:  
（1）计划任务已开启,root 用户运行；管理员邮箱（mailgun以验证）能收到当日流量使用情况.
（2）root下手动执行 sendDiaryMail，报错如下
Send daily mail to user: 1Send daily mail to user: 4PHP Fatal error:  Uncaught Mailgun\Connection\Exceptions\MissingRequiredParameters: The parameters passed to the API were invalid. Check your inputs! in /home/wwwroot/xxxxxxxx/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php:127
Stack trace:
#0 /home/wwwroot/xxxxxxxx/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(90): Mailgun\Connection\RestClient->responseHandler(Object(Guzzle\Http\Message\Response))
#1 /home/wwwroot/xxxxxxxx/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(80): Mailgun\Connection\RestClient->post('https://api.mai...', Array, Array)
#2 /home/wwwroot/xxxxxxxx/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(36): Mailgun\Mailgun->post('https://api.mai...', Array, Array)
#3 /home/wwwroot/xxxxxxxx/app/Services/Mail/Mailgun.php(42): Mailgun\Mailgun->sendMessage('https://api.mai...', Array, Array)
#4 /home/wwwroot/xxxxxxxx/app/Services/Mail.php(68): App\Services\Mail\Mailgun->send('xxxxxx@qq.co...', '\xE5\x96\xB5~-\ in /home/wwwroot/xxxxxxxx/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php on line 127

其中#4里xxxxx@qq.com为一正常使用的普通用户的邮箱，未进行mailgun的验证

2.邮件风暴, 用户等级过期和面板更新时出现 
个人排查如下:
（1）重新安装新面板并执行以下命令
chown -R root:root *
chmod -R 755 *
chown -R www:www storage
chmod 777 storage
（2）切换到www用户下，能在storage下新建，删除文件
（3）root或www用户手动执行checkjob提示如下
PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /home/wwwroot/xxxxx/app/Services/Mail.php:68
Stack trace:
#0 /home/wwwroot/xxxxx/app/Command/Job.php(706): App\Services\Mail::send('xxxxx@qq.co...', '\xE5\x96\xB5~-\xE6\x82\xA8\xE7\x9A\x84\xE7\x94\xA8\xE6...', 'news/warn.tpl', Array, Array)
#1 /home/wwwroot/xxxxx/app/Command/XCat.php(64): App\Command\Job::CheckJob()
#2 /home/wwwroot/xxxxx/xcat(11): App\Command\XCat->boot()
#3 {main}
  thrown in /home/wwwroot/xxxxx/app/Services/Mail.php on line 68

其中#0里，xxxxx@qq.com为等级到期用户邮箱。

再次感谢。

**Comment by esdeathlove** [comment]
1.你 mailgun api 没填对。
2.你的设置有错，mailgun_driver
