### ISSUE TITLE
在线人数节点统计一直是0

### ISSUE THREAD

**Issue by tang1989324** [esdeathlove/ss-panel-v3-mod#676]
最新版的http api？然后在线一直是0

**Comment by esdeathlove** [comment]
你连接上节点了吗？后端日志有异常吗？

**Comment by tang1989324** [comment]
@esdeathlove 显示连上了 WEBAPI_URL = 'https://zhaoj.in'

WEBAPI_TOKEN = 'glzjin'难道这里错了？ token本来空白的 我设置了下  网址我是http://

**Comment by esdeathlove** [comment]
你要改成自己的。

**Comment by tang1989324** [comment]
我知道 已经改成自己的了 但是人数一直0

**Comment by esdeathlove** [comment]
那就看看自己是否连上了，后端的日志有什么错误。
