### ISSUE TITLE
用户节点列表页面报错

### ISSUE THREAD

**Issue by shuangzhijinghua** [esdeathlove/ss-panel-v3-mod#678]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:2017/2/18通过git pull更新至最新版本

问题发生时所进行的操作：通过用户主页菜单点击节点列表

问题所造成的影响：无法查看节点，可以通过一键导入到客户端中

调试日志（按照上面的调试方法得到）：
![image](https://cloud.githubusercontent.com/assets/7972337/23079876/b2f38170-f589-11e6-985a-872a4122e90f.png)

**Comment by esdeathlove** [comment]
明白了，感谢您的反馈，这个问题会在下个版本进行修复，在此之前您可以暂时把 debug 关掉。
