### ISSUE TITLE
更新最新版出现500还有几个错误，有时间麻烦解答，感谢！辛苦了！

### ISSUE THREAD

**Issue by ztutu** [esdeathlove/ss-panel-v3-mod#679]
网站 http://s.ztutu.com
程序类型（前端/后端）：
最新版

程序版本（前端发版本号，后端发 git log 所看到的 commit id）: 

commit 37d3bf771ce15556037f18bd4e431ff0f9c194dc
Author: glzjin <glzjin@zhaojin97.cn>
Date:   Fri Feb 17 17:24:26 2017 +0800

问题发生时所进行的操作：
 更新您最新的版本出现问题。
 按照这个连接的操作的
https://github.com/esdeathlove/ss-panel-v3-mod/issues/603

问题所造成的影响：进后台500，debug已经打开。s.ztutu.com

调试日志（按照上面的调试方法得到）：

执行到这一步有问题，我忽略了不知道怎么解决，貌似说依赖有问题
（3.切换完成之后，就要下载依赖。）
  (php composer.phar install）
报错代码：
root@zhanggaoxiang:/usr/share/nginx/ssr# php composer.phar install
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Generating autoload files
root@zhanggaoxiang:/usr/share/nginx/ssr# chown -R root:root *
root@zhanggaoxiang:/usr/share/nginx/ssr# chmod -R 755 *
root@zhanggaoxiang:/usr/share/nginx/ssr# chown -R www:www storage
chown: invalid user: `www:www'
root@zhanggaoxiang:/usr/share/nginx/ssr# 
执行下一步导入sql，导入glzjin_30.sql提升两个OK。导入glzjin_31.sql报错如下：

mysql> source /usr/share/nginx/ssr/sql/glzjin_31.sql;
ERROR 1146 (42S02): Table 'ssr.paylist' doesn't exist
mysql> 
忽略执行下一步php -n xcat initdownload 报错如下：
root@zhanggaoxiang:/usr/share/nginx/ssr# php -n xcat initdownload

Fatal error: Class 'PDO' not found in /usr/share/nginx/ssr/vendor/illuminate/database/Capsule/Manager.php on line 49

**Comment by esdeathlove** [comment]
请严格按照升级步骤一个个版本进行阶梯升级，中间要进行的操作一步都不能少，关于你的问题在说明里都有解答。

**Comment by ztutu** [comment]
大神我看了说明啊！表里面没有paylist还是导入不成功，我看sql里面有个paylist.sql导入了还是不行错误500

还有一个php 安装依赖错误。
 php composer.phar install
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.


2.导入 glzjin_31.sql

如果导入出错，先把 paylist 表给删了（如果有），然后导入这个来代替 glzjin_31.sql

https://github.com/esdeathlove/ss-panel-v3-mod/raw/new_master/sql/paylist.sql

**Comment by ztutu** [comment]
@esdeathlove 求给个提示，是我依赖没安装好，还是数据库导入缺少表字段。我重新弄。

**Comment by esdeathlove** [comment]
请将新的debug得到的信息发出来。

**Comment by ztutu** [comment]
自己研究了以下，应该是数据库没弄好，glzjin_31.sql，导入失败换成。glzjin_all.sql
如果数据库有问题，就无法执行php xcat *等命令。
现在好了，谢谢

mysql> source /usr/share/nginx/ssr/sql/glzjin_all.sql;
Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1068 (42000): Multiple primary key defined
ERROR 1068 (42000): Multiple primary key defined
ERROR 1068 (42000): Multiple primary key defined
ERROR 1068 (42000): Multiple primary key defined
ERROR 1068 (42000): Multiple primary key defined
ERROR 1068 (42000): Multiple primary key defined
ERROR 1068 (42000): Multiple primary key defined
ERROR 1068 (42000): Multiple primary key defined
ERROR 1068 (42000): Multiple primary key defined
ERROR 1068 (42000): Multiple primary key defined
ERROR 1068 (42000): Multiple primary key defined
ERROR 1068 (42000): Multiple primary key defined
ERROR 1068 (42000): Multiple primary key defined
ERROR 1068 (42000): Multiple primary key defined
ERROR 1068 (42000): Multiple primary key defined
ERROR 1068 (42000): Multiple primary key defined
ERROR 1068 (42000): Multiple primary key defined
Query OK, 0 rows affected (0.01 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.01 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

ERROR 1060 (42S21): Duplicate column name 'node_group'
ERROR 1060 (42S21): Duplicate column name 'node_group'
ERROR 1050 (42S01): Table 'payback' already exists
ERROR 1050 (42S01): Table 'shop' already exists
ERROR 1050 (42S01): Table 'coupon' already exists
ERROR 1050 (42S01): Table 'bought' already exists
ERROR 1060 (42S21): Duplicate column name 'coupon'
Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

ERROR 1060 (42S21): Duplicate column name 'markdown'
Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

ERROR 1050 (42S01): Table 'ticket' already exists
ERROR 1060 (42S21): Duplicate column name 'status'
ERROR 1060 (42S21): Duplicate column name 'status'
ERROR 1060 (42S21): Duplicate column name 'auto_reset_day'
ERROR 1060 (42S21): Duplicate column name 'auto_reset_bandwidth'
Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

ERROR 1050 (42S01): Table 'auto' already exists
ERROR 1060 (42S21): Duplicate column name 'sign'
Query OK, 31 rows affected (0.01 sec)
Records: 31  Duplicates: 0  Warnings: 0

ERROR 1060 (42S21): Duplicate column name 'custom_rss'
ERROR 1060 (42S21): Duplicate column name 'protocol'
ERROR 1060 (42S21): Duplicate column name 'forbidden_ip'
ERROR 1050 (42S01): Table 'disconnect_ip' already exists
Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 31 rows affected (0.01 sec)
Records: 31  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

ERROR 1050 (42S01): Table 'email_verify' already exists
ERROR 1060 (42S21): Duplicate column name 'is_hide'
ERROR 1050 (42S01): Table 'detect_list' already exists
ERROR 1050 (42S01): Table 'detect_log' already exists
ERROR 1060 (42S21): Duplicate column name 'type'
ERROR 1060 (42S21): Duplicate column name 'node_id'
ERROR 1060 (42S21): Duplicate column name 'is_multi_user'
ERROR 1060 (42S21): Duplicate column name 'mu_only'
Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.02 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

ERROR 1050 (42S01): Table 'telegram_session' already exists
ERROR 1060 (42S21): Duplicate column name 'telegram_id'
Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.01 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> exit
Bye
root@zhanggaoxiang:/usr/share/nginx/ssr# php xcat initdownload
Cloning into '/usr/share/nginx/ssr/public/ssr-download'...
remote: Counting objects: 67, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 67 (delta 0), reused 0 (delta 0), pack-reused 63
Unpacking objects: 100% (67/67), done.
0root@zhanggaoxiang:/usr/share/nginx/ssr#
