### ISSUE TITLE
建议在用户面板流量记录页面添加表格形式的详细信息

### ISSUE THREAD

**Issue by sjtuross** [esdeathlove/ss-panel-v3-mod#680]
类似管理面板流量使用记录的表格是否能添加到用户面板并显示IP，用来给用户自查，比如在哪些地点使用了什么节点，避免被盗用

**Comment by esdeathlove** [comment]
不好意思，并不会记录原始IP了。

**Comment by sjtuross** [comment]
就是觉得现在那个图表实际用处不大，主要目的是希望用户有办法自查
