### ISSUE TITLE
关于从panel的用户同步到radius用户的问题

### ISSUE THREAD

**Issue by Yiipanny** [esdeathlove/ss-panel-v3-mod#682]
程序类型（前端/后端）： 前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）: 37d3bf771ce15556037f18bd4e431ff0f9c194dc

问题发生时所进行的操作：增加用户，修改用户密码

问题所造成的影响：

1. radius/radcheck表里的用户名是邮箱去掉各种符号，比如用户邮箱是admin@123.com，radius生成的账号就是admin123com，能不能完整的用邮箱，不去掉@和其他符号，经测试，完整带符号的用户名radius是可以认证的，还是因为第2条结尾所说的bug；

2.然后在前端修改密码，就直接在radius/radcheck表里生成了新的记录，旧的记录并没有删掉，比如，  radius/radcheck里的记录为 admin123com/123 ，然后在panel里修改密码为 1234，radius/radcheck表里直接插入了新纪录admin123com/1234的记录，旧的admin123com/123还存在，不知道是不是有意为之还是因为第1条所说的bug，同步用户名时查询不到完整的邮箱而认为记录不存在，才插入了新的记录。

3.针对第2条，我有个提议为：ss-panel/user表的id和radius/radcheck表的唯一id一一对应，修改了密码直接以唯一ID修改，同时检查用户名和密码是否为最新。

调试日志（按照上面的调试方法得到）：~

就这样~

**Comment by esdeathlove** [comment]
1.在某些情况下用户名不能含有符号，比如 SSH。
2. 是个 BUG，已经修复，谢谢。
