### ISSUE TITLE
关于一些面板界面操作细节的建议

### ISSUE THREAD

**Issue by WayChan** [esdeathlove/ss-panel-v3-mod#685]
个别删除、编辑操作建议确认后刷新当前页面。
可在tpl使用以下代码实现。

$("#result_ok").unbind().bind("click",function(){
     window.setTimeout(window.location.reload(), {$config['jump_delay']});
})

这样可以减少手动刷新次数

**Comment by esdeathlove** [comment]
没必要刷新，已经会在表格里删除相应表项。
