### ISSUE TITLE
商品 自动续费 叠加 的问题和建议

### ISSUE THREAD

**Issue by wxlost** [esdeathlove/ss-panel-v3-mod#687]
商品设置了自动续费.有效期(30天).
购买后.自动续期时间是当前时间+30
再次购买,自动续期时间还是当前时间+30

这.......前台购买时明明写的是到期后自动续费.所以应该是

购买时,开启自动续费,然后 自动续费时间=等级到期时间,并且同一用户重复购买的话只生效最新的一个,旧的自动退订

希望能修复下...

**Comment by wxliuxh** [comment]
所以购买了2个一样的30天套餐.数据库里显示的到期续费时间不是30+30,而是30

**Comment by wxliuxh** [comment]
也就是说我是1月份购买了2个30天套餐.那么应该是到了3个月才自动续费30天.
可现在是到了2个月就续费了.还续费了2次.

**Comment by ikingi** [comment]
我也是。比如有效期30天，等级有效期重复购买会往上叠加而不是重置。。求重复购买重置等级有效期，而不是往上叠加。。
