### ISSUE TITLE
dailyjob报错Prs: command not found……

### ISSUE THREAD

**Issue by Woophp** [esdeathlove/ss-panel-v3-mod#692]
程序类型（前端）：

程序版本（20170220）:
系统版本  centos 7
php版本  PHP 5.6.27 (cli)
问题发生时所进行的操作： php -n xcat dailyjob

问题所造成的影响：收到的附件数据库为空

调试日志（按照上面的调试方法得到）：

sh: Prs: command not found
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Usage: mysqldump [OPTIONS] database [tables]
OR     mysqldump [OPTIONS] --databases [OPTIONS] DB1 [DB2 DB3...]
OR     mysqldump [OPTIONS] --all-databases [OPTIONS]
For more options, use mysqldump --help
sh: Prs: command not found
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Usage: mysqldump [OPTIONS] database [tables]
OR     mysqldump [OPTIONS] --databases [OPTIONS] DB1 [DB2 DB3...]
OR     mysqldump [OPTIONS] --all-databases [OPTIONS]
For more options, use mysqldump --help
sh: Prs: command not found
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Usage: mysqldump [OPTIONS] database [tables]
OR     mysqldump [OPTIONS] --databases [OPTIONS] DB1 [DB2 DB3...]
OR     mysqldump [OPTIONS] --all-databases [OPTIONS]
For more options, use mysqldump --help
0  adding: tmp/ssmodbackup/configbak.php (deflated 63%)
  adding: tmp/ssmodbackup/mod.sql (stored 0%)
  adding: tmp/ssmodbackup/wecenter.sql (stored 0%)
Already up-to-date.

**Comment by Woophp** [comment]
@esdeathlove  有空帮忙看一下，谢谢。

**Comment by esdeathlove** [comment]
用 


mysqldump --user=数据库用户名 --password=数据库密码 --host=数据库地址 -P 数据库端口 数据库名称 announcement auto blockip bought code coupon disconnect_ip link login_ip payback radius_ban shop speedtest ss_invite_code ss_node ss_password_reset ticket unblockip user user_token email_verify detect_list relay> /tmp/ssmodbackup/mod.sql

测试

**Comment by Woophp** [comment]
@esdeathlove 执行后如下提示：
[1] 10844
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Usage: mysqldump [OPTIONS] database [tables]
OR     mysqldump [OPTIONS] --databases [OPTIONS] DB1 [DB2 DB3...]
OR     mysqldump [OPTIONS] --all-databases [OPTIONS]
For more options, use mysqldump --help
-bash: /tmp/ssmodbackup/mod.sql: No such file or directory
[1]+  Exit 1                  mysqldump --user=***** --password=A@Mkc8Th

password=后面的密码不对，少了一段，实际上我的密码是这样的：“A@Mkc8Th&*************”，“&”这个符号后面的都没有了。。。会不会是因为密码中有这个符号的问题？
一开始是可以备份的，后来发现备份文件数据库是空文件的时候已经更新过很多版本了。

**Comment by esdeathlove** [comment]
对，就是那个符号 改改吧
