### ISSUE TITLE
关于面板登录过期机制的问题

### ISSUE THREAD

**Issue by BROBIRD** [esdeathlove/ss-panel-v3-mod#694]
代发一个issue，请您看一下是否有采纳价值

![img_20170223_161240](https://cloud.githubusercontent.com/assets/7692707/23250431/bba9bb20-f96e-11e6-80b9-d2f32d8730cc.png)

![img_20170223_161343](https://cloud.githubusercontent.com/assets/7692707/23250378/834655d6-f96e-11e6-88a4-7c82a631ed88.png)

**Comment by esdeathlove** [comment]
你可以把IP绑定关掉。
