### ISSUE TITLE
2017年2月19日版本的问题

### ISSUE THREAD

**Issue by WEGOTOFQSS** [esdeathlove/ss-panel-v3-mod#698]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:2017年2月19日

问题发生时所进行的操作：打开管理面版，使用全新的表格组件的页面

问题所造成的影响：使用全新的表格组件的页面（如工单管理等）全部无法使用（用户列表暂未被影响）

调试日志（按照上面的调试方法得到）：无出现调试日志（在已经打开调试开关的情况下）
F12提示：500

以下的是打开上述被影响的页面时的提示对话框：

![qq 20170221213842](https://cloud.githubusercontent.com/assets/16714790/23337677/c19171ee-fc30-11e6-955b-836b7277b294.png)

此错误影响严重，请及时处理，谢谢！

**Comment by esdeathlove** [comment]
1.发问题的时候请按照调试步骤带上调试信息。
2.其实你按照调试步骤抓了错误信息之后就会知道了，很大概率上是因为你缺少了依赖，而这个原因是因为你没看更新日志按照升级步骤执行 php composer.phar install
