### ISSUE TITLE
节点图标状态的问题

### ISSUE THREAD

**Issue by trumphi** [esdeathlove/ss-panel-v3-mod#700]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:2017年2月19日

问题发生时所进行的操作：打开管理面版，用户节点列表中节点图标
问题所造成的影响：没有影响就是感觉好象哪里设置不对劲

调试日志（按照上面的调试方法得到）：无出现调试日志

前端控制面板中的节点图标是黄色的（如图），当然节点使用正常，但总感觉这里应该是绿色的，不知哪里调错了呢？

<img src="https://raw.githubusercontent.com/trumphi/tupian/master/20170227102010.png"/>

**Comment by moqiaoduo** [comment]
1.确认node id是否填写正确
2.确认防火墙是否配置好

**Comment by trumphi** [comment]
2项设置都没问题

**Comment by moqiaoduo** [comment]
继续检查：前端后端是否最新版，是否缺失配置项。具体参考example。

**Comment by lstanyu** [comment]
管理面板  节点列表 查看你新增的列表id是多少，，记住，，修改shadowsocks/userapiconfig.py 里面的# Config
NODE_ID = 3（前面要你记住的），，即可。。。。

**Comment by trumphi** [comment]
YES!
