### ISSUE TITLE
关于用户列表内，今日流量统计问题。

### ISSUE THREAD

**Issue by andy817** [esdeathlove/ss-panel-v3-mod#701]
今日流量有时候不刷新。还是显示之前的流量，这个是bug吗？有没有办法？我的网站使用一段时间后，修改公告后，点击  修改，现在也没有弹出修改成功提示，不过实际上可以修改，不影响使用。就是问问。

谢谢！

**Comment by jeanim** [comment]
同此情况

**Comment by andy817** [comment]
@jeanim 有解决吗？
