### ISSUE TITLE
设置注册时发送给邮件的验证码

### ISSUE THREAD

**Issue by trumphi** [esdeathlove/ss-panel-v3-mod#702]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:2017年3月1日

问题发生时所进行的操作：打开配置文件.config.php
问题所造成的影响：不能给邮箱发送注册验证码

调试日志（按照上面的调试方法得到）：无出现调试日志

后台中启用了
#是否启用邮箱验证码
$System_Config['enable_email_verify']='true'；
并且发送邮箱设置为如下：
# smtp
$System_Config['smtp_host'] = 'smtp.XXX1.com';
$System_Config['smtp_username'] = 'myname@XXX1.com';
$System_Config['smtp_port'] = '25';
$System_Config['smtp_name'] = 'myname';
$System_Config['smtp_sender'] = 'myname';
$System_Config['smtp_passsword'] = 'XXXXXX';
$System_Config['smtp_ssl'] = 'true';

不能出送！并且弹出的提示对话框中也没有文字说明
如图
<img src="https://raw.githubusercontent.com/trumphi/tupian/master/33333.png"/>

**Comment by lstanyu** [comment]
$System_Config['smtp_ssl'] = 'true';那么$System_Config['smtp_port'] = '25';25就要改成465

**Comment by trumphi** [comment]
YES！thanks!
