### ISSUE TITLE
debug 已打开，仍为500，无任何输出

### ISSUE THREAD

**Issue by mpb159753** [esdeathlove/ss-panel-v3-mod#705]
程序类型 ：前端

程序版本: 最新

问题发生时所进行的操作：按照安装说明安装完成后进入主页

问题所造成的影响：主页报错500

调试日志（按照上面的调试方法得到）：
已打开debug开关，$System_Config['debug'] = 'true'; 但仍无任何输出
已尝试操作：多次重装，更换 php 版本，重新安装依赖，安装依赖时发现报错需要打开两个 php 函数，重装系统后打开函数再次安装无报错，但就是 500 进不去...

**Comment by mpb159753** [comment]
![qq 20170228112409](https://cloud.githubusercontent.com/assets/9007876/23390442/0457dd96-fda9-11e6-8c18-b32c56c156cd.png)
![qq 20170228112429](https://cloud.githubusercontent.com/assets/9007876/23390443/076c3644-fda9-11e6-8a02-392993341fd1.png)

**Comment by esdeathlove** [comment]
开PHP的报错模式。

**Comment by GBigCousin** [comment]
我记得有个密码，注释是如果是旧版升级过来的，请留空

**Comment by mpb159753** [comment]
开启后错误信息提示为

> Warning: require(): open_basedir restriction in effect. File(/home/wwwroot/ss.-panel/bootstrap.php) is not within the allowed path(s): (/home/wwwroot/ss.-panel/public/:/tmp/:/proc/) in /home/wwwroot/ss.-panel/public/index.php on line 7
> 
> Warning: require(/home/wwwroot/ss.-panel/bootstrap.php): failed to open stream: Operation not permitted in /home/wwwroot/ss.-panel/public/index.php on line 7
> 
> Fatal error: require(): Failed opening required '/home/wwwroot/ss.-panel/public/../bootstrap.php' (include_path='.:/usr/local/php/lib/php') in /home/wwwroot/ss.-panel/public/index.php on line 7

自己谷歌了下似乎是 open_basedir 的问题，打开 php.ini 看了下原本是被注释掉的啊， 将行首 “；” 去掉后，分别将 open_basedir 设置为 “none",  "/home/wwwroot/" 仍然报错....
翻了几页谷歌都没找到解决方法......
![qq 20170228112429](https://cloud.githubusercontent.com/assets/9007876/23513544/5e3caa06-ff9f-11e6-9837-cef654246d99.png)

**Comment by esdeathlove** [comment]
自己看你用的环境 opendir 怎么设置。

**Comment by mpb159753** [comment]
彻底关闭 opendir  后可以使用了~感谢~
弱弱问一句，会不会不安全啊？

**Comment by Tomzuo** [comment]
相同的问题，怎么解决

**Comment by lithromantic** [comment]
同求怎么解决

**Comment by Tomzuo** [comment]
@mpb159753 @esdeathlove 怎么解决啊

**Comment by mpb159753** [comment]
搜索下自己所用 LNMP 环境的  opendir 关闭方法，然后关闭就好

**Comment by ererermao** [comment]
@mpb159753  能否给个关键字，搜索"LNMP opendir " " opendir 关闭" 无果

**Comment by Tomzuo** [comment]
LNMP 1.4上如果不想用防跨目录还需要将 /usr/local/nginx/conf/fastcgi.conf 里面的fastcgi_param PHP_ADMIN_VALUE "open_basedir=$document_root/:/tmp/:/proc/"; 删除，需要重启nginx。

**Comment by ererermao** [comment]
@Tomzuo 额，好像把这段删除了后，就直接白屏了。php、niginx都无错误日志提示

**Comment by Tomzuo** [comment]
重启了吗

**Comment by ererermao** [comment]
@Tomzuo  重启了，不过我没有找到你的原句，我的是`fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;`

**Comment by Tomzuo** [comment]
这句不对  这句我的也有

**Comment by Tomzuo** [comment]
搜索我给的那句   没有吗

**Comment by ererermao** [comment]
@Tomzuo  没有，那就算了吧。我没有500 这个问题，我只是看到一个相关的问问你，谢谢

**Comment by Tomzuo** [comment]
打开php的错误输出和sspanel的debug

**Comment by ererermao** [comment]
@Tomzuo 我觉得我现在基本上定位问题了，就是php的一些包没有安装好，。
问题在这步：`php composer.phar install`

**Comment by mpb159753** [comment]
@ererermao 包的问题的话我用的是lnmp 1.4 ，在安装之前要先解除两个个函数的禁用，具体忘记是哪个了...只能是重新安装时提示哪个不对，记录下来，然后再重新安装（不能直接重新运行`php composer.phar install`，而是要在新目录重头安装），这时还会提示另一个，记录下来，解除这俩函数的禁用，再安装就好。如果包安装好还不行，参考[这里](https://lnmp.org/faq/lnmp-vhost-add-howto.html)接触防跨目录就行~
你搜时候少考虑一步，我刚开始找出 open_basedir  问题后，不知怎么解决，多搜了下这个功能是用来防跨目录的，然后搜 "Lnmp 跨目录“ 就找到结果了~

**Comment by ererermao** [comment]
@mpb159753  谢谢耐心解答，在`php.ini`添加了，跨目录后还是不行。下面是我问题的详细内容
#789

**Comment by silentstage** [comment]
@ererermao 我也刚碰这问题，注释掉/usr/local/nginx/conf/fastcgi.conf里的最后一句fastcgi_param PHP_ADMIN_VALUE "open_basedir=$document_root/:/tmp/:/proc/，然后重启nginx就好了

**Comment by ererermao** [comment]
@silentstage  你好，我的`fastcgi.conf`在`/etc/nginx/fastcgi.conf`下面的（只有这一个）。里面没有`fastcgi_param PHP_ADMIN_VALUE`。我是`nginx version: nginx/1.10.2` 使用`yum`安装的

**Comment by silentstage** [comment]
@ererermao 那就不清楚了，我是LNMP1.4包安装的，刚刚弄好，php.ini里面那段注释我没有去掉，就删了fastcgi.conf就解决了

**Comment by ererermao** [comment]
@silentstage  好想不行，我在试试别的。非常感谢

**Comment by yienzhu** [comment]
@silentstage 感谢，问题解决了。

**Comment by xiaoshaoyc** [comment]
lnmp1.4有防跨目录配置文件移除脚本，在安装包目录里tools目录下运行 ./remove_open_basedir_restriction.sh
