### ISSUE TITLE
中转节点流量上限未按时重置

### ISSUE THREAD

**Issue by sjtuross** [esdeathlove/ss-panel-v3-mod#708]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）：20170228

问题发生时所进行的操作：设置了中转节点的流量上限，清空日为每月1号

问题所造成的影响：观察了2个月，中转节点的流量上限并未在每月1号清空

调试日志（按照上面的调试方法得到）：计划任务都正常，没发现任何错误日志

**Comment by ikingi** [comment]
![1](https://cloud.githubusercontent.com/assets/25564853/23454638/dbefafa0-fea7-11e6-8831-e80c23a371fd.jpg)
我发现一个问题。。比如29号，或者30号，2月份没有29，难道就不重置了吗？
如果填写31号重置，2、4、6、9、11没有31号会出现什么情况？不重置吗？

**Comment by esdeathlove** [comment]
更新即可。
