### ISSUE TITLE
更新到d23d9f1后 管理面板-用户列表出现问题.

### ISSUE THREAD

**Issue by Kosonlee** [esdeathlove/ss-panel-v3-mod#712]
提示如下
![image](https://cloud.githubusercontent.com/assets/17353789/23576265/cde15db0-00db-11e7-8c45-a97394203c16.png)

**Comment by esdeathlove** [comment]
请按照格式发issue。

**Comment by Kosonlee** [comment]
程序类型:前端

程序版本:08f964c57c6b4e485d51fea7e5bb663862a88bb1(纯手动更新,没有git pull,每个版本都会更新)

问题发生时所进行的操作：点击管理面包,用户列表提示空白

问题所造成的影响：用户列表空白

调试日志：
![image](https://cloud.githubusercontent.com/assets/17353789/23576312/254b5320-00dd-11e7-93e5-539f380062ee.png)
