### ISSUE TITLE
今日流量统计不重置，一直叠加

### ISSUE THREAD

**Issue by andy817** [esdeathlove/ss-panel-v3-mod#713]
程序类型（前端）：前段

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:20170117版

问题发生时所进行的操作：无操作，自己发生的

问题所造成的影响：今日流量不重置，就是一直叠加的意思

调试日志（按照上面的调试方法得到）：日志见附件，删除后缀.zip即可

谢谢配合！
[www.netbridge.ml.log.zip](https://github.com/esdeathlove/ss-panel-v3-mod/files/819097/www.netbridge.ml.log.zip)

**Comment by andy817** [comment]
添加一下描述，希望能够帮助解决。
流量不充值，但是消耗流量会继续叠加，就是基本上只显示以用多少，今日流量跟已经多少是一样的，不会自动重置为0.

**Comment by andy817** [comment]
额。。。没有办法解决吗

**Comment by esdeathlove** [comment]
检查计划任务是否正常运行。

**Comment by andy817** [comment]
[crond log.txt](https://github.com/esdeathlove/ss-panel-v3-mod/files/823183/crond.log.txt)

crond的日志，改后缀为.zip解压后，就是几个log。我没有发现什么，，不过有一个  Job `cron.daily' terminated，，不知道是不是这个原因，请问怎么解决。重启可以解决吗？

**Comment by leetianyu** [comment]
同遇到这个问题

**Comment by Gonw** [comment]
检查crond任务执行情况，如果是ubuntu，去掉命令里面的-n

**Comment by andy817** [comment]
@Gonw 我是centos 6.5的，不是unbuntu

**Comment by andy817** [comment]
30 22 * * * php /home/wwwroot/ss.panel/xcat sendDiaryMail
*/1 * * * * php /home/wwwroot/ss.panel/xcat synclogin
*/1 * * * * php /home/wwwroot/ss.panel/xcat syncvpn
0 0 * * * php -n /home/wwwroot/ss.panel/xcat dailyjob
*/1 * * * * php /home/wwwroot/ss.panel/xcat checkjob    
*/1 * * * * php -n /home/wwwroot/ss.panel/xcat syncnas

请问哪一个是执行每日流量归零的程序？

**Comment by andy817** [comment]
30 22 * * * php /home/wwwroot/www.netbridge.ml/xcat sendDiaryMail
*/1 * * * * php /home/wwwroot/www.netbridge.ml/xcat synclogin
*/1 * * * * php /home/wwwroot/www.netbridge.ml/xcat syncvpn
0 0 * * * php -n /home/wwwroot/www.netbridge.ml/xcat dailyjob
*/1 * * * * php /home/wwwroot/www.netbridge.ml/xcat checkjob    
*/1 * * * * php -n /home/wwwroot/www.netbridge.ml/xcat syncnas
这是我的 之前发错了

**Comment by tinchbear** [comment]
相同问题，下面是我手动执行php xcat dailyjob的结果:

PHP Fatal error:  Uncaught TelegramBot\Api\HttpException: Bad Request in /usr/share/websites/ss-panel/vendor/telegram-bot/api/src/BotApi.php:261
Stack trace:
#0 /usr/share/websites/ss-panel/vendor/telegram-bot/api/src/BotApi.php(241): Telegr
mBot\Api\BotApi::curlValidate(Resource id #94)
#1 /usr/share/websites/ss-panel/vendor/telegram-bot/api/src/BotApi.php(210): Telegr
mBot\Api\BotApi->executeCurl(Array)
#2 /usr/share/websites/ss-panel/vendor/telegram-bot/api/src/BotApi.php(316): Telegr
mBot\Api\BotApi->call('sendMessage', Array)
#3 /usr/share/websites/ss-panel/app/Utils/Telegram.php(18): TelegramBot\Api\BotApi-
sendMessage('-168128654', '\xE5\xA7\x90\xE5\xA7\x90\xE5\xA7\x90\xE5\xA7\x90\xEF\xB
\x8C...')
#4 /usr/share/websites/ss-panel/app/Command/Job.php(142): App\Utils\Telegram::Send(
\xE5\xA7\x90\xE5\xA7\x90\xE5\xA7\x90\xE5\xA7\x90\xEF\xBC\x8C...')
#5 /usr/share/websites/ss-panel/app/Command/XCat.php(62): App\Command\Job::DailyJob
)
#6 /usr/share/websites/ss-panel/xcat(11): App\Command\XCat->boot()
#7 {main}
  thrown in /usr/share/websites/ss-panel/vendor/telegram-bot/api/src/BotApi.php on
ine 261

手动执行后流量依旧没有重置，cron及Telegram机器人均正常运作，PHP版本7.0.17

**Comment by tinchbear** [comment]
附加信息：
程序版本：20170325
服务器系统：Fedora 25 Server
