### ISSUE TITLE
phpmyadmin打不开了

### ISSUE THREAD

**Issue by Huanhoo** [esdeathlove/ss-panel-v3-mod#719]
我在配置阶段输入ip/phpmyadmin可以正常打开。

现在所有的都配好了再输入ip/phpmyadmin就直接跳转到404了，请问这该如何解决？

**Comment by zhlzhl123** [comment]
可以把phpmyadmin放进public。。。

**Comment by saladinxp** [comment]
如果你创建了新的虚拟主机捆绑域名，将魔改sspanel丢进去 捆绑的域名目录，那么用ip+phpmyadmin 还是可以用的。

**Comment by A1exLiu** [comment]
把`/phpmyadmin`目录整个放进`/home/wwwroot/站点目录/public`文件夹下，可以直接用域名访问

**Comment by Huanhoo** [comment]
确实可以了，谢谢啊！
