### ISSUE TITLE
购买等级不按当前日期增加时间

### ISSUE THREAD

**Issue by DreamChanSS** [esdeathlove/ss-panel-v3-mod#722]
打个比方，商品为:等级升为2 等级有效期30天，帐号等级过期时间为3月3日，购买后等级过期时间变成4月3日，而不是按当前日期（3月10日）增加为4月10日。
希望可以修改这一问题。

**Comment by afeng1991** [comment]
每个月都是30天吗？

**Comment by DreamChanSS** [comment]
大佬 你看清楚一下我的描述。。。购买的时候等级过期时间是按帐号当前等级过期时间增加，而不是购买的时间。除非当前帐号的等级过期时间是默认的那个1989-06-04 00:05:00。
打个比较远的比方，我的等级2016年3月1日过期，我在2017年3月1日购买，等级过期时间变成2016年4月1日，而不是2017年。购买没有意义了。

**Comment by nailuoGG** [comment]
当前帐号等级已经过期，购买商品后，等级从购买时间开始生效

如果当前帐号等级没有过期，购买商品后，等级有效时间应该是叠加到已有等级上的。
