### ISSUE TITLE
SMTP发邮件问题

### ISSUE THREAD

**Issue by sooemma** [esdeathlove/ss-panel-v3-mod#725]
程序类型（前端/后端）： 前端

问题发生时所进行的操作：正确设置了smtp设置   注册时邮箱填写正确 点击发送也提示邮件已发送但是收不到邮件

问题所造成的影响：收不到邮件验证码无法注册

调试日志（按照上面的调试方法得到）：无调试日志。 
25端口
SSL465端口
QQ 163 都不行
烦请各位大佬帮看看是什么问题 万分谢谢

谢谢配合！

**Comment by lucas-chou** [comment]
我也是这个问题~

**Comment by saladinxp** [comment]
qq 完美支持， 你把你的设置复制出来让大家看看是否存在问题呗

**Comment by sooemma** [comment]
- 
![image](https://cloud.githubusercontent.com/assets/26247054/23823911/7f750934-06a7-11e7-99d4-677baaf3e720.png)

**Comment by sooemma** [comment]
![1](https://cloud.githubusercontent.com/assets/26247054/23823915/9a11f284-06a7-11e7-91f9-8e3f53934a48.png)
![12](https://cloud.githubusercontent.com/assets/26247054/23823918/9ed1356e-06a7-11e7-9738-13d8ba8e317c.png)
 @saladinxp 
都不能收到邮件

**Comment by saladinxp** [comment]
@sooemma 我用126测试的时候是打死不行
用qq一次成功，你还是用qq的测试下吧  当然你得弄个
qq的设置基本是
smtp.qq.com
xxxx@qq.com
465
xxxx@qq.com
xxxx@qq.com
授权码
true  

这样应该就没问题了

**Comment by sooemma** [comment]
@saladinxp  非常感谢 原来是name sender也要用邮箱填邮箱全名  非常感谢

**Comment by saladinxp** [comment]
@sooemma  stmp name可以不用写邮箱名字，可以写其他东西，只是我懒得写别的直接复制完事

**Comment by sooemma** [comment]
@saladinxp 原来是这样，总之很感谢了。

**Comment by lucas-chou** [comment]
@sooemma 请问解决了吗？
