### ISSUE TITLE
git pull时出现error

### ISSUE THREAD

**Issue by gdasoul** [esdeathlove/ss-panel-v3-mod#726]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）: ss-panel-v3 glzjin mod 20170217

问题发生时所进行的操作：git pull

问题所造成的影响： 
更新时出现报错，无法更新。
报错内容如下
error: Your local changes to 'resources/views/material/admin/relay/search.tpl' would be overwritten by merge.  Aborting.
Please, commit your changes or stash them before you can merge.

**Comment by esdeathlove** [comment]
git reset --hard
