### ISSUE TITLE
配置多个节点时出现错误

### ISSUE THREAD

**Issue by GBigCousin** [esdeathlove/ss-panel-v3-mod#727]
程序类型（前端/后端）：后端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:最新

问题发生时所进行的操作：执行python server.py并且使用的是modewebapi

问题所造成的影响：无法使用该节点

调试日志（按照上面的调试方法得到）：
![default](https://cloud.githubusercontent.com/assets/25314669/23823429/5f4fa18c-069d-11e7-9997-008c0d3194c6.PNG)

**Comment by totoro52** [comment]
我也是遇到和你一样的情况，我使用我的节点服务器P不通前端的服务器

**Comment by sooemma** [comment]
换成glzjinmod再调试，试试

**Comment by GBigCousin** [comment]
@sooemma 我本地是没有mysql的，只安装了ss的后端，然后主服务器的mysql是在ip/phpmyadmin下的，这是我改成glzjinmod后的日志
![default](https://cloud.githubusercontent.com/assets/25314669/23828138/2e2f92fe-0703-11e7-94e8-278ea34b8afa.PNG)

**Comment by sooemma** [comment]
@GBigCousin 你看看你 userapiconfig 里面NODE ID 和前端是不是一样的还有数据库信息填正确没

**Comment by GBigCousin** [comment]
@sooemma ID是对的
![default](https://cloud.githubusercontent.com/assets/25314669/23828163/40540c34-0704-11e7-92ec-193d17e9683f.PNG)

**Comment by sooemma** [comment]
你把原本的userapiconfig换进去，我看你的server pub addr 都不是原本的127001，
![image](https://cloud.githubusercontent.com/assets/26247054/23828195/349509ba-0705-11e7-976a-60b43a9708b2.png)

**Comment by sooemma** [comment]
@GBigCousin  cant connect mysql 请关闭前端防火墙即可解决。

**Comment by GBigCousin** [comment]
应该不是防火墙的问题吧，我已经关了。mysql配置里的mysql_host我如果直接写主服务器的ip是连接到本地ip上的，我尝试加上斜杠和phpmyadmin的目录后能指向正确的45.XX.XX.137的ip，遗憾的是仍然不能连接上
![111](https://cloud.githubusercontent.com/assets/25314669/23828258/6336957a-0707-11e7-8ebd-28c02264b47d.PNG)
![2222](https://cloud.githubusercontent.com/assets/25314669/23828259/641d852a-0707-11e7-9e02-ed3ec4035058.PNG)

**Comment by sooemma** [comment]
我遇到过cant connect mysql的问题，首先保证你的后端配置正确 ，只要关闭前端防火墙就可以连上
我的后端图
![image](https://cloud.githubusercontent.com/assets/26247054/23828272/0b4bb6dc-0708-11e7-92ca-a3db7aac35a0.png)

**Comment by GBigCousin** [comment]
@sooemma 
问题是他连接的根本不是我要的ip
![1](https://cloud.githubusercontent.com/assets/25314669/23828292/fbf3cb56-0708-11e7-9d7f-95c599e104ce.PNG)
![2](https://cloud.githubusercontent.com/assets/25314669/23828293/fc0fa3bc-0708-11e7-9a18-e5ba963c4cd7.PNG)
下面这张是我换成webapi的日志
![124](https://cloud.githubusercontent.com/assets/25314669/23828296/0e3e31de-0709-11e7-8386-fd788e30717f.PNG)

**Comment by sooemma** [comment]
重装后端 @GBigCousin  直接用mysql模式调试

**Comment by GBigCousin** [comment]
@sooemma 根本不是我要的ip
![default](https://cloud.githubusercontent.com/assets/25314669/23829040/c4c963d6-071f-11e7-8050-3a1c8fec1a69.PNG)

**Comment by sooemma** [comment]
@GBigCousin 加我QQ1141789386慢慢给你说
