### ISSUE TITLE
用户列表无法显示Ajax error 

### ISSUE THREAD

**Issue by afeng1991** [esdeathlove/ss-panel-v3-mod#728]
程序类型（前端/后端）：前段

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:最新版本

问题发生时所进行的操作：从之前的版本升级过来的

问题所造成的影响：无法查看用户列表

调试日志（按照上面的调试方法得到）：已经打开config中的调试模式。安装过依赖[
![08778836-fda4-11e6-9326-c551983a7fb4](https://cloud.githubusercontent.com/assets/22143597/23829270/ee0075ba-0728-11e7-958d-a969a0c7adde.png)
![e8a65334-fda3-11e6-80f9-491613c1208d](https://cloud.githubusercontent.com/assets/22143597/23829271/ef196466-0728-11e7-992b-73eac113ae3a.png)
和这个是一个问题 https://github.com/esdeathlove/ss-panel-v3-mod/issues/704
可以确定不是前段的问题，确定是mysql user 表的问题，因为我采用全新的数据库就正常，用之前老的数据库就出现这个问题。
已经尝试过把之前老的user表的数据导出，然后导入到新的数据库上面，但是还是不行，user表，没有进行过任何修改，不知道为什么会这样。

](url)

**Comment by afeng1991** [comment]
已经解决，原因是因为数据库用户表太大，导致无法一次性载入，修改php执行时间后，恢复正常，给个参考，1W用户，最起码也要6000的执行时间。谢谢TC群的兄弟支持。非常感谢

**Comment by esdeathlove** [comment]
之后会做分段加载。

**Comment by evolot** [comment]
同样问题 改6000时间解决了
max_execution_time = 6000
