### ISSUE TITLE
DataTables warning: table id=table_1 - Ajax error.

### ISSUE THREAD

**Issue by ljk4160** [esdeathlove/ss-panel-v3-mod#729]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:

问题发生时所进行的操作：管理面板
问题所造成的影响：管理面板所有页面都提示ajax错误

调试日志（按照上面的调试方法得到）：没有出现调试界面

弹出ajax弹窗
DataTables warning: table id=table_1 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

另外新版缺少vendor目录,安装后打开页面是空白的,我是将旧的移过来才能打开

**Comment by afeng1991** [comment]
请安装依赖，是缺少依赖引起的问题

**Comment by ljk4160** [comment]
缺少什么依赖?

**Comment by esdeathlove** [comment]
请自行查看更新说明。

**Comment by iyuco** [comment]
同样遇到了一样的问题，请问是哪一个依赖造成的问题？

**Comment by manyang901** [comment]
最新的版本，所有安装均为新安装，商品更改后显示ajax错误，一看所有更新说明，依赖全部安装

**Comment by manyang901** [comment]
@esdeathlove 发现当商品设置将用户等级设为非零数但等级有效期仍为0时报ajax错误，希望加入容错，谢谢
