### ISSUE TITLE
打开邀请码页面报错

### ISSUE THREAD

**Issue by lucas-chou** [esdeathlove/ss-panel-v3-mod#736]
问题：浏览器打开 www.xxxx.com/code 邀请码页面报错：ERR_CONNECTION_RESET
详细描述：浏览器为Chrome  苹果手机safari  安卓手机浏览器
连上shadowsocks之后，用上述软件打开邀请码页面一切正常，断开ss，打开就会报错，但是使用电脑自带的IE9浏览器一切正常，没有出现这样的问题。
![1](https://cloud.githubusercontent.com/assets/26342474/23982084/12cdfb68-0a46-11e7-8f3b-1b1237cd39e0.png)
![2](https://cloud.githubusercontent.com/assets/26342474/23982087/16f83f28-0a46-11e7-84db-a36c740b98c0.png)
![1](https://cloud.githubusercontent.com/assets/26342474/23982088/1906b2d6-0a46-11e7-882f-576238464c4f.png)
![2](https://cloud.githubusercontent.com/assets/26342474/23982092/1a2ac8aa-0a46-11e7-8549-e4bd1949cd38.png)

**Comment by moqiaoduo** [comment]
请打开debug并把结果发上来

**Comment by lucas-chou** [comment]
@moqiaoduo 是这些信息吗？
firefox打不开
![default](https://cloud.githubusercontent.com/assets/26342474/23985725/904fb724-0a5b-11e7-8162-bf3a4c2e0b03.png)
IE能打开
![1](https://cloud.githubusercontent.com/assets/26342474/23985742/abf64fba-0a5b-11e7-8f67-8033a59e29fd.png)
![2](https://cloud.githubusercontent.com/assets/26342474/23985743/ad430318-0a5b-11e7-8871-a21598422f00.png)

**Comment by totoro52** [comment]
并不是这些信息,你要做的是打开thinkphp的debug

**Comment by totoro52** [comment]
而对于前端抓取错误信息，你要做的就是首先将 debug 开关打开，这个开关在 config/.config.php 就是你安装时候编辑的那个设置文件里，看到

$System_Config['debug'] = 'false';

将其改为

$System_Config['debug'] = 'true';

**Comment by lucas-chou** [comment]
@totoro52 config/.config.php 中的开关已经打开了

**Comment by totoro52** [comment]
PHP的版本是多少呢？

**Comment by lucas-chou** [comment]
@totoro52 7.0.7

**Comment by totoro52** [comment]
使用lnmp搭建的还是？

**Comment by lucas-chou** [comment]
@totoro52 对，是lnmp

**Comment by totoro52** [comment]
我以前遇过和你同样的问题 你的地址能不能贴出来 不然你截图下你的vhost下配置文件

**Comment by lucas-chou** [comment]
@totoro52 能否加您，耽误您时间

**Comment by totoro52** [comment]
可以

**Comment by lucas-chou** [comment]
@totoro52 我的QQ2803160721 非常感谢

**Comment by lucas-chou** [comment]
解决了，全部定向到https，感谢@totoro52
