### ISSUE TITLE
同一个节点的IPv4和IPv6如何添加？

### ISSUE THREAD

**Issue by lucas-chou** [esdeathlove/ss-panel-v3-mod#739]
自己尝试以为解决了，结果还是不行，请教过别人，还是没明白，斗胆发个issue。
问题描述：前端在A，后端B同时支持IPv4和IPv6，在面板上同时添加两个地址获得两个node ID，config中只填写IPv4的node ID，这样两个节点都能连上，但是IPv6这个节点是断开状态，不记录人数和流量。请问该如何设置？

**Comment by esdeathlove** [comment]
删除ipv6那个节点即可。ipv6只是个地址，你设置好域名解析在客户端连接的时候进行指向即可。
