### ISSUE TITLE
关于节点列表的流量统计问题

### ISSUE THREAD

**Issue by saladinxp** [esdeathlove/ss-panel-v3-mod#740]
最近刚装了魔改sspanel 感觉功能强大，挺好用的
用了1个星期 发现
节点列表中 流量倍率默认为1 的节点，使用流量正常统计，而流量倍率为0的节点，使用流量一点都没变过这些线路一直流量是0。

后来我把一个流量倍率0改为1000，看了10秒油管，之后再看节点列表中的使用流量从0G一下子变成了7G。
也就是说咱们这个魔改版sspanel 节点列表流量统计的是 结算后的流量，而不是 实际使用的流量。

因为咱们节点设置中 流量上限功能是为了防止超出机器的流量限制，所以是否应该把 节点列表中的流量统计方式从 结算后流量改为 实际使用的流量呢？ 谢谢

**Comment by DreamChanSS** [comment]
你根据你设置的流量倍率设置你的节点流量上限不就行了。流量倍率2 服务器流量1000g 你就设置2000g 不就一样了。

**Comment by saladinxp** [comment]
@DreamChanSS 虽然这是一个不是办法的办法。不过问题是 很多线路是我们联机群免费的线路，俺们群除了阿里云限制流量，其他例如什么日本 香港 欧洲的 俺都是免费的，也就是设置0 的，0的话，不管咋设置还都是0，难道非得把倍率设置成 0.01 用100G  限制1T就设置限制10G？

**Comment by DreamChanSS** [comment]
不明白你什么意思。

**Comment by saladinxp** [comment]
@DreamChanSS 你说倍率2我，我机器流量上限改为2000.那么倍率0 改为多少？

**Comment by DreamChanSS** [comment]
我是说我不明白你的目的。
倍率0肯定是不计流量的。

**Comment by saladinxp** [comment]
@DreamChanSS 我的意思是 希望或者有无办法把节点列表的流量计算从 结算流量改为实际使用流量，这样方便查看实际流量使用。原版是这样，当然可能使用结算流量是为了准确计算用户剩余流量吧？

**Comment by esdeathlove** [comment]
对的，只计算结算的。
