### ISSUE TITLE
安装说明里提及的  .user.ini 不存在

### ISSUE THREAD

**Issue by JiaFeiX** [esdeathlove/ss-panel-v3-mod#742]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:    V3mod

安装指南里提到 的 .user.ini   clone下来的文件库里并没有这个文件， 是新建吗？ 

如下为安装说明里提到的部分：
~~~
[root@vultr vhost]# cd /home/wwwroot/ss.panel/
[root@vultr ss.panel]# chattr -i .user.ini
[root@vultr ss.panel]# mv .user.ini public
~~~

**Comment by saladinxp** [comment]
这文件在你的域名目录中 
前提你用的 lnmp才有。

**Comment by JiaFeiX** [comment]
明白了  ， 是 LNMP 的配置文件之一
