### ISSUE TITLE
想问下php -n xcat initdownload  php -n xcat initQQWry这两个是什么意思啊！执行报错

### ISSUE THREAD

**Issue by ztutu** [esdeathlove/ss-panel-v3-mod#743]
地址ss.ztutu.com 
git pull基本没啥问题
执行这个报错了
google了来一下貌似没有先例
php -n xcat initdownload

php -n xcat initQQWry
貌似没什么影响用到的功能都在正常使用
报错如下：
root@zhanggaoxiang:/usr/share/nginx/ssr# php -n xcat initdownload

Fatal error: Class 'PDO' not found in /usr/share/nginx/ssr/vendor/illuminate/database/Capsule/Manager.php on line 49
root@zhanggaoxiang:/usr/share/nginx/ssr# php -n xcat initQQWry

Fatal error: Class 'PDO' not found in /usr/share/nginx/ssr/vendor/illuminate/database/Capsule/Manager.php on line 49

**Comment by moqiaoduo** [comment]
你看看你有没有
vendor这个目录

**Comment by ztutu** [comment]
@moqiaoduo 
有的。谁知道这个是什么意思xcat initdownload   xcat initQQWry
   4 -rwxr-xr-x  1 root     root    1074 Mar 20 11:48 LICENSE
   4 -rwxr-xr-x  1 root     root    1146 Mar 20 11:48 README.md
   4 drwxr-xr-x  8 root     root    4096 Dec 13 14:48 app
   4 -rwxr-xr-x  1 root     root     466 Mar 20 11:50 bootstrap.php
   4 -rwxr-xr-x  1 root     root     950 Mar 20 11:50 composer.json
  92 -rwxr-xr-x  1 root     root   94074 Mar 20 11:50 composer.lock
1556 -rwxr-xr-x  1 root     root 1591764 Mar 20 11:48 composer.phar
   4 drwxr-xr-x  2 root     root    4096 Mar 20 15:25 config
   4 drwxr-xr-x  6 root     root    4096 Mar 20 11:48 public
   4 drwxr-xr-x  5 root     root    4096 Dec 13 14:48 resources
   4 drwxr-xr-x  2 root     root    4096 Mar 20 11:50 sql
   4 drwxr-xr-x  5 www-data root    4096 Mar 20 08:54 storage
   4 drwxr-xr-x  2 root     root    4096 Mar 20 11:48 tool
  12 -rwxr-xr-x  1 root     root   11592 Feb 18 09:36 torage
   4 drwxr-xr-x 37 root     root    4096 Mar 20 11:52 vendor
   4 -rwxr-xr-x  1 root     root     195 Mar 20 11:48 xcat

**Comment by moqiaoduo** [comment]
“init”意为初始化，总而言之这两个命令就是初始化本地客户端下载和初始化IP库

**Comment by ztutu** [comment]
好的，谢谢了。慢慢研究
