### ISSUE TITLE
执行php xcat syncusers出错 已填加mailgun相关信息

### ISSUE THREAD

**Issue by BlingRabbit** [esdeathlove/ss-panel-v3-mod#746]
程序类型：前端
程序版本（commit id）:51824fe65b103d1f5d85245ccaad0fb43c2ccaf9
>Send sync mail to user: 1
PHP Fatal error:  Uncaught exception 'Mailgun\Connection\Exceptions\InvalidCredentials' with message 'Your credentials are incorrect.' in /home/wwwroot/Rabbit/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php:130
Stack trace:
#0 /home/wwwroot/Rabbit/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(90): Mailgun\Connection\RestClient->responseHandler(Object(Guzzle\Http\Message\Response))
#1 /home/wwwroot/Rabbit/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(80): Mailgun\Connection\RestClient->post('sandboxec97ffe0...', Array, Array)
#2 /home/wwwroot/Rabbit/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(36): Mailgun\Mailgun->post('sandboxec97ffe0...', Array, Array)
#3 /home/wwwroot/Rabbit/app/Services/Mail/Mailgun.php(44): Mailgun\Mailgun->sendMessage('sandboxec97ffe0...', Array, Array)
#4 /home/wwwroot/Rabbit/app/Services/Mail.php(68): App\Services\Mail\Mailgun->send('XXXXXXX@qq.c...', 'Rabbit-\xE5\xAF\x86\xE7\xA0\x81\xE6\x9B...', '<!DOCTYPE html ...', Array)
#5 /home/wwwroot/Rabbit/app/ in /home/wwwroot/Rabbit/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php on line 130

我的mailgun填写的是 DOMAIN和Default Password和Default SMTP Login
                              对应 mailgun_domain和 mailgun_key和mailgun_sender
有没有错误？

**Comment by moqiaoduo** [comment]
mailgun_domain填域名
mailgun_domain填密钥
mailgun_sender填发送人邮箱
