### ISSUE TITLE
单端口多用户无法联网

### ISSUE THREAD

**Issue by Tomzuo** [esdeathlove/ss-panel-v3-mod#748]
@esdeathlove 调了两天了，求解

最新版的前后端，按照教程设置好但端口多用户后，客户端无法联网

调试日志（按照上面的调试方法得到）：
前端配置：
节点：
![1 2](https://cloud.githubusercontent.com/assets/12390842/24283989/c8c6ada8-10a3-11e7-858f-f86971cc44d9.png)
用户：
![1 1](https://cloud.githubusercontent.com/assets/12390842/24283990/c8edb97a-10a3-11e7-8f29-b6ae82041419.png)

客户端日志：
`[Error] Proxy server [***] ClientDecode data error: wrong sha1`
后端显示：

Mar 24 14:25:43 jaffar python[115]: 2017-03-24 14:25:43 WARNING  tcprelay.py:607 TCP data mu redir 127.0.0.1:1080 03093132372e302e302e310438
Mar 24 14:25:49 jaffar python[115]: 2017-03-24 14:25:49 INFO     connectionpool.py:249 Resetting dropped connection: jaffar.ml
Mar 24 14:25:50 jaffar python[115]: 2017-03-24 14:25:50 ERROR    web_transfer.py:386 more than one user use the same port [80]
Mar 24 14:26:15 jaffar python[115]: 2017-03-24 14:26:15 INFO     auto_block.py:86 Read hosts.deny from line 2677
Mar 24 14:26:17 jaffar python[115]: 2017-03-24 14:26:17 ERROR    tcprelay.py:1205 The port is multi user in single port only , but the key remote provided is error or empty, so The connection has been rejected, when connect from ::ffff:54.93.94.126:46855 via port 80
Mar 24 14:26:17 jaffar python[115]: 2017-03-24 14:26:17 WARNING  tcprelay.py:594 Protocol ERROR, TCP ogn data

**Comment by esdeathlove** [comment]
用别的用户扫描单端口多用户连接。

**Comment by Tomzuo** [comment]
@esdeathlove怎么扫描？

**Comment by CherishUUU** [comment]
@Tomzuo 我也是这个问题，解决了么？

**Comment by Tomzuo** [comment]
没有，改回去了，这段时间没用单端口

**Comment by andy501336** [comment]
@esdeathlove 出现同样的问题

**Comment by zaaack** [comment]
我也是，无论是协议式还是混淆式都无法联网，后端日志则是md5加密校验错误，后来改成非单端口的那个选项，单端口就能正常工作了

**Comment by lygzyr** [comment]
同求结果，我也出现同样问题，非单端口一切正常，一旦开始但端口。所有节点都一样，无法上网

**Comment by Tomzuo** [comment]
再次尝试配置单端口多用户，还是失败
