### ISSUE TITLE
提个愿望 希望能用 http://sendcloud.sohu.com发信

### ISSUE THREAD

**Issue by wxliuxh** [esdeathlove/ss-panel-v3-mod#749]
提个愿望 希望能用 http://sendcloud.sohu.com发信,送达率很高

**Comment by nailuoGG** [comment]
发 pull request就好，一起来改

**Comment by wxliuxh** [comment]
我发现这家有模板.改改可以用.就是带附件的看不懂. pull request也不知道怎么开...一脸懵逼
