### ISSUE TITLE
登录ip全部为前端ip

### ISSUE THREAD

**Issue by lithromantic** [esdeathlove/ss-panel-v3-mod#751]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:20170325

问题发生时所进行的操作：在HKB节点上搭了前后端，并开启了443单端口多用户，nginx ssl监听在80端口和444端口，80端口全部301重定向到444强制https，后端配置了443到444的redirect ，其他一切正常

问题所造成的影响：配置后，发现用户登录ip 和注册ip 全部变成了HKB前端IP，无法查看源ip，请问主要是因为redirect 设置造成的吗？另外如果想同时实现 一个节点上装前后端 、SSL、以及443单端口， 如果避免这种情况的发生
 
调试日志（按照上面的调试方法得到）：无报错日志，仅仅无法显示源登录ip

**Comment by lithromantic** [comment]
请求头里面
Request Method:GET
Status Code:200 OK
Remote Address:47.89.55.67:443
所以应该是转发导致的，有什么办法避免吗？

**Comment by nailuoGG** [comment]
你试试 把 80 端口 301 重定向 到 443端口

**Comment by lithromantic** [comment]
你没懂我的意思，因为443单端口多用户已经占用了443端口，所以我ssl监听444，80已经301到444了，redirect也从443到444

**Comment by lithromantic** [comment]
问题问过破瓦醬了，暂时没办法解决。
