### ISSUE TITLE
使用webapi遇到的问题，麻烦帮查看下设置是否正确，谢谢

### ISSUE THREAD

**Issue by shakbari** [esdeathlove/ss-panel-v3-mod#752]
程序类型（前端/后端）：全是最新

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:全是最新

使用mysql正常，但设置webapi时却出错，麻烦帮忙看下设置是否正确，谢谢
前端
![image](https://cloud.githubusercontent.com/assets/26726809/24381879/5d48f484-1385-11e7-8f28-c27efcda53ea.png)

后端设置
![image](https://cloud.githubusercontent.com/assets/26726809/24381918/a3073940-1385-11e7-8743-1b7b7a96d1d4.png)

出错提示：
![image](https://cloud.githubusercontent.com/assets/26726809/24381934/be9d4186-1385-11e7-999b-ef67510f3eb5.png)

谢谢。

**Comment by nailuoGG** [comment]
看起来是网络问题

**Comment by moqiaoduo** [comment]
你看看你后端服务器能不能ping通web端

**Comment by shakbari** [comment]
@moqiaoduo ping域名和ip都可以ping通的。

**Comment by moqiaoduo** [comment]
如果你的后端是新装的并且严格按照教程安装，请给网站安装使用ssl（可以用Let's Encrypt）试试。

**Comment by shakbari** [comment]
@moqiaoduo ssl倒是没安装，晚点用闲置机器安装一个测试下吧先

**Comment by HanC890** [comment]
我也是这个问题
如果数据库和SSR在一台机器那就正常
如果是分开就这样报错
iptables关闭了也不行
站点启用了https

**Comment by chinawenxu** [comment]
不是这个错误，但一样连不上。。

**Comment by FlyxFly** [comment]
上面不是说了request() got an unexpected keyword argument 'json'。
requests 发送json post需要2.4.2以上的版本。请更新requests。
这个应该去你用的后端项目问吧。
