### ISSUE TITLE
关于节点无法正常显示的问题。

### ISSUE THREAD

**Issue by Shiekizhao** [esdeathlove/ss-panel-v3-mod#757]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:2017/3/25通过git pull更新至最新版本

问题发生时所进行的操作：通过用户主页菜单点击节点列表

问题所造成的影响：无法查看节点,提示
Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

调试日志（按照上面的调试方法得到）
![1](https://cloud.githubusercontent.com/assets/15689844/24575443/3bf11e00-16d8-11e7-8152-e60cbd8b7789.png)

**Comment by Shiekizhao** [comment]
其他功能没有影响，一键导入正常。

**Comment by esdeathlove** [comment]
你设置的单端口多用户承载用户不能被找到。

**Comment by Shiekizhao** [comment]
才发现之前设置的80用户过期了，谢谢老哥。
