### ISSUE TITLE
如何修改用户注册时的等级？

### ISSUE THREAD

**Issue by imzmy** [esdeathlove/ss-panel-v3-mod#758]
用户注册时等级是2 用一周后等级变成0 如何实现这个操作？
需要修改那些文件呢？

**Comment by luyuxuan** [comment]
什么文件都不用改，你只要改一下默认值（phpmyadmin里的默认值）就ok了
比如等级默认值你改成2，过期时间默认值改成当前时间加7天

**Comment by imzmy** [comment]
phpmyadmin的哪里啊 我刚才挨个表看了一下 没有发现这个选项啊 不会是 手动一个一个修改吧。。。

**Comment by luyuxuan** [comment]
进入到数据表的页面，最上面有一个结构

**Comment by luyuxuan** [comment]
BTW你造咋从原版升级到魔改版不

**Comment by imzmy** [comment]
不知道啊 我的魔改 没升级过。。。。

**Comment by imzmy** [comment]
![qq 20170405100951](https://cloud.githubusercontent.com/assets/9897302/24686728/3ab31ca6-19e8-11e7-9981-6882bc8bb3df.png)

**Comment by imzmy** [comment]
是哪一个呢。。

**Comment by luyuxuan** [comment]
user表啊

**Comment by imzmy** [comment]
一个一个修改吗。。。

**Comment by imzmy** [comment]
user里面没发现默认设置啊

**Comment by luyuxuan** [comment]
不不不
user表进去后
最上边有一个结构
点开就有默认值

**Comment by luyuxuan** [comment]
截图

**Comment by imzmy** [comment]
![qq 20170405102511](https://cloud.githubusercontent.com/assets/9897302/24687071/3716baa6-19ea-11e7-87ed-285fc0522007.png)

**Comment by imzmy** [comment]
是这个吗

**Comment by luyuxuan** [comment]
最上边有一个结构
点开

**Comment by imzmy** [comment]
![qq 20170405102747](https://cloud.githubusercontent.com/assets/9897302/24687130/8dfa6fb6-19ea-11e7-9d7f-733878104fda.png)
![qq 20170405102754](https://cloud.githubusercontent.com/assets/9897302/24687131/8ea5af16-19ea-11e7-880e-d5ab9e7f9946.png)

**Comment by imzmy** [comment]
好像有点明白了 (๑•̀ㅂ•́)و✧

**Comment by luyuxuan** [comment]
看到“默认”两个字了么？
点修改

**Comment by luyuxuan** [comment]
你网址是啥啊我去看看围观

**Comment by imzmy** [comment]
私聊我 (o゜▽゜)o telegram@cutent

**Comment by imzmy** [comment]
然后修改啥。。。 33改成等级 然后 34 怎么改。。。

**Comment by luyuxuan** [comment]
CURRENT_TIMESTAMP+7*24*60*60

**Comment by luyuxuan** [comment]
加上的是一周的秒数

**Comment by imzmy** [comment]
改好了 测试一下 o((>ω< ))o

**Comment by imzmy** [comment]
加了

**Comment by ouyangmland** [comment]
能给个截图看下你是如何改的这个注册等级时间的吗

**Comment by leoleoasd** [comment]
加微信leoleoasd。@ouyangmland
