### ISSUE TITLE
节点配置问题

### ISSUE THREAD

**Issue by tanix12qly** [esdeathlove/ss-panel-v3-mod#760]
![123](https://cloud.githubusercontent.com/assets/26880202/24624357/2e06ad02-18de-11e7-8130-8b180ef80c6c.PNG)
![1234](https://cloud.githubusercontent.com/assets/26880202/24624359/30b1512e-18de-11e7-8cd1-12c54d0bfc6d.PNG)
如图
前端节点无法连接与工作
后端什么原因暂且未知
然后 已百度过 Google过 没搜到什么
最后才到这里问
求解决！！！

**Comment by s2185363602** [comment]
广东人发来贺电

**Comment by s2185363602** [comment]
应该是ss-go验证那个那里

**Comment by luyuxuan** [comment]
pip安装下试试

**Comment by nailuoGG** [comment]
```bash
pip install -r requirements.txt 
```

**Comment by wxjihao** [comment]
什么系统？如果是 debian 执行：pip install requests
