### ISSUE TITLE
createAdmin和注册用户均不能向radusergroup中添加条目

### ISSUE THREAD

**Issue by backrunner** [esdeathlove/ss-panel-v3-mod#762]
程序类型（前端/后端）：前端
程序版本（前端发版本号，后端发 git log 所看到的 commit id）:最新
问题发生时所进行的操作：php xcat createAdmin、注册用户
问题所造成的影响：不能正常使用radius

注册用户成功不能正常跳转，删除用户不能正常删除且弹出一个没有字的dialog。
添加管理员后radusergroup中的内容也没有变化。
使用的数据库帐户是全局满权限，设置正常，config.php里的设置也正常，数据库可以正常连接。

**Comment by backrunner** [comment]
注：ss-panel的搭建环境是win下的xampp

**Comment by esdeathlove** [comment]
请按照说明发开启debug后故障步骤的抓包。
