### ISSUE TITLE
各位大哥是怎么发送每日邮件的？

### ISSUE THREAD

**Issue by leoleoasd** [esdeathlove/ss-panel-v3-mod#763]
程序类型（前端/后端）：前段

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:3

问题发生时所进行的操作：无

问题所造成的影响：无

调试日志（按照上面的调试方法得到）：无

各位是怎么发送每日邮件的？qq企业邮箱？我用企业邮箱发送，所有qq邮件收信的全退回来了(退信)

**Comment by luyuxuan** [comment]
说我是垃圾邮件让我现在连验证码都发不出去

**Comment by moqiaoduo** [comment]
sendgrid或者sendcloud，国内接收正常，但是每日数量有限。

**Comment by luyuxuan** [comment]
sendcloud？
配置文件里没有啊

**Comment by moqiaoduo** [comment]
用smtp方式发送，具体配置百度一下。关键词：sendcloud smtp

**Comment by roddyofchina** [comment]
可以单独部署一台邮件服务器，smtp。用第三方有限制

**Comment by tang1989324** [comment]
@moqiaoduo sendcloud 有数量限制 问下如何关闭每日邮件 只留下验证和找回密码时邮件功能
