### ISSUE TITLE
运行php -n xcat creatAdmin时的问题

### ISSUE THREAD

**Issue by ILLKX** [esdeathlove/ss-panel-v3-mod#764]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:20170325版本

问题发生时所进行的操作：php -n xcat creatAdmin

问题所造成的影响：运行这条命令后直接弹出"Memo"，请问下是否正常？

**Comment by luyuxuan** [comment]
不正常，你拼错了
xcat在接收到错误的参数的时候会“memo”

**Comment by luyuxuan** [comment]
createAdmin

**Comment by luyuxuan** [comment]
public function boot()
    {
        switch ($this->argv[1]) {
            case("install"):
                    return $this->install();
            case("createAdmin"):
                return $this->createAdmin();
            case("resetTraffic"):
                return $this->resetTraffic();

**Comment by ILLKX** [comment]
感谢，是打少了e
