### ISSUE TITLE
php composer install是出现大量无法安装的包，提示版本不对

### ISSUE THREAD

**Issue by ILLKX** [esdeathlove/ss-panel-v3-mod#765]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:20170325版本

问题发生时所进行的操作：php composer install好像是这样写

问题所造成的影响：弹出了一堆无法安装，提示版本不对

**Comment by nailuoGG** [comment]
把详细的报错信息贴上来吧

**Comment by ILLKX** [comment]
感谢回复，不过因为懒得重装系统也就看不见错误了
