### ISSUE TITLE
求助大佬们 ，geetest 怎么配置？

### ISSUE THREAD

**Issue by 379385331** [esdeathlove/ss-panel-v3-mod#766]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:

问题发生时所进行的操作：不会显示出来

问题所造成的影响：

调试日志（按照上面的调试方法得到）：

谢谢配合！

**Comment by nailuoGG** [comment]
去 geetest 网站申请帐号，把 key 和id 填到 .config.php 文件里

**Comment by EmiHe** [comment]
输入后打开注册页面500错误
