### ISSUE TITLE
网站配置

### ISSUE THREAD

**Issue by ILLKX** [esdeathlove/ss-panel-v3-mod#767]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:20170325版本

问题发生时所进行的操作：打开服务器IP

问题所造成的影响：无法正常看见网站，看见的是感谢安装lnmp一键包的网页

**Comment by speederss** [comment]
请一个字一个字认真理解安装说明

**Comment by zhangweiqiandy** [comment]
/usr/local/nginx/conf/vhost/ss.panel.conf里的server_name后面填你的IP
