### ISSUE TITLE
修改了index.tpl后导致网站出错

### ISSUE THREAD

**Issue by zhangweiqiandy** [esdeathlove/ss-panel-v3-mod#768]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:2017年2月28日

问题发生时所进行的操作：改了/home/wwwroot/ss.panel/resources/views/material/user/index.tpl 后来换回原版文件
问题所造成的影响：网站出现错误404，换回后原版文件后不显示错误404，只是登录不进去，最后重启了服务器，还是同样的问题。获取验证码时只有白框
![image](https://cloud.githubusercontent.com/assets/23313651/24829478/f23a8148-1ca4-11e7-923c-2dca3713b638.png) 怀疑是数据库的问题，但是进入phpmyadmin页面后一片空白

调试日志（按照上面的调试方法得到）：
![image](https://cloud.githubusercontent.com/assets/23313651/24829524/f36cc4f8-1ca5-11e7-83d5-e96ea8e2ebd2.png)
![image](https://cloud.githubusercontent.com/assets/23313651/24829525/fc001b06-1ca5-11e7-9837-f2f44e9b054b.png)
这是phpmyadmin的调试页面
![image](https://cloud.githubusercontent.com/assets/23313651/24829537/58ba8e80-1ca6-11e7-99d8-8b53822b1928.png)

已打开debug，站点是www.maoxiong.tk 
![whoops there was an error](https://cloud.githubusercontent.com/assets/23313651/24834437/8bfbfc72-1d17-11e7-8ce5-f98b2d9a5503.png)

谢谢

**Comment by chinawenxu** [comment]
更新了以后，貌似修改一点点文件都会导致网页不正常。我改个邀请码页面的文字，网站就炸了。。

**Comment by zhangweiqiandy** [comment]
你是怎样解决的？phpmyadmin进不去也很头疼

**Comment by zhangweiqiandy** [comment]
问题解决了。上网找了很久原因，发现果然是mysql数据库有问题，找其他人看了后发现是硬盘太小被塞满了
