### ISSUE TITLE
如何累加流量

### ISSUE THREAD

**Issue by 0936zz** [esdeathlove/ss-panel-v3-mod#769]
发现一个问题，购买流量时，无论商品是否勾选“续费时自动重置用户流量为上面这个流量值”，都会把当前流量直接设置为套餐的流量，不会在当前的流量上累加，是我配置出错了吗？

**Comment by moqiaoduo** [comment]
.config.php里面，$System_Config['enable_bought_reset']一项的值设置为false。

**Comment by 0936zz** [comment]
感谢，已解决
