### ISSUE TITLE
开启debug之后再关闭，网站就一片空白了。

### ISSUE THREAD

**Issue by chinawenxu** [esdeathlove/ss-panel-v3-mod#771]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:25 Mar 2016 

问题发生时所进行的操作：.config.php里打开了一个debug开关，然后关闭了。

问题所造成的影响：网页无法正常打开，一片空白了。

**Comment by Awelling2** [comment]
php debug  nginx debug自己排查

**Comment by esdeathlove** [comment]
那就打开 php 的调试。
