### ISSUE TITLE
radius同步失败

### ISSUE THREAD

**Issue by shuangzhijinghua** [esdeathlove/ss-panel-v3-mod#772]
root@localhost:/home/wwwroot/default# php -n /home/wwwroot/default/xcat syncnas

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Database [radius] not configured.' in /home/wwwroot/default/vendor/illuminate/database/DatabaseManager.php:239
Stack trace:
#0 /home/wwwroot/default/vendor/illuminate/database/DatabaseManager.php(158): Illuminate\Database\DatabaseManager->getConfig('radius')
#1 /home/wwwroot/default/vendor/illuminate/database/DatabaseManager.php(68): Illuminate\Database\DatabaseManager->makeConnection('radius')
#2 /home/wwwroot/default/vendor/illuminate/database/Eloquent/Model.php(3314): Illuminate\Database\DatabaseManager->connection('radius')
#3 /home/wwwroot/default/vendor/illuminate/database/Eloquent/Model.php(3280): Illuminate\Database\Eloquent\Model::resolveConnection('radius')
#4 /home/wwwroot/default/vendor/illuminate/database/Eloquent/Model.php(1880): Illuminate\Database\Eloquent\Model->getConnection()
#5 /home/wwwroot/default/vendor/illuminate/database/Eloquent/Model.php(1853): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#6 /home/wwwroot/defau in /home/wwwroot/default/vendor/illuminate/database/DatabaseManager.php on line 239

config.php内容为：

#Radius数据库设置
$System_Config['radius_db_host']='**';
$System_Config['radius_db_database']='*';
$System_Config['radius_db_user']='*';
$System_Config['radius_db_password']='*'; （均已填写内容）

**Comment by lenovoy450** [comment]
哈喽，你这个问题是怎么解决的呢。能分享一下经验嘛，谢谢。
