### ISSUE TITLE
加了cdn后最近登录记录无法显示源IP

### ISSUE THREAD

**Issue by zhouguangyou1994** [esdeathlove/ss-panel-v3-mod#773]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:20170325

问题发生时所进行的操作：加了cdn

问题所造成的影响：无法查看源IP，全部登录IP为CDN IP

调试日志（按照上面的调试方法得到）：

**Comment by mxihan** [comment]
试试ngnix真实ip模块

**Comment by esdeathlove** [comment]
同上。
