### ISSUE TITLE
迁移网站时遇到的问题

### ISSUE THREAD

**Issue by A1exLiu** [esdeathlove/ss-panel-v3-mod#774]
程序类型（前端/后端）：前端

程序版本:latest

问题发生时所进行的操作：尝试进行网站迁移时出现的问题

问题所造成的影响：网站无法打开（HTTP 500）

调试日志（按照上面的调试方法得到）：

`Warning: require(/home/wwwroot/站点/vendor/autoload.php): failed to open stream: No such file or directory in /home/wwwroot/站点/bootstrap.php on line 17`

`Fatal error: require(): Failed opening required '/home/wwwroot/站点/vendor/autoload.php' (include_path='.:/usr/local/php/lib/php') in /home/wwwroot/站点/bootstrap.php on line 17`

我先将原有机器的前端升级到了最新版本，然后导出了数据库以及vhost的conf文件，然后在新机器上安装好前端，导入数据库并用原有的所有配置文件替换过来，之后就出现了HTTP 500错误，在php.ini内将`display_errors`开启之后得到上述报错信息。

**Comment by A1exLiu** [comment]
@esdeathlove 自查了一下，发现bootstrap.php中Line 17请求的vendor文件夹在当前版本new_master分支中的代码中已经删去，故导致此问题

**Comment by esdeathlove** [comment]
就舍不得看看更新说明？

**Comment by ererermao** [comment]
需要执行：php composer.phar install

**Comment by A1exLiu** [comment]
问题已解决

2017年5月19日星期五，liyang <notifications@github.com> 写道：
