### ISSUE TITLE
 chattr -i .user.ini 报错 求助！！

### ISSUE THREAD

**Issue by SBgfw** [esdeathlove/ss-panel-v3-mod#780]
# 提 issue 之前请注意:
1.这个问题你自己是否已经尝试解决过，但是并没有头绪。
2.这个问题所涉及的相关内容是否能在之前的 issue 以及互联网上搜索到。不能，再往下。
3.这里不提供客服服务，请确认你自己有能力进行调试，方法看[这里](https://github.com/esdeathlove/ss-panel-v3-mod/wiki/%E5%A6%82%E4%BD%95%E6%AD%A3%E7%A1%AE%E5%9C%B0%E6%8E%92%E6%9F%A5%E4%B8%8E%E5%8F%8D%E9%A6%88%E9%97%AE%E9%A2%98)。
4.理解并认同不恰当的 issue 会被关闭，乃至于无法获取到更多的帮助。
5.在描述问题的时候少说无关的废话，再强调你自己是小白也无法获得更多地关注的，省点力气把问题描述得详细些吧。

# 看完了的话，就把上面的删掉。来下面的模板来发 issue 吧。

程序类型（前端/后端）：前段

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:git clone https://github.com/glzjin/ss-panel-v3-mod.git tmp -b new_master && mv tmp/.git . && rm -rf tmp && git reset --hard

问题发生时所进行的操作： chattr -i .user.ini

问题所造成的影响：chattr: No such file or directory while trying to stat .user.ini

调试日志（按照上面的调试方法得到）：chattr: No such file or directory while trying to stat .user.ini

谢谢配合！

求助，安装目录下并没有发现user.ini，按照官方提供的安装步骤进行操作的。

**系统环境：centos7 内核 4.10.10 with lnmp**

求帮忙！

**Comment by SBgfw** [comment]
@esdeathlove

**Comment by SBgfw** [comment]
![1](https://cloud.githubusercontent.com/assets/26626519/25040737/d67ea89c-213d-11e7-8c8d-f40eea6e22ae.PNG)
![2](https://cloud.githubusercontent.com/assets/26626519/25040739/d9ebf7dc-213d-11e7-96b6-2137c60c721d.PNG)

**Comment by SBgfw** [comment]
![3](https://cloud.githubusercontent.com/assets/26626519/25040764/fd17dd0c-213d-11e7-870e-1a9adf8cd85c.PNG)

**Comment by saladinxp** [comment]
你如果完全按照教程操作的话根本不会出错，因为你运行目录都弄错了……

**Comment by saladinxp** [comment]
lnmp 1.4吗？

**Comment by saladinxp** [comment]
你3楼的图不是没user .ini了吗？

**Comment by Zhang-Siyang** [comment]
`la -l`看看

**Comment by esdeathlove** [comment]
没有的话，不用管。
