### ISSUE TITLE
有没有除了nginx或者Apache以外的教程？

### ISSUE THREAD

**Issue by nrtdadmin** [esdeathlove/ss-panel-v3-mod#783]
我想使用的是kangle，能不能做个教程？

**Comment by moqiaoduo** [comment]
之前做过教程，不小心弄丢了。其实也很简单，把kangle当做apache看就行了。注意一下目录绑定就行。

**Comment by nrtdadmin** [comment]
主要是，安装依赖，

2017-04-18 12:16 GMT+08:00 moqiaoduo <notifications@github.com>:
