### ISSUE TITLE
xcat几个操作的含义

### ISSUE THREAD

**Issue by ererermao** [esdeathlove/ss-panel-v3-mod#786]
xcat sendDiaryMail
xcat synclogin
xcat syncvpn
xcat dailyjob
xcat checkjob    
xcat syncnas
我想知道这几个是什么操作，每个的含义是什么

**Comment by moqiaoduo** [comment]
1.发送每日邮件（流量报告）
3.同步vpn用户
4.每日任务
5.检查任务
其他意味不明，可以自己翻一下代码看看

**Comment by ererermao** [comment]
@moqiaoduo  感谢
