### ISSUE TITLE
安装完 打开页面是一片空白。

### ISSUE THREAD

**Issue by huanhome** [esdeathlove/ss-panel-v3-mod#787]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:v3

问题发生时所进行的操作：新安装

问题所造成的影响：按教程一步一步的安装完成后 打开是一片空白。

调试日志（按照上面的调试方法得到）：RuntimeException
Unexpected data in output buffer. Maybe you have characters before an opening <?php tag?

希望能得到帮助。。谢谢

**Comment by esdeathlove** [comment]
请检查你的配置文件php头前是不是添加了其他东西。
