### ISSUE TITLE
在后端配置正确的情况下，前端在该节点的状态中显示橙色惊叹号

### ISSUE THREAD

**Issue by ZeusGamingPlay** [esdeathlove/ss-panel-v3-mod#788]
程序类型（前端/后端）：前端

程序版本：都为最新

问题发生时所进行的操作：同样是配置节点，两台美国洛杉矶VPS在同样操作后图标状态显示为绿色的云

问题所造成的影响：无法添加国内SS节点（含一个香港SS节点）

后端Node ID已经与前端网页上的匹配，跟运营商确认过防火墙不会拦

截SS的流量。

**Comment by ZeusGamingPlay** [comment]
后端使用的是教程中推荐的：https://github.com/esdeathlove/shadowsocks

**Comment by Ehco1996** [comment]
在单人模式下 Python server.py log是什么？

**Comment by esdeathlove** [comment]
请发国内节点的日志。

**Comment by nrtdadmin** [comment]
我也出这个问题，什么都正常，就是黄色感叹号，然后观察窗里面什么也没显示，我加了5个节点，可以正常连接和开账户。

**Comment by nrtdadmin** [comment]
![image](https://cloud.githubusercontent.com/assets/20719889/25983384/117fadee-3717-11e7-908f-07e418027b9b.png)

**Comment by nrtdadmin** [comment]
![image](https://cloud.githubusercontent.com/assets/20719889/25983430/4d34be24-3717-11e7-856d-9703132f4311.png)
