### ISSUE TITLE
页面500

### ISSUE THREAD

**Issue by ererermao** [esdeathlove/ss-panel-v3-mod#789]
### 程序类型（前端/后端）：
前端

### 程序版本（前端发版本号，后端发 git log 所看到的 commit id）:
 2017年3月25日更新的这一版本

### 问题发生时所进行的操作：
安装成功，页面都能访问，也能正常设置。重启vps后，就不行了。
>
 还有另外一个重要的问题：每次vps重启，就必须执行一次`php composer.phar install`,不然就会报vendor文件夹下差某个`.php` ,安装后在报500.

### 问题所造成的影响：
页面500

### 调试日志（按照上面的调试方法得到）：
- 网页版错误日志：请访问[ss.liyang.site](http://ss.liyang.site)  如果网页访问不了，[查看图片](http://note.youdao.com/noteshare?id=339c6f17d7519bff7a7ff2ee1479091f&sub=B64B7173EBE1482780775552506CFEBA)
- nginx中得到的信息：
```
日志：
PHP message: PHP Notice:  Undefined index: authDriver in /home/www/ss.panel/app/Services/Config.php on line 10

Config.php：
public static function get($key)
      {
         global $System_Config;
         return $System_Config[$key];
      }
```
我有认真检查`.config.php`是否填写错误错误的key。没有检查出现来。

### .config.php
.config.php 配置：[点击这里](http://note.youdao.com/noteshare?id=25e6ccd78c45db8fe3f2dd932fab0a0d&sub=73B048A3DCFA4A669993C897D01CA436)

**Comment by ererermao** [comment]
@esdeathlove 麻烦作者指教下

**Comment by esdeathlove** [comment]
你缺了一个配置项 authDriver，应该为误删导致，请按照模板配置文件添加上。

**Comment by ererermao** [comment]
感谢，我重新git clone后，正常了
