### ISSUE TITLE
无法查看用户列表

### ISSUE THREAD

**Issue by 755048652** [esdeathlove/ss-panel-v3-mod#790]
程序类型（前端/后端）：前端

程序版本: 最新版本

问题发生时所进行的操作：用户列表出现如下提示

Data tables warning table id table 1 - ajax error for more information about this error please see http : / / datatables . netto a

问题所造成的影响：无法查看用户列表

调试日志（按照上面的调试方法得到）：

谢谢配合！

**Comment by iyuco** [comment]
遇到相同的问题

**Comment by esdeathlove** [comment]
你的抓包呢？

**Comment by asan1147** [comment]
日志文件过多 删除即可
