### ISSUE TITLE
如何关闭每日邮件？

### ISSUE THREAD

**Issue by tang1989324** [esdeathlove/ss-panel-v3-mod#791]
用的第三方 sendcloud 每日有数量限制，所以想关闭每日邮件 只留下邮箱验证和密码找回邮件功能

**Comment by moqiaoduo** [comment]
去掉dailymail的cron即可

**Comment by tang1989324** [comment]
@moqiaoduo 谢谢，每日备份没有附件 你这个解决了吗？

**Comment by moqiaoduo** [comment]
请在php.ini解除scandir函数的限制。若直接用sendcloud api版，需要按照sendcloud文档修改后支持附件；用smtp版，则正常发送附件。

**Comment by tang1989324** [comment]
@moqiaoduo 可以发下修改后的文档吗 小白不太会= =

**Comment by moqiaoduo** [comment]
抱歉，我也没改过，我直接用的smtp配置sendcloud

**Comment by tang1989324** [comment]
@moqiaoduo   smtp
$System_Config['smtp_host'] = '';
$System_Config['smtp_username'] = '';
$System_Config['smtp_port'] = '';
$System_Config['smtp_name'] = '';
$System_Config['smtp_sender'] = '';
$System_Config['smtp_passsword'] = '';
$System_Config['smtp_ssl'] = 'false';   smtp配置sendcloud 怎么配置的 我好想弄不成功  smtp_name是什么 端口是25？

**Comment by moqiaoduo** [comment]
@tang1989324
$System_Config['smtp_host'] = 'smtpcloud.sohu.com';
$System_Config['smtp_username'] = 'api名字';
$System_Config['smtp_port'] = '25';
$System_Config['smtp_name'] = '站名';
$System_Config['smtp_sender'] = 'xxx@xxx.xxx';
$System_Config['smtp_passsword'] = 'api密码';
$System_Config['smtp_ssl'] = 'false';
按照这个格式就行了

**Comment by tang1989324** [comment]
@moqiaoduo 按照这个设置点了没有反应  smtp_name ']= '站名”; 是自己随意设置的？

**Comment by esdeathlove** [comment]
请按照issue模板来提问题。
