### ISSUE TITLE
关于问答系统

### ISSUE THREAD

**Issue by amaharuka** [esdeathlove/ss-panel-v3-mod#793]
前几天按照说明正确安装配置了wecenter，使用也没有出现任何问题
今天突然发现进入问答系统跳转到了wecenter的登录页面，输入正确的账号密码后仍然再次跳转到登录页面要求登录，求解

p.s. 账号密码没有输错，因为输入错误的账号密码会提示错误

**Comment by esdeathlove** [comment]
请按照issue模板提问，谢谢。
