### ISSUE TITLE
突增60g使用流量

### ISSUE THREAD

**Issue by lithromantic** [esdeathlove/ss-panel-v3-mod#797]
程序类型（前端/后端）：前端 最新版 

问题发生时所进行的操作：今天准备测试不通混淆协议对网速的影响，结果某次测试后发现无法连接，后查明今日流量记录突增60多g，导致账户全部流量用完被停掉

问题所造成的影响：今日流量突增 60多g，应该是个bug 跟你反馈一下

**Comment by esdeathlove** [comment]
1.请不要在问题中指明任何人的名字。
2.请问你的系统版本是？
3.请发出流量使用记录。
