### ISSUE TITLE
安装时composer.phar install 出错

### ISSUE THREAD

**Issue by LYJSPEEDX** [esdeathlove/ss-panel-v3-mod#799]
程序类型（前端/后端）：前端

问题发生时所进行的操作：安装时按照wiki教程，当运行php composer.phar install 命令时

会出现报错：Running composer as root/super user is highly discouraged as packages, plugins and script
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for guzzle/guzzle 3.9.x-dev -> satisfiable by guzzle/guzzle[3.
    - guzzle/guzzle 3.9.x-dev requires ext-curl * -> the requested PHP extension curl is 
  Problem 2
    - Installation request for guzzle/guzzle dev-master -> satisfiable by guzzle/guzzle[d
    - guzzle/guzzle dev-master requires ext-curl * -> the requested PHP extension curl is
  Problem 3
    - Installation request for illuminate/support v5.2.21 -> satisfiable by illuminate/su
    - illuminate/support v5.2.21 requires ext-mbstring * -> the requested PHP extension msystem.
  Problem 4
    - gregwar/captcha v1.1.1 requires ext-gd * -> the requested PHP extension gd is missi
    - gregwar/captcha v1.1.1 requires ext-gd * -> the requested PHP extension gd is missi
    - Installation request for gregwar/captcha v1.1.1 -> satisfiable by gregwar/captcha[v

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI

已经过搜索和摸索仍无法发现问题要点（php拓展缺失？） 求支招 谢谢！！  php是用apt-get安装的

**Comment by 40huo** [comment]
没有 gd、curl、mbstring 库。
