### ISSUE TITLE
请问前端支持api连接的后端SS版本有哪些？

### ISSUE THREAD

**Issue by iyuco** [esdeathlove/ss-panel-v3-mod#800]
原生V3可以通过api连接 ss-py-mu，个人认为api的连接方式对多节点的效率要高不少，之前尝试了通过api连接魔改版和py-mu后端，但是没有成功，这边看到魔改版也有支持api，但是具体设置方面有没有什么需要注意的呢？比如web baseurl是 /mu/ 还是 /mu/v2/ 呢？或者有没有明确支持的可以通过api沟通的后端版本。
谢谢各位大佬的帮助！

**Comment by moqiaoduo** [comment]
应该是mu_mod或者mod_mu

**Comment by iyuco** [comment]
谢谢回复，我只在.config.php中找到如下内容：
```
// mu key 用于校验ss-go mu的请求,半角逗号分隔
$System_Config['muKey'] = '';
```
这个应该就是api的连接方式，不过我使用 shadowsocks-py-mu 与此通信失败，然后魔改版教程中推荐的SSR版本并不支持api的连接方式。

因为觉得远程数据库连接不仅效率低，也存在一定的安全隐患。
或者能提供一下api的连接机制的内容也可以，我可以自己尝试看看改一改。
希望有成功的大佬来指明一下道路，非常感谢！

**Comment by esdeathlove** [comment]
1.发问题请按照模板来。
2. https://github.com/esdeathlove/shadowsocks/wiki/重大更新日志#20170215

多翻翻wiki
