### ISSUE TITLE
用户流量统计不准

### ISSUE THREAD

**Issue by backrunner** [esdeathlove/ss-panel-v3-mod#801]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:20170325

问题发生时所进行的操作：

问题所造成的影响：用户流量统计不准确

我只启用了一个节点，这个节点的流量用了81g，但是所有用户用掉的流量加在一起只有12g。
用了一个今日没有跑流量的账号进行测试，在流量记录里有加起来有4mb左右的记录，我的手机端ssr客户端上的统计也是这个数。但是面板首页那个流量统计里面今日流量先从2.45m跳到3m多，后面多跑了一点流量刷新之后又跳回了2m，而且每次刷新页面这个今日已用都不一样。

**Comment by backrunner** [comment]
流量记录里写的已经跑掉了几十m但是只记录了4m

**Comment by backrunner** [comment]
不是计划任务的问题，不是设置的问题...

**Comment by backrunner** [comment]
查出问题是因为32位的php无法正常处理超过2147483647的u、d值，这两个值都被定义成了int。
希望开发者把这两个值改成float避免类似错误。

**Comment by miaovpn** [comment]
请问是怎么解决的，前端流量统计和后端服务器上的数据真的差很多... 跑了20G的前端连1G还不到，跑了150G的前端显示25G...
