### ISSUE TITLE
ssr-download 客户端下载路径不存在

### ISSUE THREAD

**Issue by miaovpn** [esdeathlove/ss-panel-v3-mod#803]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）: 20170325最新版

问题发生时所进行的操作：检查 crontab -e 中的定时任务，因为用户等级未重置，爬文后知道可能是
 checkjob 问题，于是用 php 命令把任务列都执行一次确保正常。。
几个任务都没报错，就在执行以下命令时发现 找不到 ssr-download 这个文件夹。
![2017-04-30 11 49 59](https://cloud.githubusercontent.com/assets/28225813/25565951/b19782d8-2e03-11e7-994e-30365f1778c5.png)

因为我几天前用您的前端也在另一个测试机上搭了一个，确认 ssr-download 目录是存在的，
路径是 **/www/wwwroot/域名/public/ssr-download**
内有几个客户端压缩包，网站上面供人下载的也是这个路径
而我这边的机器却完全找不到（自然网站那边点下载就404了）
我刚到您这边git目录看，也是真的没有这个文件夹...但搜寻代码却是有指向这个路径的代码
![2017-05-01 12 08 55](https://cloud.githubusercontent.com/assets/28225813/25565864/7598af24-2e02-11e7-8994-a6a74f5aa1e4.png)
![2017-05-01 12 09 08](https://cloud.githubusercontent.com/assets/28225813/25565866/78d3bed6-2e02-11e7-88ff-874c70b149bb.png)

原作者orvice那边一样没有... 应该可以排除他的版本因为我没有搭成过orz

于是当然我回到前端git pull 也没能使它"复原"，目前 cron日志是这样的（似乎正常了？）
![2017-05-01 12 02 26](https://cloud.githubusercontent.com/assets/28225813/25565932/71cadd3a-2e03-11e7-8b8b-442a0f0c40fe.png)
![2017-05-01 12 21 28](https://cloud.githubusercontent.com/assets/28225813/25566004/72c8575c-2e04-11e7-8fd7-a1b3af25bf2d.png)

但消失的客户端依然不复存在。
我现在是想到把另一边的 ssr-download 下载了手动传到目前的服务器
但不知道这样能真的解决问题吗？（这个客户端是不是还会定时更新的？还是都需要手动替换呢？）

是否赵大能够解答下这个疑惑
谢谢

问题所造成的影响：网站客户端无法下载、用户数据重置任务不执行

**Comment by lightpencil** [comment]
**傻孩子**
`mkdir /www/wwwroot/域名/public/ssr-download
cd /www/wwwroot/域名/public/ssr-download
git clone https://github.com/esdeathlove/panel-download.git`

**Comment by gdasoul** [comment]
rm -rf /ssp所在目录/public/ssr-download && 
git clone https://github.com/esdeathlove/panel-download.git /ssp所在目录/public/ssr-download

用这个命令加上crontab的时间可以满足自动计划任务的需要，楼上命令git clone下来的文件是存在panel-download里的。

**Comment by miaovpn** [comment]
感谢，其实我有发现赵大 那个 panel-download 的地址，不过当时一直不得要领。
后来我发现教程中定时任务设置项的 dailyjob 好像本来就会执行这个更新，每天定时更新 ssr-download 目录下的文件，最近的日志输出是这样的：
![2017-05-09_123350](https://cloud.githubusercontent.com/assets/28225813/25835792/621f07c8-34b4-11e7-83d0-08b74bc70c67.png)
![2017-05-09_123420](https://cloud.githubusercontent.com/assets/28225813/25835794/63d89458-34b4-11e7-9db2-31cfb3d21d60.png)
这边应该是正常执行了更新
但也可以看到一个报错信息，我把 Job.php做了如下修改之后
就正常了
![2017-05-09_124123](https://cloud.githubusercontent.com/assets/28225813/25835861/d844b114-34b4-11e7-9399-6afa9b602b98.png)
