### ISSUE TITLE
管理账号生成问题

### ISSUE THREAD

**Issue by Ximxin** [esdeathlove/ss-panel-v3-mod#804]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:ss-panel-v3-mod

问题发生时所进行的操作：我使用的yum命令方式安装都lnmp nginx版本:1.10.2 mariadb版本:5.5.42 php版本:5.6.30

问题所造成的影响：管理账号生成不了

调试日志（按照上面的调试方法得到）：执行生成管理账号的代码后得到以下的报错:
Fatal error: Interface 'JsonSerializable' not found in /home/wwwroot/xmxin.top/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 16

**Comment by esdeathlove** [comment]
请升级PHP版本到 5.6 或以上，注意看安装说明。

**Comment by chenyanmo** [comment]
“请升级PHP版本到 5.6 或以上，注意看安装说明。”
-------------------------------------------------------------
我也是 5.6.30
