### ISSUE TITLE
同步用户出错和后台节点没有添加选项

### ISSUE THREAD

**Issue by mmist** [esdeathlove/ss-panel-v3-mod#807]
[root@ip-172-31-16-187 s.mist.top]# php xcat syncusers
Send sync mail to user: 1PHP Fatal error:  Namespace declaration statement has to be the very first statement in the script in /home/wwwroot/s.mist.top/app/Services/Mail/Smtp.php on line 4

以下是/home/wwwroot/s.mist.top/app/Services/Mail/Smtp.php部分内容
i<?php

namespace App\Services\Mail;

use PHPMailer;
use App\Services\Config;

class Smtp extends Base
{
    private $mail;
    private $config;

    public function __construct()
    {
        $this->config = $this->getConfig();
        $mail = new PHPMailer;
        //$mail->SMTPDebug = 3;                               // Enable verbose debug output
        $mail->isSMTP();                                      // Set mailer to use SMTP
        $mail->Host = $this->config['host'];  // Specify main and backup SMTP servers
        $mail->SMTPAuth = true;                               // Enable SMTP authentication
        $mail->Username = $this->config['username'];                 // SMTP username
        $mail->Password = $this->config['passsword'];                    // SMTP password
    if (Config::get('smtp_ssl') == 'true') {
        $mail->SMTPSecure = (Config::get('smtp_port') =='587'?'tls':'ssl');                            // Enable TLS encryption, `ssl` also accepted
    }
        $mail->Port = $this->config['port'];                                    // TCP port to connect to
        $mail->setFrom($this->config['sender'], $this->config['name']);
        $mail->CharSet = 'UTF-8';
        $this->mail = $mail;
    }

    public function getConfig()
    {
        return [
            "host" => Config::get('smtp_host'),
            "username" => Config::get('smtp_username'),
            "port" => Config::get('smtp_port'),
            "sender" => Config::get('smtp_sender'),
。。。。。。。。。。。。。。
省略
。。。。。。。。。。

第二个问题：
注册时邮箱验证码收不到-点发送后邮箱收不到验证码
我的设置为

$System_Config['mailDriver'] = 'smtp';   // mailgun or smtp or sendgrid
 
# smtp
$System_Config['smtp_host'] = 'smtp.163.com';
$System_Config['smtp_username'] = '13ab@163.com';
$System_Config['smtp_port'] = '465';
$System_Config['smtp_name'] = '13ab@163.com';
$System_Config['smtp_sender'] = '13ab@163.com';
$System_Config['smtp_passsword'] = 'song1234567';
$System_Config['smtp_ssl'] = 'true';
   

#是否启用邀请码注册
$System_Config['enable_invite_code']='true';

#是否启用邮箱验证码
$System_Config['enable_email_verify']='true';

#邮箱验证码有效期
$System_Config['email_verify_ttl']='300';

#单IP可请求验证码次数（上面那个周期内）
$System_Config['email_verify_iplimit']='20';

**Comment by esdeathlove** [comment]
请按照模板发issue。
