### ISSUE TITLE
如何取消网站打开时从谷歌加载字体和样式

### ISSUE THREAD

**Issue by heng19970427** [esdeathlove/ss-panel-v3-mod#810]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:

问题发生时所进行的操作：打开网页时需要从谷歌加载字体和样式http://fonts.googleapis.com/icon?family=Material+Icons    

问题所造成的影响：国内由于加载不了而打开网页过慢，想更换为网站本地加载以提高速度

找了半天也没找到从哪里加载的，望指点迷津！

**Comment by moqiaoduo** [comment]
你可以看看css，翻翻主题文件夹

**Comment by zhouguangyou1994** [comment]
可以负责任的告诉你，google字体服务在国内是可以正常访问的，有国内google节点，并不会慢，自己ping一下fonts.googleapis.com就知道了，你网站加载慢是你服务器的原因

**Comment by heng19970427** [comment]
@moqiaoduo 嗯，已经找到了。
@zhouguangyou1994  如果是我服务器的原因，我也不会来这里发issues。

ping fonts.googleapis.com
正在 Ping googleadapis.l.google.com [203.208.41.36] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。

203.208.41.36 的 Ping 统计信息:
    数据包: 已发送 = 3，已接收 = 0，丢失 = 3 (100% 丢失)，

![image](https://cloud.githubusercontent.com/assets/21993215/25785742/7b15ff52-33ba-11e7-9158-095856b5ad8e.png)

**Comment by heng19970427** [comment]
解决方案，翻墙加载完毕后。从浏览器将Google 字体和样式复制粘贴到css文件内，替换css第一句@import....
