### ISSUE TITLE
更新版本导入glzjin_32.sql提示错误

### ISSUE THREAD

**Issue by e8732** [esdeathlove/ss-panel-v3-mod#811]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:20170507

问题发生时所进行的操作：升级导入glzjin_32.sql时
提示：
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near

问题所造成的影响：无法导入数据库

调试日志（按照上面的调试方法得到）：无需开启调试模式

不知道是个例还是其他人也会出现。

谢谢管理！

**Comment by zhouguangyou1994** [comment]
特地登录告诉你，升级正常，你个别现象

**Comment by miaovpn** [comment]
同是今天更新导入正常

**Comment by leoleoasd** [comment]
升级MYSQL

**Comment by leoleoasd** [comment]
把提示google翻一下不就得了

**Comment by esdeathlove** [comment]
问题还存在吗？
