### ISSUE TITLE
用户列表中在线ip显示问题

### ISSUE THREAD

**Issue by yinws** [esdeathlove/ss-panel-v3-mod#813]
前端

2017.5.8最新

问题所造成的影响：
![image](https://cloud.githubusercontent.com/assets/2763739/25795467/047992ac-3408-11e7-8f58-f0136a51ddd9.png)

之前是去掉了在线ip模块，想问下这里是怎么回事？能显示正常ip吗？

**Comment by esdeathlove** [comment]
已经去掉。
