### ISSUE TITLE
无法加载用户节点配置信息、二维码等

### ISSUE THREAD

**Issue by manyang901** [esdeathlove/ss-panel-v3-mod#815]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:最新

问题发生时所进行的操作：打开用户节点配置信息、二维码等

问题所造成的影响：无法加载显示白框

调试日志（按照上面的调试方法得到）：debug无输出

chrome webconsole

Refused to display 'https://***/user/node/8?ismu=0&relay_rule=0' in a frame because it set 'X-Frame-Options' to 'deny'.
node:1217 GET https://***/user/node/8?ismu=0&relay_rule=0 net::ERR_BLOCKED_BY_RESPONSE
urlChange @ node:1217
onclick @ node:418

新版X-frame权限问题？

**Comment by esdeathlove** [comment]
请自行设置好你的 web 服务器，上网搜索如何设置即可。
