### ISSUE TITLE
New registered user with random group doesn't work correctly

### ISSUE THREAD

**Issue by weky9** [esdeathlove/ss-panel-v3-mod#816]
New registered user with random group doesn't work correctly.
New users are always assigned to group '1'.

I checked the php code, the following code may not right:
/app/Controllers/AuthController.php     line 380
        $user->node_group=$group[rand(0, count($group)-1)];

It should be:
        $user->node_group=$Garray[rand(0, count($Garray)-1)];

Please conform, Thank you!

**Comment by esdeathlove** [comment]
Right ,Thank you,and please send the issue by following the temp next time.
