### ISSUE TITLE
节点列表问题

### ISSUE THREAD

**Issue by manyang901** [esdeathlove/ss-panel-v3-mod#817]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:最新

问题发生时所进行的操作：打开 /user/node

问题所造成的影响：仅显示一个节点且无法打开配置页面

调试日志（按照上面的调试方法得到）：

Whoops\Exception\ErrorException thrown with message "Creating default object from empty value"

Stacktrace:
#22 Whoops\Exception\ErrorException in /home/wwwroot/ss.panel/app/Controllers/UserController.php:503
#21 Whoops\Run:handleError in /home/wwwroot/ss.panel/app/Controllers/UserController.php:503
#20 App\Controllers\UserController:node in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:41
#19 call_user_func in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:41
#18 Slim\Handlers\Strategies\RequestResponse:__invoke in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/Route.php:366
#17 Slim\Route:__invoke in /home/wwwroot/ss.panel/app/Middleware/Auth.php:43
#16 App\Middleware\Auth:__invoke in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/DeferredCallable.php:46
#15 call_user_func_array in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/DeferredCallable.php:46
#14 Slim\DeferredCallable:__invoke in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:73
#13 call_user_func in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:73
#12 Slim\Route:Slim\{closure} in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:122
#11 Slim\Route:callMiddlewareStack in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/Route.php:334
#10 Slim\Route:run in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/App.php:545
#9 Slim\App:__invoke in /home/wwwroot/ss.panel/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php:70
#8 Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware:__invoke in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/DeferredCallable.php:46
#7 call_user_func_array in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/DeferredCallable.php:46
#6 Slim\DeferredCallable:__invoke in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:73
#5 call_user_func in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:73
#4 Slim\App:Slim\{closure} in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:122
#3 Slim\App:callMiddlewareStack in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/App.php:438
#2 Slim\App:process in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/App.php:370
#1 Slim\App:run in /home/wwwroot/ss.panel/config/routes.php:339
#0 require in /home/wwwroot/ss.panel/public/index.php:11

曾更改 X-Frame-Options 配置 DENY -> SAMEORIGIN

firefox web monitor 曾显示 clipboard 未定义

**Comment by esdeathlove** [comment]
请检查单端口多用户是否按照正确步骤来配置了。

**Comment by manyang901** [comment]
谢谢！
