### ISSUE TITLE
这样才能重置总流量啊？

### ISSUE THREAD

**Issue by yueliang223** [esdeathlove/ss-panel-v3-mod#825]
我设置了每日续命获得流量，结果他们越攒越多，一大堆几百GB总流量的人....
我搜索了很久，只有一个重置已用流量的命令。
所以要重置所有人的总流量，我该怎么做？

**Comment by leoleoasd** [comment]
去phpmyadmin
sql执行
update user set traffic_enable = 0 where 1
我可能拼错了自己改一下

**Comment by yueliang223** [comment]
update user settransfer_enable = 0 where 1
求教详细 我这样好像还是错的 提示错误 @leoleoasd

**Comment by yueliang223** [comment]
@leoleoasd 明白了。是update user set transfer_enable = 0 where 1
多打了个t
