### ISSUE TITLE
审计规则能否添加url匹配

### ISSUE THREAD

**Issue by leoleoasd** [esdeathlove/ss-panel-v3-mod#826]
程序类型（前端/后端）：后端

就是说，审计规则能否屏蔽制定的url
这样连https也可以屏蔽了
比如规则(.+\.|^)(360|so)\.(cn|com)
就是屏蔽360搜索

**Comment by nailuoGG** [comment]
既然你已经说了方法，至少先尝试下再来提问

**Comment by leoleoasd** [comment]
@nailuoGG
我当然试过了，不可以
因为数据包铭文匹配比如规则是上面我说的那个那么我google搜索360.cn也会被拦截这不是我想要的效果
并且https根本没卵用
找到了个替代方案，就是改shadowsocks服务器的hosts文件

**Comment by 40huo** [comment]
https的时候数据包是加密的，所以匹配不到，http应该可以。

**Comment by leoleoasd** [comment]
@40huo
麻烦看好，地址匹配 https地址没有加密

**Comment by nailuoGG** [comment]
(=・ω・=) 其实是可以看到 访问地址的哟

不信你在 ss的后端里 用 logrun.sh，tail -f ssserver.log 看看

应该能看到你访问的 https 网站地址

**Comment by leoleoasd** [comment]
对啊，我知道是显示的啊
我就是想要能根据地址屏蔽的功能。。。

**Comment by nailuoGG** [comment]
(๑´ω`๑)

或许要改下正则呢

2017年5月27日 +0800 11:31 leo <notifications@github.com>，写道：

**Comment by leoleoasd** [comment]
我想要的效果是屏蔽https

**Comment by EricFan2002** [comment]
如果https传输内容经过中间能解密那还得了？除非你有源服务器私匙 否则除了host什么也看不见。

**Comment by leoleoasd** [comment]
没人看标题么？？？？
@EricFan2002 
我说的就是host屏蔽！！！url屏蔽！！指定服务器屏蔽！！

**Comment by EricFan2002** [comment]
@leoleoasd 
你的标题指代并不明确。
你的意图可以理解为两方面
1-访问特定host针对域名拦截
那么你可以研究一下HTTP(S) over TCP就会发现host name在明文中，相信屏蔽方法你也知道。
2-针对搜索引擎（eg.google）对特定搜索内容屏蔽
那么你可以研究一下HTTPS协议就会发现POST内容全部加密，你是获取不到的。
最后 ， 我们只是好心帮助，没有必要用这种态度回复谢谢。

**Comment by leoleoasd** [comment]
@EricFan2002 抱歉
对，针对某种host进行拦截，我希望sspanel后端能支持这种方式
