### ISSUE TITLE
如何给mysql host指定端口

### ISSUE THREAD

**Issue by moqiaoduo** [esdeathlove/ss-panel-v3-mod#830]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:ss-panel-v3 glzjin mod 20170513

问题发生时所进行的操作：修改config.php

问题所造成的影响：mysql host一项加上端口仍无法运作（因为我的mysql服务端不是3306端口，需要指定端口）

调试日志（按照上面的调试方法得到）：无

**Comment by dvenwu** [comment]
app/Services/Config.php给在getDbConfig下定义个port试试

**Comment by esdeathlove** [comment]
host:port
