### ISSUE TITLE
请问如何检测并删除那些恶意注册的用户

### ISSUE THREAD

**Issue by zhlzhl123** [esdeathlove/ss-panel-v3-mod#831]
我ss站是半免费的，所以有的人就注册了几十个（就只有邮箱最后一个数字不一样其他都一样的账号一看就知道是恶意刷的）刷我的流量。
有什么办法阻止这种行为，除了使用邀请码来限制注册。

**Comment by ZhangqianStudio** [comment]
邮箱验证？

**Comment by zhlzhl123** [comment]
@ZhangqianStudio 要多几个邮箱也不是难事呀！邮箱也是可以无限注册的。现在好像放弃免费啊

**Comment by yueliang223** [comment]
@zhlzhl123 看注册ip 一样的全删掉
