### ISSUE TITLE
有人知道user表里面t,u,d分别是什么吗？

### ISSUE THREAD

**Issue by bbhxwl** [esdeathlove/ss-panel-v3-mod#833]
哪个是上传，哪个是下载，还有一个是什么。
我说的t不是transfer_enable，
transfer_enable是总流量是吧？

**Comment by moqiaoduo** [comment]
t应该是today？
u是upload，d是download
transfer_enable是限制的流量

**Comment by bbhxwl** [comment]
谢谢，我知道了，t好像是最后使用时间的时间戳，您知道怎么限制某个同时的同时在线吗？
