### ISSUE TITLE
安装失败，谁能介绍下数据库(收费也行)

### ISSUE THREAD

**Issue by bbhxwl** [esdeathlove/ss-panel-v3-mod#837]
程序类型（后端）：

程序版本（485）:

问题发生时所进行的操作：centos6安装不行，7就可以

问题所造成的影响：centos6安装不行，7就可以，谁能给介绍下数据库字段(我学C#的，只想用后端，前台自己做，收费也行)

**Comment by lithromantic** [comment]
一个人连发四条issue  牛逼
