### ISSUE TITLE
用户同时连接IP数 与 中转系统 冲突

### ISSUE THREAD

**Issue by Cnievana** [esdeathlove/ss-panel-v3-mod#842]
程序类型（前端/后端）：前端
程序版本（前端发版本号，后端发 git log 所看到的 commit id）: 09be60f

问题发生时所进行的操作：
在用户连接中转线路时会将中转线路的ip算为用户的ip，从而导致用户同时连接IP数超过规定值

问题所造成的影响：
超过IP数的用户无法使用中转线路

**Comment by esdeathlove** [comment]
暂时没办法，自己调吧。
