### ISSUE TITLE
面板的ssr客户端是否还会自动更新？

### ISSUE THREAD

**Issue by echoowall** [esdeathlove/ss-panel-v3-mod#843]
其他功能都正常了，计划任务也正常运行了（每日备份邮件也正常发了）
但是我记得之前的版本的ssr客户端在面板内是自动更新的，我这次装完好几天了一直没有自动更新，依旧是404，请问有可能是什么造成的？自动更新ssr的命令是什么，谢谢了

**Comment by Axtit** [comment]
ss-panel根目录下执行php xcat setTelegram
