### ISSUE TITLE
前后端在一起，用后端开启代理后无法访问前端网页

### ISSUE THREAD

**Issue by lantudai** [esdeathlove/ss-panel-v3-mod#847]
程序类型：前端

程序版本:new branch

问题发生时所进行的操作：前后端在一个VPS上，开启了后端的代理

问题所造成的影响：无法访问前端网页，但是能正常访问谷歌等

调试日志（按照上面的调试方法得到）：
火狐调试只有请求，没有响应。
主页面提示 “安全连接失败 您尝试查看的页面无法显示，因为已收到数据的可靠性无法证实。”

附加信息:cloudflare的DNS解析，开不开CDN都是这样，前端的其他不同VPS上的节点都能正常访问前端，只有前端自身做的后端无法访问。

**Comment by leoleoasd** [comment]
没出现这样的问题。

**Comment by esdeathlove** [comment]
自己调调cf。
