### ISSUE TITLE
给魔改版写了一个个人可用的支付宝扩展

### ISSUE THREAD

**Issue by discountry** [esdeathlove/ss-panel-v3-mod#848]
参考了 [shadowsocks-manager](https://github.com/shadowsocks/shadowsocks-manager) 的 [WebGUI](https://github.com/shadowsocks/shadowsocks-manager/wiki/WebGUI) 插件，不过人家那个是 nodejs 写的。支付宝官方提供的 php sdk 和屎一样，注释写了半天不知道在讲些啥，我大概封装了一下，不过改动的文件数目比较多，不敢提 PR ，在这里分享一下最关键的封装支付的部分：

[gist 地址](https://gist.github.com/discountry/92c88368acda7c4380e1504fddbb4bd9)

这个接口使用的是支付宝最新开放的面向小商户门店的当面付扫码支付接口，个人也可以申请，是支付宝官方直接提供的。

**Comment by discountry** [comment]
哈哈，刚刚看到貌似已经有老铁提交 PR 了 #829

**Comment by esdeathlove** [comment]
不好意思，有些事情不要做得太完全。
