### ISSUE TITLE
建议添加商品修改用户自动重置流量日和重置流量的功能

### ISSUE THREAD

**Issue by 40huo** [esdeathlove/ss-panel-v3-mod#849]
比如这样一个情况
有商品：添加流量50G，账号等级提升为1，有效期30天；
在config.php里设置了注册时自动重置流量日为1，重置流量5G；

那么有用户30日购买了该商品，流量为55G，等级1，但下月1日的时候又会被重置流量为5G。

自己考虑的解决办法：
购买商品时将自动重置流量日改为0，即不自动重置，靠自动续费添加流量。
用户等级到期时将自动重置流量日改为config.php里的值。
这样似乎可以了？

**Comment by moqiaoduo** [comment]
如果有能力的话，可以修改/app/Command/Job.php里的内容，加一个判断等级是否到期
