### ISSUE TITLE
PHP guzzle/guzzle is abandoned

### ISSUE THREAD

**Issue by bowen628** [esdeathlove/ss-panel-v3-mod#861]
程序类型（前端/后端）：ss-panel-v3-mod 

程序版本（前端发版本号，后端发 git log 所看到的 commit id）: 

问题发生时所进行的操作：安装步骤 第12步

问题所造成的影响：

调试日志（按照上面的调试方法得到）：

`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`

**Comment by esdeathlove** [comment]
不用管。
