### ISSUE TITLE
Ocserv可否限速？

### ISSUE THREAD

**Issue by ouyangmland** [esdeathlove/ss-panel-v3-mod#862]
程序类型（前端/后端）：ocserv

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:0.11.6

问题发生时所进行的操作：无

问题所造成的影响：无

调试日志（按照上面的调试方法得到）：无

ocserv可以进行限速吗？有限速的方法吗？

**Comment by ouyangmland** [comment]
![qq 20170613080818](https://user-images.githubusercontent.com/13723714/27060463-9a78ab76-500f-11e7-9f72-d45e401c6d76.png)
只找到了全局限速的设置，但是注释里面说可以设置单个用户的。不知道到单个用户的如何改动图片中的参数名称

**Comment by esdeathlove** [comment]
不能。
