### ISSUE TITLE
SPAY支付时提示订单号重复

### ISSUE THREAD

**Issue by zhaoyan1245** [esdeathlove/ss-panel-v3-mod#864]
使用SS-PANEL-MOD里的SPAY充值，总是会提示：出现错误:订单号重复,请重新提交[0](说明:如果您不是因为本接口集成调试而看见该错误提醒，请联系本次请求来源网站，本错误属于网站集成接口的错误)
请问一下怎么解决这个bug

**Comment by nailuoGG** [comment]
请按要求提供debug信息

**Comment by wxlost** [comment]
ID重复呗.你吧递归ID改大点改成没用过的ID就可.比如1000
