### ISSUE TITLE
执行  php xcat sendDiaryMail  发生错误

### ISSUE THREAD

**Issue by wsjackys** [esdeathlove/ss-panel-v3-mod#865]
程序类型（前端/后端）：
Nginx 1.8   MySQL 5.6  PHP-7.1
程序版本（前端发版本号，后端发 git log 所看到的 commit id）:

最新版本

问题发生时所进行的操作：

[root@MyServer www.15al.com]# php xcat sendDiaryMail
Send daily mail to user: 1[root@MyServer www.15al.com]# php xcat checkjob
PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /www/wwwroot/15al.com/app/Command/Job.php on line 376
PHP Warning:  file_get_contents(): Failed to enable crypto in /www/wwwroot/15al.com/app/Command/Job.php on line 376
PHP Warning:  file_get_contents(https://github.com/esdeathlove/ss-panel-v3-mod/raw/new_master/bootstrap.php): failed to open stream: operation failed in /www/wwwroot/5al.com/app/Command/Job.php on line 376
PHP Warning:  fopen(/www/wwwroot/15al.com/storage/qqwry.dat): failed to open stream: No such file or directory in /www/wwwroot/15al.com/app/Utils/QQWry.php on line 25

谢谢配合！

**Comment by wsjackys** [comment]
现在执行xcat sendDiaryMail 正常了 但是执行xcat dailyjob  会出现

Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /www/wwwroot/15al.com/app/Command/Job.php on line 164

Warning: file_get_contents(): Failed to enable crypto in /www/wwwroot/15al.com/app/Command/Job.php on line 164

Warning: file_get_contents(https://github.com/esdeathlove/qqwry-download/raw/master/copywrite.rar): failed to open stream: operation failed in /www/wwwroot/15al.com/app/Command/Job.php on line 164

Warning: fopen(/www/wwwroot/15al.com/storage/qqwry.dat): failed to open stream: No such file or directory in /www/wwwroot/15al.com/app/Utils/QQWry.php on line 25

Warning: unlink(/www/wwwroot/15al.com/storage/qqwry.dat): No such file or directory in /www/wwwroot/15al.com/app/Command/Job.php on line 196

Warning: rename(/www/wwwroot/15al.com/storage/qqwry.dat.bak,/www/wwwroot/15al.com/storage/qqwry.dat): No such file or directory in /www/wwwroot/15al.com/app/Command/Job.php on line 197
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7 (delta 3), reused 6 (delta 2), pack-reused 0
Unpacking objects: 100% (7/7), done.
From https://github.com/esdeathlove/panel-download
   35d14e1..625cad1  master     -> origin/master
Updating 35d14e1..625cad1
Fast-forward
 ssr-android.apk |  Bin 3698089 -> 3701139 bytes
 1 files changed, 0 insertions(+), 0 deletions(-)

**Comment by LYJSPEEDX** [comment]
你好请问你的mailgun是三个配置项是怎么配置的呢

**Comment by esdeathlove** [comment]
请检查你的服务器受佛能正常连接到GitHub 。
