### ISSUE TITLE
一个css文件大陆网络无法访问到，可能是被墙了

### ISSUE THREAD

**Issue by wz812180** [esdeathlove/ss-panel-v3-mod#866]
后果：访问网页很慢，因为一直在加载这个文件加载不出来

造成原因：
project.min.css line 1
@import url(https://fonts.googleapis.com/css?family=Roboto:300,300italic,400,400italic,500,500italic);
这个网络样式访问超时

解决方案：翻墙获取到css文件内容手动替换掉网络引用 
@esdeathlove

**Comment by nailuoGG** [comment]
常规问题，这个可以自己替换下

**Comment by wz812180** [comment]
嗯，已经替换了，只是把这个问题说一下 @nailuoGG

**Comment by 40huo** [comment]
谷歌字体都已经解析到国内了啊，没有墙。

**Comment by wz812180** [comment]
我看了另外一个谷歌字体引用是没问题的，只有这一个访问不到，我的网络是徐州电信，站长之家测速了一下，有些地方是红的，红的全是电信网络 @40huo

**Comment by mytsing520** [comment]
浙江电信表示这个文件可以正常被加载，已确认无扶墙
