### ISSUE TITLE
网站打开空白，看了下控制台500错误 

### ISSUE THREAD

**Issue by huigezizj** [esdeathlove/ss-panel-v3-mod#869]
配置完了网站打开空白，看了下控制台500错误 。
.config.php中的debug开启了也没有输出，
然后调试了下发现在index.php的 require PUBLIC_PATH.'/../bootstrap.php'; 这里就报错了。。
这个是哪里的问题？

**Comment by LYJSPEEDX** [comment]
是否有出现failed to open stream: Operation not permitted in ...  这个关键句？

**Comment by dvenwu** [comment]
陷入user.ini怪圈?

Warning: require(): open_basedir restriction in effect. File(/home/wwwroot/ss.panel/bootstrap.php) is not within the allowed path(s): (/home/wwwroot/ss.panel/public/:/tmp/:/proc/) in /home/wwwroot/ss.panel/public/index.php on line 7

Warning: require(/home/wwwroot/ss.panel/bootstrap.php): failed to open stream: Operation not permitted in /home/wwwroot/ss.panel/public/index.php on line 7

Fatal error: require(): Failed opening required '/home/wwwroot/ss.panel/public/../bootstrap.php' (include_path='.:/usr/local/php/lib/php') in /home/wwwroot/ss.panel/public/index.php on line 7

直接把.user.ini干掉也无济于事

**Comment by LYJSPEEDX** [comment]
应该为跨站设置问题 在.user.ini可设置

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 HUAWEI EVA-AL00 发送_
