### ISSUE TITLE
震惊！mailgun 的配置

### ISSUE THREAD

**Issue by LYJSPEEDX** [esdeathlove/ss-panel-v3-mod#871]
程序类型（前端/后端）：后端
问题发生时所进行的操作： mailgun发件一直出错 输入senddailymail先提示The parameters passed to the API were invalid，后来改了一下api的格式再次发送，则提示Uncaught Mailgun\Connection\Exceptions\InvalidCredentials: Your credentials are incorrect.  查询mailgun账户的logs是空的。请问是我本地配置出现了问题吗？ 附配置格式
# mailgun
$System_Config['mailgun_key'] = '92e5b13fe8xxx11beca9d48c773';
$System_Config['mailgun_domain'] = 'sandboxexxxxxcd44bd28098dd296928980a.mailgun.org';
$System_Config['mailgun_sender'] = 'TEST';

问题所造成的影响：邮件无法发送且报错

**Comment by esdeathlove** [comment]
请自己绑定一个域名在mailgun上。
