### ISSUE TITLE
xcat无法进行

### ISSUE THREAD

**Issue by hzy2003** [esdeathlove/ss-panel-v3-mod#872]
程序类型（前端/后端）：
前端
程序版本（前端发版本号，后端发 git log 所看到的 commit id）:
lastest
问题发生时所进行的操作：
xcat创建账户
问题所造成的影响：
无法创建
调试日志（按照上面的调试方法得到）：
PHP Warning:  require(/home/wwwroot/ss.xxx.xxx/vendor/autoload.php): failed to open stream: No such file or directory in /home/wwwroot/ss.xxx.xxx/bootstrap.php on line 17
没有这个目录/vendor/，导致无法执行
域名处理为ss.xxx.xxx

**Comment by ymefg** [comment]
同问

**Comment by esdeathlove** [comment]
请按照安装示例来。除非有明确说明否则不能缺漏任何一步。
