### ISSUE TITLE
扫码登录一直提示解码中

### ISSUE THREAD

**Issue by dolfchan** [esdeathlove/ss-panel-v3-mod#875]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）: 20170620_1

问题发生时所进行的操作：扫二维码发给bot登录

问题所造成的影响：bot一直提示正在解码，大约每2分钟提示一次

调试日志（按照上面的调试方法得到）：
可能由于二维码不够清晰
重启服务器无用
停用bot再启用问题依旧
重新扫描二维码成功登录以后bot依旧提醒正在解码

请问是否能告知解决方法？谢谢。

谢谢配合！

**Comment by tang1989324** [comment]
换一个解码的 记得是online

**Comment by esdeathlove** [comment]
换一个解码器。
