### ISSUE TITLE
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

### ISSUE THREAD

**Issue by kmahyyg** [esdeathlove/ss-panel-v3-mod#880]
[x ]这个问题你自己是否已经尝试解决过，但是并没有头绪。
[x] 这个问题所涉及的相关内容是否能在之前的 issue 以及互联网上搜索到。不能，再往下。
[x] 这里不提供客服服务，请确认你自己有能力进行调试，方法看[这里](https://github.com/esdeathlove/ss-panel-v3-mod/wiki/%E5%A6%82%E4%BD%95%E6%AD%A3%E7%A1%AE%E5%9C%B0%E6%8E%92%E6%9F%A5%E4%B8%8E%E5%8F%8D%E9%A6%88%E9%97%AE%E9%A2%98)。
[x] 理解并认同不恰当的 issue 会被关闭，乃至于无法获取到更多的帮助。

程序类型（前端/后端）：前端的后台程序

程序版本（前端发版本号，后端发 git log 所看到的 commit id）: 8d073e1fc24254b3a245f249b92e554bddebe035   （sec fix）

问题发生时所进行的操作：尝试进行 php -n xcat createAdmin

问题所造成的影响：看提示应该是缺失文件

调试日志（按照上面的调试方法得到）：

_可以确定问题在initQQWry()这里_

root@localhost:/home/wwwroot/ss.panel# php xcat initQQWry
downloading....PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /home/wwwroot/ss.panel/app/Command/XCat.php on line 206
PHP Warning:  file_get_contents(): Failed to enable crypto in /home/wwwroot/ss.panel/app/Command/XCat.php on line 206
PHP Warning:  file_get_contents(https://github.com/esdeathlove/qqwry-download/raw/master/copywrite.rar): failed to open stream: operation failed in /home/wwwroot/ss.panel/app/Command/XCat.php on line 206
PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /home/wwwroot/ss.panel/app/Command/XCat.php on line 209
PHP Warning:  file_get_contents(): Failed to enable crypto in /home/wwwroot/ss.panel/app/Command/XCat.php on line 209
PHP Warning:  file_get_contents(https://github.com/esdeathlove/qqwry-download/raw/master/qqwry.rar): failed to open stream: operation failed in /home/wwwroot/ss.panel/app/Command/XCat.php on line 209

可能是openssl的配置问题，还麻烦dalao指导一下，谢谢。使用的lnmp.org的1.4版本的lnmp，默认配置，ssl证书使用letsencrypt certonly签发，使用正常。

**Comment by esdeathlove** [comment]
更新你系统的CA证书库。

**Comment by kmahyyg** [comment]
这是才安装的ubuntu 16.04，参考网上的办法从windows导出了系统ca并转换为pem进行了更新，没用。

root@localhost:~# curl https://github.com






<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://assets-cdn.github.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">

curl github正常。

**Comment by esdeathlove** [comment]
https://github.com/composer/composer/issues/3346#issuecomment-61487245

环境问题，你应该尝试更加规范的更新方法，比如更新ca包后重新编译php等。其他的，我只能说无能为力，因为没多少人出这种问题。

**Comment by kmahyyg** [comment]
已通过apt源尝试更新ca-certificates包，useless
感谢您提供的issue link，看起来正是我需要的，正在尝试。

**Comment by kmahyyg** [comment]
https://github.com/composer/composer/issues/2798

这个issue 同样有用，供后人参考，问题已解决，感谢。
现在该去lnmp.org提个issue了，编译php的时候指定了错误的证书存储位置。
