### ISSUE TITLE
等级过期时间无效

### ISSUE THREAD

**Issue by Roy47Zhang** [esdeathlove/ss-panel-v3-mod#889]
程序类型（前端/后端）：前端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:目前最新

问题发生时所进行的操作：编辑目标用户等级为2，等级过期时间为第二天0点

问题所造成的影响：第二天0点等级无变化

调试日志（按照上面的调试方法得到）：

谢谢配合！

**Comment by esdeathlove** [comment]
检查 crontab 运行状况，尝试手动运行下 checkjob。
